Check for librsvg 2.52 and replace deprecated functions with new ones
darktable-org/darktable pull request #10026
Opened 2021-09-18 15:54 UTC by piratenpanda

fixes #10013

2021-09-18 16:40 UTC, johnny-bit commented on src/common/utility.c
> +  {
```suggestion
  {
```

2021-09-18 17:13 UTC, flannelhead commented
Thanks for doing this! As far as I understand the [migration docs](https://gitlab.gnome.org/GNOME/librsvg/-/merge_requests/588/diffs), the new APIs were actually introduced already in `librsvg 2.46` – I wonder if they should be used already starting from that version.

2021-09-18 17:30 UTC, piratenpanda commented
I can change to 2.46 if no one objects

2021-09-18 17:38 UTC, flannelhead commented
At least that way the new code would get more exposure and testing as many people don't probably have 2.52 yet.

2021-09-18 17:48 UTC, piratenpanda commented
done

2021-09-18 18:06 UTC, piratenpanda commented
So CI doesn't like 2.46 it seems

2021-09-18 18:07 UTC, johnny-bit commented
Seems like the migration docs are incorrect then since we have this build error in CI:

```
/home/runner/work/darktable/darktable/src/src/common/utility.c: In function ‘_util_get_svg_img’:
/home/runner/work/darktable/darktable/src/src/common/utility.c:426:7: error: implicit declaration of function ‘rsvg_handle_get_intrinsic_size_in_pixels’; did you mean ‘rsvg_handle_get_intrinsic_dimensions’? [-Werror=implicit-function-declaration]
  426 |       rsvg_handle_get_intrinsic_size_in_pixels(svg, &width, &height);
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |       rsvg_handle_get_intrinsic_dimensions
compilation terminated due to -Wfatal-errors.
```

Quite honestly check the versions ;) . I have `librsvg-2.50.7` and i do not have the method.

Actually as seen in https://github.com/GNOME/librsvg/blob/69b32420e6265d50f3cfbecff36ebd9da08cd4ad/include/librsvg/rsvg.h#L970 it's been introduced in 2.52 so you have to sprinkle or correct for that ;)

2021-09-18 18:40 UTC, flannelhead commented
> Seems like the migration docs are incorrect then since we have this build error in CI:

Probably just a misunderstanding of mine. Sorry about the hassle :/

2021-09-18 18:47 UTC, piratenpanda commented
I think the new size determination needs 2.52 and print document 2.46. Shall we discriminate for the two methods or should I leave it at 2.52 for both?

2021-09-18 19:40 UTC, johnny-bit commented
If you want to be correct you can try checking versions from which given methods were introduced. That way the coverage would be greater and would cover what @flannelhead said - that most don't have 2.52 yet but have newer funcions. However current ver is good as-is and it's up to you if you want to play details ;)

2021-09-18 20:10 UTC, piratenpanda commented
rsvg_handle_render_cairo seems to be deprecated in 2.52 as well and not in 2.46 so I think the PR is fine as is: https://github.com/GNOME/librsvg/blob/69b32420e6265d50f3cfbecff36ebd9da08cd4ad/include/librsvg/rsvg-cairo.h#L91

2021-09-19 13:49 UTC, ralfbrown commented
I would suggest refactoring the changes into two functions which each get called from two locations.

2021-09-19 15:33 UTC, piratenpanda commented
> I would suggest refactoring the changes into two functions which each get called from two locations.

yeah, i also don't like the doubled code but I am afraid my C skills are not good enough. I thought it would be good to have functions like the following where the first returns the dimension variable which can then be used like it was before. 

```
RsvgDimensionData getSvgDimension(RsvgHandle svg) {
  RsvgDimensionData dimension;
  // rsvg_handle_get_dimensions has been deprecated in librsvg 2.52
  #if LIBRSVG_CHECK_VERSION(2,52,0)
    double width;
    double height;
    rsvg_handle_get_intrinsic_size_in_pixels(&svg, &width, &height);
    dimension.width = width;
    dimension.height = height;
  #else      
    rsvg_handle_get_dimensions(&svg, &dimension);
  #endif
  return dimension; 
}
```
while the first works I have no idea how to a) pass the cairo surface to the second function. Such thing never happens in the code so I am not sure if this is the right way to to do and b) adding svg stuff to utilities.c and .h seems like the proper place, still seems a bit strange to me. Input very much welcome.
```
void dt_render_svg(RsvgHandle svg, cairo_surface_t cr, double width, double height, double offset_x, double offset_y) {
  // rsvg_handle_render_cairo has been deprecated in librsvg 2.52
  #if LIBRSVG_CHECK_VERSION(2,52,0)
    RsvgRectangle viewport;
	  viewport.x = offset_x;
	  viewport.y = offset_y;
	  viewport.width = width;
	  viewport.height = height;
    rsvg_handle_render_document(&svg, &cr, &viewport, &error);
  #else
    rsvg_handle_render_cairo(&svg, &cr);
  #endif  
}
```

2021-09-19 17:57 UTC, elstoc commented
I think this might need to be added to the 3.6.x branch too, as it's going to cause issues for anyone compiling 3.6 on ArchLinux.

2021-09-19 18:05 UTC, ralfbrown commented
I would just pass in pointers to the dimension structure and cairo surface.
The second function would then beome
```
void dt_render_svg(RsvgHandle svg, cairo_surface_t &cr, double width, double height, double offset_x, double offset_y) {
  // rsvg_handle_render_cairo has been deprecated in librsvg 2.52
  #if LIBRSVG_CHECK_VERSION(2,52,0)
    RsvgRectangle viewport;
	  viewport.x = offset_x;
	  viewport.y = offset_y;
	  viewport.width = width;
	  viewport.height = height;
    rsvg_handle_render_document(&svg, cr, &viewport, &error);
  #else
    rsvg_handle_render_cairo(&svg, cr);
  #endif  
}
```

2021-09-19 18:10 UTC, TurboGit requested changes
A little code clean proposed.

2021-09-19 18:10 UTC, TurboGit commented on src/iop/watermark.c
> +        RsvgRectangle viewport;
```
= { .x = 0,
    .y = 0,
    ... }:
```

2021-09-19 18:10 UTC, TurboGit commented on src/common/utility.c
> +        RsvgRectangle viewport;
```
= { .x = 0,
    .y = 0,
    ... }:

```

2021-09-19 18:34 UTC, piratenpanda commented
So I changed the second function to:
```
void dt_render_svg(RsvgHandle svg, cairo_surface_t &cr, double width, double height, double offset_x, double offset_y) 
{
  // rsvg_handle_render_cairo has been deprecated in librsvg 2.52
  #if LIBRSVG_CHECK_VERSION(2,52,0)
    RsvgRectangle viewport = { 
      .x = 0,
      .y = 0,
      .width = width,
      .height = height,
    };
    rsvg_handle_render_document(&svg, cr, &viewport, &error);
  #else
    rsvg_handle_render_cairo(&svg, cr);
  #endif  
}
```

in the code the surface is created with:
```
cairo_t *cr = cairo_create(surface);
```
and afterwards I call the function with:
```
dt_render_svg(*svg, *cr, final_width, final_height, 0, 0);
```
The compiler now complains about a "invalid use of the incomplete typedef »cairo_t« {alias »struct _cairo«}"

I guess it will be a small change but I am lost where to look. I tried to look for the problem and found some inheritance things but I'm not getting any wiser here

2021-09-19 20:58 UTC, johnny-bit commented
you want `cairo_surface_t` not `cairo_t` ;)

2021-09-20 01:14 UTC, ralfbrown commented
`dt_render_svg(*svg, cr, final_width, final_height, 0, 0);` because you already have `cr` as a pointer and are passing a pointer rather than a structure.

And, my bad, the function header should be
```
void dt_render_svg(RsvgHandle svg, cairo_surface_t *cr, double width, double height, double offset_x, double offset_y) 
```
(My C++ background slipped through.)  I'm surprised my original proposal compiled as straight C code.

2021-09-20 06:32 UTC, piratenpanda commented
So now it compiles but dt segfaults on startup. So I guess I missed something still. I'll take a look when I get back from work, maybe someone spots the obvious mistake earlier

2021-09-20 08:49 UTC, parafin commented
You're copying RsvgHandle this way, which I'm not sure is allowed. You should pass RsvgHandle* as a function parameter, not RsvgHandle.

2021-09-20 15:17 UTC, piratenpanda commented
Thank you! That was indeed the case. It's working now. This is the result of me improvising in C..

2021-09-20 17:05 UTC, TurboGit commented on src/common/utility.h
> +RsvgDimensionData getSvgDimension(RsvgHandle *svg);
Name should be: `dt_get_svg_dimension`.

2021-09-20 17:05 UTC, TurboGit requested changes
dt naming issue.

2021-09-21 21:15 UTC, TurboGit approved these changes
Looks ok now, thanks !

2021-09-21 21:15 UTC, merged

2021-09-21 21:20 UTC, piratenpanda commented
I'll prepare another pr for 3.6 branch tomorrow if that is needed?

2021-09-21 21:42 UTC, TurboGit commented
> I'll prepare another pr for 3.6 branch tomorrow if that is needed?

No, not needed I do not expect more changes to this branch and no more 3.6.x release.