Exposure : enable color matching between pictures
darktable-org/darktable pull request #10581
Opened 2021-12-07 10:30 UTC by aurelienpierre

This is the companion of #10579 for brightness mapping. It works exactly the same, but at the exposure module level.

Also, this removes the previous color-picker auto-tune that was based on min/max RGB detection, suitable only for display-referred workflow and aiming at avoiding clipping in this context.

![Screenshot_20211207_113046](https://user-images.githubusercontent.com/2779157/145012878-3bf4e933-e90e-492a-a258-41531ce342fb.png)

2021-12-07 15:39 UTC, elstoc commented on src/iop/exposure.c
> +  dt_bauhaus_widget_set_label(g->spot_settings, NULL, N_("spot exposure mapping settings"));
As in the other PR, IMO the word "settings" is superfluous in this label.

2022-01-03 12:40 UTC, TurboGit requested changes
Somehow same comments as for the color calibration changes:
1. "settings" is superfluous in label "spot exposure mapping settings"
2. I would probably move this to the bottom of the module
3. In the tooltip put "correction" & "mesure" inside quotes

2022-01-03 12:42 UTC, TurboGit commented
Now another question, how do you see the two modes "automatic" and this PR? Aren't they redundant?

2022-01-03 15:13 UTC, aurelienpierre commented
> Now another question, how do you see the two modes "automatic" and this PR? Aren't they redundant?

Automatic is automatic. It performs histogram normalization based on the distribution of intensities. That may be good for exposure normalization of time-lapses with a fixed camera on a tripod and doesn't require user input after copy-pasting the history on a batch of pictures. 

But that's too blind to the actual image content to work in all cases, for example if the camera is moving and the ratio of highlights vs. shadows changes in the background, the histogram distribution will not allow to anchor the exposure for the subject because it has no idea where the subject is.

So this is a more supervised way of anchoring the exposure over a particular surface of a particular object without the intermediate assumptions over histogram distribution.

2022-01-15 12:19 UTC, elstoc commented
As with the color matching PR, I think this needs a default behaviour for when people aren't performing exposure mapping (the most common use case). Three options

- Have the existing color picker default to 50% lightness when the spot exposure mapping section is collapsed
- Move the color picker into the collapsible section (to the lightness slider)
- Have a second color picker in the collapsible section that targets the measured lightness, and keep the existing color picker to always correct to 50% lightness

As with the color matching PR, I prefer the last option (even though the two pickers might be considered redundant).

The tooltip on the collapsible section seems to have been copied-and-pasted from the color matching PR. Similarly the spot mode tooltip references "color" which looks wrong to me.

2022-01-24 22:43 UTC, elstoc commented
I think this probably also resolves #6588

2022-02-15 12:32 UTC, TurboGit commented
@aurelienpierre : I'd like to make this moving. I'll update this PR to use the new collapsible section support. I'll create a new PR with this. I'll test and if you are OK I'll merge then. I understand the different point of view about the color-picker. We'll revisit this if needed after more feedback. On my side after testing it seems ok as-is.

2022-02-15 18:04 UTC, TurboGit commented
@aurelienpierre : Closing, see #11142

2022-02-15 18:04 UTC, closed without merging

2022-05-09 12:49 UTC, estaf1001 commented
Unfortunately, in DT 3.8.1 there is no such thing as spot mode in the exposure tool.
<a href="https://imgbb.com/"><img src="https://i.ibb.co/j83XHRS/2022-05-09-15-43-27.jpg" alt="2022-05-09-15-43-27" border="0"></a>

2022-05-09 12:50 UTC, elstoc commented
Look at the milestone on the PR. It's scheduled for v4.0.