metadata: allow both horizontal and vertical scroll
darktable-org/darktable pull request #10584
Opened 2021-12-07 22:26 UTC by elstoc

Ironically this change means that the metadata textview fields never have horizontal scroll bars but also means that the widget doesn't increase size horizontally.

Resolves #10582.

2021-12-07 22:50 UTC, phweyland commented
Definitively avoids the bug.
But prevents ellipsizing the labels.
![image](https://user-images.githubusercontent.com/23012047/145117070-63b1547d-3ce5-4f83-b8ce-9ee512126455.png)

GTK_POLICY_EXTERNAL seems to behave the same minus the horizontal scrollbar:
![image](https://user-images.githubusercontent.com/23012047/145117947-75bcdf98-25ad-42a7-b6c7-6dd9fc67cc7e.png)


if @dterrahe has no better idea this may be a workaround.

2021-12-07 23:02 UTC, dterrahe commented
> But prevents ellipsizing the labels

I think this was tried and rejected before for this reason; it doesn't work too well with narrow panels.

2021-12-07 23:08 UTC, elstoc commented
> it doesn't work too well with narrow panels.

But on the other hand if I had wide panels I wouldn't have seen the bug in the first place. In my opinion (and I love narrow panels), the issue reported in #10582 is worse. And I really can't find any other solution, apart from drawing the whole thing manually.

2021-12-07 23:56 UTC, dterrahe commented
> the issue reported in #10582 is worse

That's debatable. That issue shows up while you're typing which is definitely very annoying if you don't touch type, but temporary. If the labels make the entries really narrow, you cannot see the metadata while moving around, so you can't spot errors without scrolling through each entry. Let's disagree on severity. _My_ preference would be to leave as is until someone finds a solution. Just one vote, obviously.

2021-12-08 07:53 UTC, elstoc commented
The alternative is to change it to 
```
gtk_scrolled_window_set_policy(GTK_SCROLLED_WINDOW(swindow), GTK_POLICY_NEVER, GTK_POLICY_ALWAYS);
```
This leave ellipsization intact and seems to prevent the bug but means that scroll bars are always displayed in every entry widget.

2021-12-08 11:15 UTC, phweyland commented
![image](https://user-images.githubusercontent.com/23012047/145199040-17dea309-1825-4272-94af-274baf7ab1de.png)

I prefer this one. The less intrusive one.

To break a word longer than the line, as above, change GTK_WRAP_WORD to GTK_WRAP_WORD_CHAR three lines below.

2021-12-08 11:52 UTC, phweyland requested changes

2021-12-08 11:52 UTC, phweyland commented on src/libs/metadata.c
>      gtk_text_view_set_wrap_mode(GTK_TEXT_VIEW(textview), GTK_WRAP_WORD);
Changing GTK_WRAP_WORD to GTK_WRAP_WORD_CHAR you fix also the case of very long word.
Sorry, 3 lines below

2021-12-08 12:08 UTC, elstoc commented
Latest commit implements the last two suggestions. Perhaps we should consider this a workaround for now and leave the issue open for investigation (or raise a new one).

2021-12-08 12:20 UTC, phweyland approved these changes
For me that's the best we can do for now.

2021-12-08 12:21 UTC, dterrahe commented
> The alternative is to change

I know you want to do something to fix the bug and this is doing something, but all of these options (as well as the _CHAR) were considered at the time and the status quo was picked as the least bad compromise. I don't see a reason to change my view on this, but would be happy to see more feedback.

Since this is not a regression from 3.6.1 and not a crash bug, would it really be appropriate for 3.8, with very little time to collect such feedback?

2021-12-08 12:27 UTC, elstoc commented
@dterrahe can you provide a link to the original discussion please

2021-12-08 12:50 UTC, phweyland commented
> but all of these options (as well as the _CHAR) were considered at the time and the status quo was picked as the least bad compromise. I don't see a reason to change my view on this, but would be happy to see more feedback.

I may be wrong (my memory may fail unfortunately), but I don't remember nor having discussed these options neither having been happy with this really annoying issue. Do you have any link to those discussions ?

2021-12-08 17:25 UTC, dterrahe commented
Don't get me wrong, I'm not claiming there was a lot of discussion of all the options (people were sort of getting fed up with "narrow panels") or that some sort of consensus was reached, so let me rephrase:

> I clearly remember experimenting with all of the fixes suggested here so far and _I_ found all of them worse than the status quo, so _I_ rejected them, not because it wasn't me who didn't come up with them, but even though I did.

Of course that doesn't mean I can't have been wrong about that. But I still feel the same way, so its 2-1 ;-)

Which, in a democracy, means this will probably go against me, which is ok! I just wanted to make the argument that, with narrow panels, _always_ wasting space on vertical scrollbars, when you can expand the height of the textboxes so that you actually _never_ need to scroll, is an unwelcome tradeoff to me. But the bug is very annoying too, so...

BTW the first time this bug was reported it was identified as a regression in GTK https://github.com/darktable-org/darktable/issues/9172 A bug report was filed https://gitlab.gnome.org/GNOME/gtk/-/issues/4042 but not followed up on. Maybe that would be the correcter way forward? Clearly the response that no changes were made _in GtkTextView_ between 3.24.24 and 3.24.29 is insufficient, in that the bug was triggered by simply upgrading gtk. There is a subtle interaction here between wrapping and scrollbar, so indeed the change could well have been elsewhere but only triggered unwanted behavior in TextViews.

2021-12-08 17:53 UTC, dterrahe commented
Please test if #10589 also gets rid of the bug. It only adds the scrollbar when it is needed, i.e. when the textbox is actually being edited. Which takes care of my main complaint against this approach.

It also generically applies the fix to _all_ scrollwrapped textviews, not just metadata. Which is a good thing. Unless it triggers bugs elsewhere. Hence why needs testing :-)

2021-12-08 18:12 UTC, dterrahe commented
Scratch that; metadata is the only place where textviews get scrollwrapped, so this should indeed be local to it. And it also conveniently already has focus in/out callbacks, so #10589 expands the workaround by just one line (and comments).

2021-12-08 21:12 UTC, phweyland commented
@dterrahe thank you for the explanations. 
I understand that wasting space is not desirable, but I would vote here for this fix, as the waste is not so much and still better than showing buggy behaviors.

2021-12-09 01:04 UTC, dterrahe commented
> I would vote here for this ~fix~ workaround

I understand your position.

What I would suggest, if this gets merged, is to have workarounds for specific gtk issues be clearly marked as such in source commentary. That way, there's at least a chance that the workaround can be removed if the cause is fixed. Otherwise, we'll end up with a lot of cruft and suboptimal choices that we can never get rid of, because we don't even know what to test to see if it is still needed. Not _as_ necessary in cases where the workaround doesn't cause any other issues, but in this case, we could easily see someone in future reverting the _ALWAYS because, after all, _AUTOMATIC is the more customary setting.

Yes, git blame will point to this PR, but only until the line gets moved/reformatted/copied all over the place by people who don't understand the reason for the magic invocations but copy them along out of an abundance of caution.

2021-12-09 07:55 UTC, elstoc commented
Comment added

2021-12-10 12:35 UTC, TurboGit approved these changes
Not great to have the scrollbar always on, but better than having the GUI going crazy when entering long text in there!

2021-12-10 12:35 UTC, merged