lib modules: defer widget updates while collapsed
darktable-org/darktable pull request #10846
Opened 2022-01-09 20:01 UTC by ralfbrown

Utility modules which respond to the 'collection changed' signal may end up performing considerable work updating their widgets with large
image libraries (100k+), causing noticable UI lag.  All of this work is unnecessary when the module is collapsed, as the updates can't be
seen by the user.

This patch adds a new signal that is raised when a module is expanded, which allows a module to defer widget updates until it is expanded by
the user.  This is applied to the Collections module (which can take multiple seconds if the active rule is date-time or geotag), but could
also be applied to the Tagging module and possibly others.

2022-01-09 22:18 UTC, dterrahe commented
Tell me if I'm missing something (concurrency? but this is all display thread, right?), but to me it looks like, at least in this particular case, you can achieve the same thing simply by connecting to the "show" signal in gui_init:
`  g_signal_connect(G_OBJECT(self->widget), "show", G_CALLBACK(on_show), self);
`

2022-01-09 23:14 UTC, ralfbrown commented
Not being familiar with Gtk signalling, I didn't think of the "show" signal.  That sort-of works, but causes additional update calls compared to the way I did it.  Specifically, there's an additional call each time Lighttable view is entered with Collections collapsed that doesn't happen with the custom signal.

2022-01-09 23:47 UTC, dterrahe commented
If that can't be handled by an addition check of `dt_lib_gui_get_expanded` in on_expand (that seems to be set _before_ the widget is _show[n]_ so I would _expect_ it to work, but haven't tested), why not just call the on_expand method directly in `dt_lib_gui_set_expanded`:

```
    /* announce that the module has been expanded */
    if (DTGTK_IS_EXPANDER(module->expander) && module->on_expand)
      module->on_expand(module);
``` 
rather than attaching the method to a signal and emitting that signal, which isn't really a pattern used elsewhere. I know the signal allows _anybody_ to catch the event of _any_ module expanding, but is that needed anywhere?

2022-01-10 00:33 UTC, ralfbrown commented
That works.

2022-01-10 01:29 UTC, ralfbrown commented
In checking into where the lag between pressing a hotkey to toggle a color label and the COLLECTION_CHANGED signal being raised was being spent, I discovered that `dt_colllection_update` is called twice.  Since it in turn makes two calls to `_dt_collection_compute_count` which execute the SQL query over the entire library, we could shave off another second or more for complex queries on large libraries if one of the calls could safely be eliminated.  I've tagged the doubled calls with TODO in src/common/collection.c and src/common/selection.c.

2022-01-10 18:26 UTC, dterrahe commented
I've submitted a change to your PR that refreshes any module data only when the draw signal is received for it https://github.com/ralfbrown/darktable/pull/1

That has the advantage that in addition to collapsed modules, also modules hidden along with their side panel do not spend time needlessly updating after a collection change.

2022-02-25 13:23 UTC, TurboGit commented
@ralfbrown : A rebase and conflict resolution is needed here. TIA.

2022-02-25 13:25 UTC, TurboGit commented
BTW, reading @dterrahe comment (https://github.com/darktable-org/darktable/pull/10846#issuecomment-1009210025)  am I wrong to assume that this PR is OBE?

2022-02-25 14:35 UTC, dterrahe commented
That comment was merged into this PR, not submitted separately, so this is still very relevant.

2022-02-25 14:39 UTC, ralfbrown commented
I don't know what you mean by OBE, but dterrahe's changes are included here.

Rebased and conflict resolved, but I did notice a bug in checking out the result -- selecting a date range using the timeline doesn't flag the collections module's display as stale.  I'll look into it over the weekend.

2022-02-25 15:04 UTC, TurboGit commented
Sorry OBE : Overcome By Events

2022-02-25 15:48 UTC, TurboGit requested changes
This breaks the filmstrip content:
- go to darkroom
- change filters say >= 5 stars
- see that the filmstrip is not updated

This is a regression as current master is ok.

2022-03-07 20:58 UTC, ralfbrown commented
Another regression found when I looked at this last weekend: in lighttable, the timeline does not update either when dragging the mouse across it to select a new range of dates.  Unfortunately I wasn't able to track down how the callbacks etc work in the time available.

2022-09-06 16:50 UTC, TurboGit commented
@ralfbrown : I'm proposing to post-pone this for 4.2, is that OK for you? TIA.

2022-09-07 11:59 UTC, ralfbrown commented
> @ralfbrown : I'm proposing to post-pone this for 4.2, is that OK for you? TIA.

Yes.

2022-10-23 22:08 UTC, dterrahe commented
@ralfbrown are you still planning on getting back to this? Looking at #12697 I may need to implement something similar for the mask manager after the recent slider additions to update properties.

From the above I'm not sure if there was an issue with the basic approach or just something related to collection queries specifically.

But now that I'm briefly thinking about this again I worry that widgets that are mainly used via shortcuts but otherwise are hidden would not get updated at all and therefore the changes triggered via shortcuts would be based off stale data.

2022-10-24 14:03 UTC, ralfbrown commented
Won't have time until Spring :(

2022-10-24 14:10 UTC, dterrahe commented
Understood and no worries. Good luck dealing with RL!

2023-04-15 10:05 UTC, TurboGit commented
@ralfbrown : This can certainly be closed after @dterrahe merged https://github.com/darktable-org/darktable/pull/14187 PR?

2023-04-15 12:41 UTC, dterrahe commented
This PR also contains some refactoring and collection recounting optimisation that I haven't carried over, because it is little more daunting (and maybe the cause of the timeline issue that was blocking this? I don't know and didn't look into it).

2023-04-15 13:26 UTC, ralfbrown commented
Rebased.

2023-04-16 16:35 UTC, TurboGit approved these changes
Works for me, thanks!

2023-04-16 16:35 UTC, merged

2023-04-16 18:15 UTC, zisoft commented
With this PR merged I cannot switch tag collections via double click.

With commit ccbd5131dddba654 prior to this everything works fine.