real page-up and page-down for culling
darktable-org/darktable pull request #10912
Opened 2022-01-18 13:37 UTC by Solarer

Currently, the page up / page down buttons in culling modes move the view forward by the number of active images. If this number is small (one or two) it takes very long to scroll through a collection.

I mapped the existing page-up page-down functionality to the up/down arrow keys and made the page up / page down buttons advance the view by the number of thumbnails displayed in the filmstrip at a time. This is a better representation of what a "page" is.

2022-01-18 21:00 UTC, TurboGit commented
I'm not sure if this change is welcome. Indeed the page-up / page-down is moving the culling by the amount of currently displayed image and this is really what a page is. We go to the next group of images changing the whole display (all previously images are not displayed anymore). For me this match perfectly as a page in this case. @AlicVB : what's your take on this?

2022-01-18 22:22 UTC, Solarer commented
@TurboGit you can also see culling as a one-row display with variable row length. 😉 
That is also consistent with what happens in filemanager layout. The zoom slider controls the number of images per row in filemanager layout and pressing arrow up/down in this mode moves the cursor forward by that same number.

2022-01-19 10:33 UTC, AlicVB requested changes
Thanks for your work.
Sadly, I agree with @TurboGit here : this doesn't works very well...
First, we have to keep in mind that lot of users doesn't show filmstrip in culling mode which can ends to even more unpredictable and surprising jumps, not to speak about what happen if you have a filmstrip with a very small height...

More than this issue, I also agree with @TurboGit about what a "page" represent in culling : for me, a page is what is shown on screen... So current implementation seems more logical imo.
That said you're right on one point : up and down arrows are buggy : they should in fact : 
- act like page up/down when there's only 1 row of images in culling
- go forward of the number of images shown in the first line in culling view

but here, we face the issue #2565 that nobody (including me) has been able to solve until now :(

For your initial issue, I think we have 2 options : 
1. consider that culling is not designed to scroll into *lot* of images and one has to return to lighttable to do that (or use filmstrip)
2. implement shift+arrow that would go forward for a fixed number of image (5 for example) like what is done in Writer...

2022-01-19 13:19 UTC, dterrahe commented
> 2\. implement shift+arrow that would go forward for a fixed number of image (5 for example) like what is done in Writer...

Please consider enhancing `_action_process_move` so that `move_size` is passed on to `dt_thumbtable_key_move `and `dt_culling_key_move` and adjusts the step size there. This would get you free configurability of the step size and modifier key through the input ng framework. A default fallback could be defined that changes the stepsize for moves in all directions.

Please also consider that elsewhere the shift modifier is used to select-while-move, so it may not be the most appropriate (although in other cases, sliders for example, shift _does_ imply a larger step size.)

2022-01-19 13:43 UTC, Solarer commented
Thanks for the explanation. 
Is there a way for me to implement this in a generic way so that a user could create a keybinding how page up/down behaves? I would also implement the "move a fixed amount of images" and then it could be mapped as the user sees fit. Can such a keybinding be limited to culling?

2022-01-19 14:01 UTC, dterrahe commented
> Can such a keybinding be limited to culling?

Not easily, no. Since they are both in the same view, you can't map the arrow keys to different actions. So internally this is the same _move_ action that's dispatched to either culling or thumbtable. The same speed adjustment would apply to both.

2022-01-19 14:14 UTC, Solarer commented
Then I am not sure if such a change makes sense.
If I were to advance by some fixed number of images (let's say 10) in filemanager I would most likely end up in a different column which can be disorienting (even more in zoomable filemanager) and it would provide no benefit over current arrow keys or page up/down buttons.
Some months ago I asked about a horizontal scrolling bar for culling and now I feel now more comfortable with the code so I might be able to implement that myself. That would cover my requirement for culling and I would close this PR. #2565 can then take the place of arrow up/down once someone found a solution.
Is that ok? @dterrahe @AlicVB

2022-01-19 14:45 UTC, dterrahe commented
> If I were to advance by some fixed number of images (let's say 10) in filemanager

The _speed_ setting of the shortcut would multiply the existing move by a factor. So if in culling the standard move is 1, you could make it 5, for example. If in filemanager it is one _page_ that would make it 5 pages.

2022-01-19 16:50 UTC, AlicVB commented
@Solarer : yep, if you implement the scrollbars that should work and solve your issue without causing other glitch...
Just remember to do it optional like what is done for lighttable and darkroom (I would default to off because we are in a "special" usecase of culling here imho)

2022-01-19 17:40 UTC, Solarer commented
@AlicVB 
> Just remember to do it optional 

I will. I more or less use culling exclusively (not only for comparing images) and do not want to do a round trip to file manager just for the scrolling. I wonder how many people use culling that way - will ask in the telegram group.

@dterrahe 
thanks for clarifying. But unfortunately it still would not work for me. I mostly use culling with 1 image displayed so I would need a huge multiplier like 10 or even more to get a meaningful speedup in culling but that would make it unusable in any other mode because I would just scroll to the end of the collection instantly :confused: . 

I will close this PR and look into the horizontal scroll bar :+1:

2022-01-19 17:40 UTC, closed without merging

2022-01-19 18:58 UTC, AlicVB commented
> I mostly use culling with 1 image displayed

Yes, culling as not been designedfor this type of use (that doesn't mean it shouldn't work)... just for information, what is the benefit of this over the fullscreen preview ?

2022-01-19 19:08 UTC, dterrahe commented
> I would need a huge multiplier like 10 or even more to get a meaningful speedup in culling but that would make it unusable in any other mode

You can define multiple shortcuts for, say, page down and increase the speed of only one of them. For example PgDn with speed 1 and Alt-PgDn with speed 10. Use the first in filemanager and the second in culling mode. Not saying its as easy as it intelligently adjusting, but maybe it is enough (or at least until you've implemented your preferred solution).

2022-01-19 21:34 UTC, Solarer commented
> what is the benefit of this over the fullscreen preview ?

The filmstrip. When I do my first selection or apply ratings I need to know what the next images will look like. Because if they show the same subject I need to check all of them before I can decide in the best picture. You probably use culling dynamic for this step but I prefer scrolling and seeing one image in near full screen without having to press W.
I am used to this from Lightroom.

2022-01-20 18:13 UTC, AlicVB commented
@Solarer : that's completely another topic, but you know that you can have filmstrip in fullscreen too ? : just use ctrl-F to show it, or press b to show the panels arrow... (note that internally, fullscreen is just a special case of culling)