Use dt_apply_transposed_color_matrix() instead of dot_product() everywhere
darktable-org/darktable pull request #10963
Opened 2022-01-23 07:09 UTC by flannelhead

Use `dt_apply_transposed_color_matrix()` instead of `dot_product()` everywhere.

Two reasons:

1. the code (at least SIMD) code for `dt_apply_transposed_color_matrix()` is better than that for `dot_product()`. This should result in performance gains in IOPs that heavily use color matrices, especially Color calibration.
2. There's no reason to have two ways of doing essentially the same thing.

2022-01-23 07:16 UTC, TurboGit reviewed
Have you run the testsuite ?

2022-01-23 07:18 UTC, flannelhead commented
> Have you run the testsuite ?

Not yet. Is there any way to have it run by CI? Otherwise I'll run the test suite overnight (need my computer for development today ;)

2022-01-23 07:33 UTC, TurboGit commented
> > Have you run the testsuite ?
> 
> Not yet. Is there any way to have it run by CI? Otherwise I'll run the test suite overnight and post results tomorrow (need my computer for development today ;)

Too slow for the CI. I'll run it, will report.

2022-01-23 11:31 UTC, TurboGit commented
All tests are passing on my side.

2022-02-02 10:24 UTC, TurboGit requested changes
OpenCL to be changed too.

2022-02-06 20:51 UTC, flannelhead commented
Thanks for the good point. I'll finish this and update the OpenCL version when time permits - however I'll prioritize other work (https://github.com/darktable-org/darktable/pull/10975) over this one.

2022-08-24 16:56 UTC, flannelhead commented
I'm not interested on working this one as I'm mainly using the GPU/OpenCL paths myself, which will not gain any improvements from this one. If someone wants to pursue this later, feel free to pick this up – there should be measurable improvements available to the CPU paths.

2022-08-24 16:56 UTC, closed without merging