po/collapsible section
darktable-org/darktable pull request #11039
Opened 2022-01-30 18:20 UTC by TurboGit

Rework the collapsible sections. Share code in Gtk for the creation, the update and the style.

The new support has been used in temperature:

![image](https://user-images.githubusercontent.com/467069/151712084-cebd0550-6044-43fc-8900-a21cc0223c60.png)

And in crop:

![image](https://user-images.githubusercontent.com/467069/151712072-44f96017-a154-4e25-b740-d24b30deddda.png)

This idea is to use it consistently to have a common style for collapsible section. Also the section is made visible by using a slight change in the background.

This sections are also intended to be used in the two following PR: #10579 & #10581

2022-01-30 18:21 UTC, TurboGit commented
@Nilvus : I'd like to have your take on the GUI part.

2022-01-30 19:53 UTC, elstoc commented
I think the thing that I dislike the most about the current implementation is the header and expander icon which means that, when collapsed, it's not entirely obvious that it's an expandable section. Part of it is that the expander icon looks too much like the combobox icon (possibly an arrow icon with a stem ↑↓, where up indicates collapsed and down indicates expanded). Perhaps the header could also be coloured the same as the contents?

If we're keeping the same expander icon, putting it on the left hand side might help distinguish it from comboboxes.

2022-01-30 22:06 UTC, TurboGit commented
@elstoc : Agreed, we'll try to come up with something better in the GUI. That's the main motivation for this PR. Once all modules are migrated to the new API we will be able to easily change all the collapsible sections.

2022-01-30 22:15 UTC, elstoc commented
I had wondered whether just a thick-ish full-width line above and below the section might be sufficient (like in the quick access panel). The lines would be above the header and below the bottom of the section so that they appear when the section is collapsed as well as when it is expanded. That way you might not even need a different background colour.

2022-01-31 08:11 UTC, TurboGit commented
Perspective correction module done:

![image](https://user-images.githubusercontent.com/467069/151759120-2fb273a1-1db0-4c75-a5d6-9a0adfb54899.png)

2022-01-31 08:24 UTC, elstoc commented
probably should add the import module to your list if you haven't already

2022-01-31 09:07 UTC, TurboGit commented
The color calibration is done : 

![image](https://user-images.githubusercontent.com/467069/151766296-5675d38e-cf59-4c54-ac3b-0acfa058c7c6.png)

2022-01-31 10:59 UTC, TurboGit commented
And the import lib: 

![image](https://user-images.githubusercontent.com/467069/151782001-9db6e021-bca3-4511-ba4d-99877f060377.png)

2022-01-31 12:31 UTC, TurboGit commented
A little update on the theming of collapsible section. The background is a bit less darkened and a small line on the left is added to outline better the widgets part of the section.

![image](https://user-images.githubusercontent.com/467069/151794034-731af934-b88c-495b-a236-b2e20cc64ab6.png)

![image](https://user-images.githubusercontent.com/467069/151794079-a735a826-ce06-4690-9c14-966e0f7acd2e.png)

![image](https://user-images.githubusercontent.com/467069/151794304-0247bd12-d1b3-44de-830d-cefd2fa0d988.png)

@elstoc : I tried with a vertical line but it does not look good, and ending line on an IOP looks strange.

Anyway, all this is just to make the ball rolling... I'll wait for more input from @Nilvus (and others) to find the best UI for those sections.

2022-01-31 14:22 UTC, TurboGit commented
Minor theme tweak again to avoid having uniform background in collapsible sections, very visible in the import lib. New look compared to previous screenshot it makes quite a difference:

![image](https://user-images.githubusercontent.com/467069/151810281-04476fd6-708a-474b-a670-d88a1da6005f.png)

2022-01-31 15:39 UTC, TurboGit commented
To better differentiate collapsible sections from combo-boxes we may want to use + - as indicator as in this example : 

![Capture d’écran de 2022-01-31 16-37-34](https://user-images.githubusercontent.com/467069/151823834-c9b7a7f1-696a-4781-8ce1-ee78dc4e9b62.png)

(without the colors of course!)

2022-01-31 15:53 UTC, TurboGit commented
@AlicVB : You may want to comment as I have slightly changed the UI of ashift. In fact I'm always using the auto perspective, so I have moved the manual section at the end.

2022-01-31 18:14 UTC, Nilvus commented
I didn't test by now (but will try tonight). Just some quick feedback:
I agree with @elstoc comments here globally. Thinking about how to design better that PR was on my todo-list, so great to see that you work on that. I don't have all drawbacks/mockup about that but maybe this PR will help.

About the icon, the plus/minus button is way better than actual arrow. This could also be sort of diagonal arrow like those icons:

https://icons.getbootstrap.com/icons/arrows-angle-expand/
https://www.iconfinder.com/icons/3680941/arrow_diagonal_direction_expand_location_orientation_icon
https://www.iconfinder.com/icons/7642531/shrink_expand_bigger_big_retract_small_smaller_icon

We could also use on of those icons when it's collapsed and use same icons with arrow inverted (pointed to the center) when section is expanded (so to collapse it). It could be with or without a diagonal line between arrows. Or use same icons and make one or the arrow (depending on the state) bigger than the other.

I'm personally more to the first idea (arrows pointed to the center or the exterior depending on state or use plus or minus way.

That's for the icon. About the background and visual around, I will need to test more and see. Not sure for today and I will have only thursday and a little time this week-end.

2022-01-31 18:59 UTC, AlicVB commented
@TurboGit : I'm not against inversing the "auto" - "manual" blocks, but I would prefer to have both under the expander. The idea under that is that the main feature is the rotation, and most users will not use perspective at all (it's only useful for few percentage of subjects...)
And the expanded state is saved...

Now for the new "design", I agree with all of you and find the +- icon better (like the ones you propose in your colored example) But I find the "horizontal + vertical lines strange... imho it just clutter the UI a little more and in fact put the focus on the "expanded" section although that's usually not the most important part of the module...

I've played a little with css and was able to do something like :
![Capture d’écran_2022-01-31_19-49-42](https://user-images.githubusercontent.com/1818223/151854805-67018961-6939-4cbe-bd8d-796bc36f9ba3.png)
 to do that, I've added `gtk_widget_set_name(cs->expander, "collapse-block");` in gui/gtk.c line 3363
and then applied the following css (with the box in prefs) : 
```
#collapse-block,
#iop-plugin-ui #collapsible #bauhaus-slider
{
 background-color: shade(@plugin_fg_color, 0.54);
}
#collapsible,
#collapse-block #section_label
{
  border: none;
  background-color: shade(@plugin_fg_color, 0.54);
}
#collapse-block .section-expander
{
  margin: 0.1em 0;
}
```

2022-01-31 19:26 UTC, TurboGit commented
> @TurboGit : I'm not against inversing the "auto" - "manual" blocks, but I would prefer to have both under the expander. The idea under that is that the main feature is the rotation, and most users will not use perspective at all (it's only useful for few percentage of subjects...)
> And the expanded state is saved...

Well, since I'm often using the perspective and never the manual stuff, can we agree on having both under a collapsible section? This way a user can have the one he uses opened and the other folded?

2022-01-31 19:27 UTC, TurboGit commented
> I've played a little with css and was able to do something like :

I very like this one, and I think this is exactly what @elstoc hinted in a previous message. For me that's the best proposal at the moment.

2022-01-31 19:28 UTC, AlicVB commented
> Well, since I'm often using the perspective and never the manual stuff, can we agree on having both under a collapsible section? This way a user can have the one he uses opened and the other folded?

yes of course, no problem !

2022-01-31 19:29 UTC, elstoc commented
> For me that's the best proposal at the moment.

Agreed

2022-01-31 19:59 UTC, TurboGit commented
I've just pushed a new proposal based on @AlicVB proposal. This is certainly a best starting point for the final proposal.

2022-01-31 20:17 UTC, elstoc commented
I don't see the different colours when I build it (darktable-elegant-grey theme), and personally I'd prefer if we could put the formatting within the existing borders (so that the controls in the collapsible section don't have a different width to the rest of the module)

2022-01-31 20:32 UTC, TurboGit commented
@AlicVB : After thinking more I withdraw my proposal. Having a collapsible section for only 2 lines of icons is not good to me, and after all the module is named **rotate and perspective**, seems ok to have the tools for both readily available.

2022-01-31 20:34 UTC, TurboGit commented
> and personally I'd prefer if we could put the formatting within the existing borders (so that the controls in the collapsible section don't have a different width to the rest of the module)

How? The only way is to remove the padding but in this case the text will be on the border. I tried this and it doesn't look good. Or do you see another way?

2022-01-31 20:41 UTC, elstoc commented
> How?

Ah now that's the question - I'm afraid I haven't looked into the practicalities. There is a non-zero border between normal module controls and the edge of the module so I'd say we need some way to place the collapsible box edge half way into that existing border. I'm sure there must be a way.

2022-01-31 20:46 UTC, TurboGit commented
@elstoc : Personally I find the padding nice. I see that as a nested block, it also help to see it as a grouped set of controls as not only the background stand out but also the formatting.

2022-01-31 20:56 UTC, elstoc commented
The following very quick and dirty experiment 
```
#iop-plugin-ui-main #collapse-block
{ margin-left: -0.4em; margin-right: -0.4em;  }

#iop-plugin-ui-main #collapse-block #collapsible
{ padding-left: 0.4em; padding-right: 0.4em; }
```
Looks like this:

![Screenshot_2022-01-31_20-55-35](https://user-images.githubusercontent.com/9555491/151871677-3fab4870-73c6-44e1-8d77-d867a9f7b472.png)

This is not anywhere near perfected but it illustrates what's possible.

2022-01-31 21:01 UTC, TurboGit commented
@elstoc : I have fixed the colors on grey theme.

I'm really not fond of the wide panel, even wider than the actual content on the other part. We'll see what can be done/proposed.

2022-01-31 21:05 UTC, elstoc commented
> I'm really not fond of the wide panel

I think one problem here is that the background colour (on the darktable theme anyway) is too strong a contrast with the rest of the module. Would a bounding box (thin border) be better?

2022-01-31 21:07 UTC, Nilvus commented
@AlicVB proposal is much better. I don't like too wide panel. But we could find something better anyway. I will try ASAP to test some CSS settings on that. But this probably not before thursday or the end of the week. 
A thin border could maybe be a think to test. Some other things probably to test/check. No hurry ;-)!

2022-02-04 22:33 UTC, Nilvus commented
Some proposals:

![image](https://user-images.githubusercontent.com/45535283/152611518-7cac5704-09ae-439b-ae18-351de8e1dc5c.png)

![image](https://user-images.githubusercontent.com/45535283/152611549-ec0c328c-393f-4705-a271-1d01ab58588d.png)

or (with the same border as user css editor):

![image](https://user-images.githubusercontent.com/45535283/152611655-8686adb2-c24e-4d05-ad39-652f9cf64bf4.png)

![image](https://user-images.githubusercontent.com/45535283/152611627-d13a05fa-d42c-4f19-8986-6fdee3177cdb.png)

First CSS code set is that one:

```
@define-color collapsible_bg_color @selected_bg_color;

/* Collapsible sections on lib & iop modules */

#collapse-block,
#collapsible #bauhaus-slider
{
  border: 0.07em inset @border_color;
  background-color: @collapsible_bg_color;
}

#collapsible,
#collapse-block #section_label
{
  padding: 0 0.14em 0.14em 0.7em;
  margin: 0;
}

/* for the import parameters to be more aligned with the imports buttons */
#lib-plugin-ui #collapse-block
{
  margin: 0.42em 0.07em;
}

#collapse-block .section-expander
{
  margin: 0.1em;
}

#collapse-block #section_label
{
  border-bottom: none;
}
```
For second choice (border of user css editor), just change first border line on above code to (from line 1221 of darktable.css):

`  border: 0.07em inset @border_color;`

CSS is not over, remains some works to do on combobox, checkbox... in import module. And I agree with @elstoc, some margins are too important. But it's not on that PR and on those expander code that this should be changed. I think modules margins need to be reduced a little. Will make some tests and propose that (if all good) in my UI Improvements PR.

@TurboGit: depending on answer (and especially about border choice), feel free to integrate the code on your PR here.

Will work more ASAP on all that (margins and import module content).

2022-02-04 22:38 UTC, Nilvus commented
If you read last comment on mail, read it again here, I see mistakes and update to a better proposal for first one.

2022-02-04 23:51 UTC, elstoc commented
I prefer the first proposal - I don't really like the inset border. I was suggesting a border without an altered background-color but I've tried it and I'm not so sure now:

![Screenshot_2022-02-04_23-50-46](https://user-images.githubusercontent.com/9555491/152618135-4b6bd8eb-0a78-436a-b120-52fe741dfece.png)

2022-02-05 09:01 UTC, TurboGit commented
@Nilvus : I also prefer your first proposal (a more flat design - more modern for whatever it means).

@elstoc : Yep, don't really like the only border... it is hard to see the whole collapsible part.

2022-02-05 10:56 UTC, AlicVB commented
I really prefer @Nilvus first proposal too... Some quick comments : 
- Do we need the borders when the item is collapsed (I find them really strange).
- We really need to rework the icon : with this proposal, the arrow is not "separated" anymore from the regular combobox ones and that's really confusing visually...
- it would be great if we can reduce the "cumulative" margins for this case, but I've not idea how to achieve this...

2022-02-05 12:39 UTC, elstoc commented
> Do we need the borders when the item is collapsed (I find them really strange)

We need something to indicate that it's an expandable selection since it's really not obvious at the moment. Are you suggesting a different background colour but no borders, and then the borders appear when you expand? I'm not sure.

> We really need to rework the icon

Agreed. This has been discussed in a couple of places but that particular arrow icon should really be for comboboxes only (and _maybe_ keep for lib module expansion)

2022-02-06 09:49 UTC, Nilvus commented
Thanks for your feedback. I have proposed both but was too more for my first proposal. So all great we are all agree. It would indeed be better to have something to indicate differently when expanded or not. I agree too on that. I will try to propose something ASAP.

> * Do we need the borders when the item is collapsed (I find them really strange).

I think we need it but a better one than on my proposal. It's not the final one but was a direction to go to. What I have in mind is to have a subtle border between outside collapsible part and collapsible background color, when it is collapsed and a more visible border (like my first proposal) when expanded. But it's something to try with having a different background between title line and content part as suggested here.

> * We really need to rework the icon : with this proposal, the arrow is not "separated" anymore from the regular combobox ones and that's really confusing visually...

Those arrows were from start not a good idea. Even without that proposal, they should change. That's why I've started to do the sort by icon. Those ones are some next step.

> * it would be great if we can reduce the "cumulative" margins for this case, but I've not idea how to achieve this...

This need just some CSS changes and I will do that in my PR UI improvements started on January.

2022-02-06 10:43 UTC, Nilvus commented
Just a new proposal based on your feedback:

![image](https://user-images.githubusercontent.com/45535283/152677100-b44dcdcf-8f47-4751-a330-581bc4f7103a.png)

![image](https://user-images.githubusercontent.com/45535283/152677112-2285fb75-cd69-49e3-bf34-b03007fd5e46.png)

I just work here on CSS, remains some things about combobox, checkboxes to work on (and icon to replace arrow of course).

The CSS:

```
/* Collapsible sections on lib & iop modules */

#collapse-block
{
  border: 0.1em solid shade(@collapsible_bg_color, 0.9);
}

#collapsible,
#collapse-block #section_label
{
  padding: 0 0.14em 0.14em 0.7em;
  margin: 0;
}

#collapsible,
#collapsible #bauhaus-slider
{
  border-top: 0.035em solid  shade(@section_label, 0.7);
  background-color: @collapsible_bg_color;
}

/* for the import parameters to be more aligned with the imports buttons */

#lib-plugin-ui #collapse-block
{
  margin: 0.42em 0.07em;
}

#collapse-block #section_label,
#collapse-block .section-expander
{
  margin: 0.1em;
  background-color: shade(@collapsible_bg_color, 0.95);
}
```

2022-02-06 11:54 UTC, Nilvus commented
Just a thing, If my last proposal is ok for all of you, I propose @TurboGit to integrate my CSS on your PR and then this so could be merged. I will work on improving expanding content (combobox, checkbox, etc.) and propose a new expander icon on a separate PR.

2022-02-06 11:58 UTC, elstoc commented
I think the last proposal looks fine, except maybe the background of the collapsible section is a little bright for my liking.

2022-02-06 12:04 UTC, Nilvus commented
> I think the last proposal looks fine, except maybe the background of the collapsible section is a little bright for my liking.

Yes, you're right. I forget to update define-color line. I suggest for elegant-grey theme, that line:

`@define-color collapsible_bg_color shade(@plugin_fg_color, 0.55);`

And set to 0.45 instead of 0.5 in darktable.css main theme.

2022-02-11 11:47 UTC, Nilvus requested changes
@TurboGit: just a reminder when you have time, to test my CSS proposal for your PR. Of course, feel free to integrate them directly on your PR. I will soon try to work on the +/- icon to replace actual arrow. But will be easier when this PR will be merged in master.

2022-02-11 12:34 UTC, merged

2022-02-11 12:36 UTC, TurboGit commented
@Nilvus : Thanks now merged. I kept 0.5 collapsible_bg_color otherwise it is not really visible on my side. Also I have removed the border on the label, probably you did no saw that as you've added your CSS into the user's section on dt pref. Anyway, all merged now and ready for the +/- icon or whatever you'll come up for better UI. TIA.

2022-02-11 12:40 UTC, Nilvus commented
@TurboGit: that's anyway a great step. Will now start to work on improving that part with the icon and CSS. Thanks.