Improve monochrome images workflow
darktable-org/darktable pull request #11070
Opened 2022-02-06 16:06 UTC by jenshannoschwalm

True monochrome images like those from Leica and images from cameras that have the color
matrix filter in front of the sensor removed should be treated the same in the user interface
as much as possible.

1. The testing function dt_image_is_monochrome() tests for both types of sensors now.
   Also this function - plus a few others - are defined to return a gboolean now instead of int.

2. In colorin.c make sure we use DT_COLORSPACE_LIN_REC709 for both types of monochromes

3. The raw chromatic aberration module should be switched off for monochromes

4. Changing the demosaicer to one of the monochrome passthrough modes works flawlessly.
   But - a number of modules rely on a proper setting of being a monochrome image and the gui widgets need to be updated at runtime.
   To get this working `dt_dev_reload_image()` is executed if the `DT_IMAGE_MONOCHROME_BAYER`
   had changed leading to a complete new setup of all modules.

5. highlights reconstruction does not make sens for raw-monochromes at all, the module gets deactivated and can not be switched on.

6. temperature gets disabled for all monochromes

7. In channelmixerrgb we check for monochromes and set mode to pass in defaults.

8. No hotpixels for monchromes

2022-02-06 16:25 UTC, parafin commented
> 8. No hotpixels for monchromes

Out of the interest - why?

2022-02-06 17:01 UTC, jenshannoschwalm commented
No proper algorithm so far :-)


also it's much less important for monochromes, there it's  basically just noise.


No artefacts over a box of up to 5*5 as demosaicers might do for colours.


It was disabled for true monochromes before btw.


Any strong other opinion?

2022-02-06 17:33 UTC, parafin commented
Never looked at that algorithm, I’m wondering how exactly it fails with monochrome sensor? Or is it just about not being optimal?
Anyway, I think it’s OK to disable it for this edge case whatever the reason.

2022-02-06 17:43 UTC, jenshannoschwalm commented
The code does not work as it is now as  it looks at corresponding Photosites. (which itself is not bad but only so-so I think also for bayer)

That code could easily be modified... for true monochromes it would also require to change ROI as data are already downscaled.

2022-02-11 09:49 UTC, TurboGit requested changes
A minor comment, also I suppose we want to disable the "color reconstruction" module for monochrome images?

2022-02-11 11:11 UTC, jenshannoschwalm commented on src/iop/channelmixerrgb.c
> +    && (!dt_image_is_monochrome(img)); // and it is not us
that's careful reviewing :-) Absolutely right, will fix tonight.

2022-02-11 11:16 UTC, jenshannoschwalm commented
> A minor comment, also I suppose we want to disable the "color reconstruction" module for monochrome images?

Right, i never used that module so missed it. Will add that asap

2022-02-11 11:18 UTC, TurboGit commented on src/iop/channelmixerrgb.c
> +    && (!dt_image_is_monochrome(img)); // and it is not us
I must confess that if I had not found the "color reconstruction" issue I would have fixed that myself :)

2022-02-11 18:02 UTC, jenshannoschwalm commented
@TurboGit should be good now

2022-02-11 18:09 UTC, TurboGit approved these changes
Looks good to me! Thanks.

Will be my last merge for today. Today darktable got shake quite a lot, enough for a single day :)

2022-02-11 18:09 UTC, merged

2022-02-11 18:13 UTC, jenshannoschwalm commented
Pascal, congrats for pushing 3.8.1 today and all your hard work btw

2022-05-28 18:08 UTC, elstoc commented
@jenshannoschwalm: do you think this needs any documentation changes? If so please could you advise.

2022-05-28 18:36 UTC, jenshannoschwalm commented
Actually i think this does not require any special docs, this only affects debayered sensors or true monochrome camera disabling stuff in modules that simply doesn't make sense.

Maybe a short note in "importing and flagging images as monochrome" 

*************
If dt detected a true monochrome image or one from a monochrome converted camera (using the  passthrough monochrome" demosaicer some modules like demosaic, temperature or whitebalance are automatically disabled as not applicapable.
*************

2022-05-28 20:23 UTC, elstoc commented
Thanks