buttons flags cleanup
darktable-org/darktable pull request #11482
Opened 2022-04-08 21:02 UTC by AlicVB

This is a big cleanup in buttons/paint flags.
Currently we have lot of drawing flags which are used to "theme" the buttons. Now that all this is managed by css, better remove them, that will avoid a mix between hardcoded things and css ;)

I think that it doesn't change anything in the UI, but better test it twice, considering the amount of changes done in so many files !

2022-04-08 21:26 UTC, Nilvus requested changes
Many changes are needed here and I didn't review darktable.css. I let some #dt-ubtton and #dt-toggle-button on purpose. Cleanup is really good but go too far here. I'm even wondering if the rebase is done completely on master.

2022-04-08 21:26 UTC, Nilvus commented on src/develop/blend_gui.c
> +    gtk_style_context_add_class(gtk_widget_get_style_context(bd->masks_polarity), "dt_ignore_fg_state");
Use dt_gui_add_class() function here

2022-04-08 21:26 UTC, Nilvus commented on src/develop/blend_gui.c
> +      gtk_style_context_add_class(gtk_widget_get_style_context(sl->polarity), "dt_ignore_fg_state");
Use dt_gui_add_class() function here

2022-04-08 21:26 UTC, Nilvus commented on src/develop/blend_gui.c
> +    gtk_style_context_add_class(gtk_widget_get_style_context(bd->masks_shapes[0]), "dt_checked_background");
Use dt_gui_add_class() function here

2022-04-08 21:26 UTC, Nilvus commented on src/develop/blend_gui.c
> +    gtk_style_context_add_class(gtk_widget_get_style_context(bd->masks_shapes[4]), "dt_checked_background");
Use dt_gui_add_class() function here

2022-04-08 21:26 UTC, Nilvus commented on src/develop/blend_gui.c
> +    gtk_style_context_add_class(gtk_widget_get_style_context(bd->masks_shapes[1]), "dt_checked_background");
Use dt_gui_add_class() function here

2022-04-08 21:26 UTC, Nilvus commented on src/develop/blend_gui.c
> +    gtk_style_context_add_class(gtk_widget_get_style_context(bd->masks_shapes[2]), "dt_checked_background");
Use dt_gui_add_class() function here

2022-04-08 21:26 UTC, Nilvus commented on src/develop/blend_gui.c
> +    gtk_style_context_add_class(gtk_widget_get_style_context(bd->masks_shapes[3]), "dt_checked_background");
Use dt_gui_add_class() function here

2022-04-08 21:26 UTC, Nilvus commented on src/develop/blend_gui.c
> +    gtk_style_context_add_class(gtk_widget_get_style_context(bd->raster_polarity), "dt_ignore_fg_state");
Use dt_gui_add_class() function here

2022-04-08 21:26 UTC, Nilvus commented on src/dtgtk/button.c
> -  gtk_widget_set_name(GTK_WIDGET(button), "dt-button");
Do not remove it. Still needed on some places to allow different settings between dt-button and dt-toggle-button, like in blending tabs

2022-04-08 21:26 UTC, Nilvus commented on src/dtgtk/togglebutton.c
> -  gtk_widget_set_name(GTK_WIDGET(button), "dt-toggle-button");
Do not remove it. Still needed on some places to allow different settings between dt-button and dt-toggle-button, like in blending tabs

2022-04-08 21:26 UTC, Nilvus commented on src/gui/gtk.c
> +  gtk_style_context_add_class(gtk_widget_get_style_context(darktable.gui->focus_peaking_button),
Use dt_gui_add_class() here

2022-04-08 21:26 UTC, Nilvus commented on src/iop/filmic.c
> +  gtk_widget_set_name(GTK_WIDGET(g->extra_toggle), "control-button");
I remove it on purpose, not to see this add back. My CSS on last PR was fix that without need of it

2022-04-08 21:26 UTC, Nilvus commented on src/libs/modulegroups.c
> +      gtk_widget_set_name(btn, "module-enable-button");
Je l'avais enlevé celui-là

2022-04-08 21:26 UTC, Nilvus commented on src/libs/modulegroups.c
> +      gtk_widget_set_name(btn, "module-enable-button");
Je l'avais enlevé celui-là

2022-04-08 21:26 UTC, Nilvus commented on src/libs/modulegroups.c
> +            gtk_widget_set_name(btn, "module-reset-button");
Celui-là aussi

2022-04-08 21:26 UTC, Nilvus commented on src/libs/modulegroups.c
> +  gtk_style_context_add_class(gtk_widget_get_style_context(d->basic_btn), "dt_checked_background");
Use dt_gui_add_class() here

2022-04-08 21:26 UTC, Nilvus commented on src/libs/modulegroups.c
> +  gtk_style_context_add_class(gtk_widget_get_style_context(d->active_btn), "dt_checked_background");
Same here

2022-04-08 21:26 UTC, Nilvus commented on src/libs/modulegroups.c
> +    gtk_style_context_add_class(gtk_widget_get_style_context(bt), "dt_checked_background");
And here

2022-04-08 21:26 UTC, Nilvus commented on src/libs/tools/global_toolbox.c
> +  gtk_style_context_add_class(gtk_widget_get_style_context(d->grouping_button), "dt_checked_background");
Use dt_gui_add_class() here

2022-04-08 21:26 UTC, Nilvus commented on src/libs/tools/global_toolbox.c
> +  gtk_style_context_add_class(gtk_widget_get_style_context(d->help_button), "dt_checked_background");
Same here

2022-04-08 21:26 UTC, Nilvus commented on src/libs/tools/global_toolbox.c
> +  gtk_style_context_add_class(gtk_widget_get_style_context(d->keymap_button), "dt_checked_background");
And here

2022-04-08 21:26 UTC, Nilvus commented on src/views/darkroom.c
> +  gtk_style_context_add_class(gtk_widget_get_style_context(dev->second_window.button), "dt_checked_background");
Use dt_gui_add_class

2022-04-08 21:26 UTC, Nilvus commented on src/views/darkroom.c
> +  gtk_style_context_add_class(gtk_widget_get_style_context(dev->iso_12646.button), "dt_checked_background");
Same here

2022-04-08 21:26 UTC, Nilvus commented on src/views/darkroom.c
> +    gtk_style_context_add_class(gtk_widget_get_style_context(dev->rawoverexposed.button), "dt_checked_background");
And here

2022-04-08 21:26 UTC, Nilvus commented on src/views/darkroom.c
> +    gtk_style_context_add_class(gtk_widget_get_style_context(dev->overexposed.button), "dt_checked_background");
same here

2022-04-08 21:26 UTC, Nilvus commented on src/views/darkroom.c
> +    gtk_style_context_add_class(gtk_widget_get_style_context(dev->profile.softproof_button),
And here

2022-04-08 21:26 UTC, Nilvus commented on src/views/darkroom.c
> +    gtk_style_context_add_class(gtk_widget_get_style_context(dev->profile.gamut_button), "dt_checked_background");
ANd here

2022-04-08 21:26 UTC, Nilvus commented on src/views/darkroom.c
> +    gtk_style_context_add_class(gtk_widget_get_style_context(darktable.view_manager->guides_toggle),
Here too

2022-04-08 21:30 UTC, Nilvus commented
Just a quick code review. I will test more tomorrow but many more things on CSS need to be update and for some revert to what I've done. But even on dt-button, and dt-toggle-button, maybe some of your code is good.

2022-04-08 21:36 UTC, Nilvus requested changes
Some first request on darktable.css files. Probably more to come

2022-04-08 21:36 UTC, Nilvus commented on data/themes/darktable.css
> +#main-histogram .dt_module_btn
This break histogram button and especially hover effect. Just check them on histogram and see hover effect on master and on your PR.

2022-04-08 21:36 UTC, Nilvus commented on data/themes/darktable.css
> +#modules-tabs .dt_module_btn
This make hamburger menu too big on both parts. With lines just above, it's needed and wanted to keep difference between dt-toggle-button and dt-button

2022-04-08 21:36 UTC, Nilvus commented on data/themes/darktable.css
>  {
Revert back to dt-toggle-button here (see comment below)

2022-04-08 21:36 UTC, Nilvus commented on data/themes/darktable.css
> +#blending-tabs .dt_module_btn
Needed to put back dt-button here (for same reason as above

2022-04-09 09:12 UTC, Nilvus commented on data/themes/darktable.css
> +#main-histogram .dt_module_btn
Ignore that comment

2022-04-09 20:22 UTC, Nilvus approved these changes
All good now. Thanks for this great work.

2022-04-09 20:25 UTC, Nilvus requested changes

2022-04-09 20:25 UTC, Nilvus commented on src/libs/modulegroups.c
>            gtk_widget_set_name(btn, "module-reset-button");
Oh just see that one to remove too!

2022-04-09 20:38 UTC, Nilvus approved these changes

2022-04-09 20:38 UTC, Nilvus commented
Ready to be merged!

2022-04-09 21:17 UTC, elstoc approved these changes
Looks good. I don't see any obvious regressions

2022-04-10 12:05 UTC, AlicVB commented
note that at some point, we'll also have to do a big cleanup in how CPF_... flags are defined : 
- reordering them by putting state flags in first as their number are limited (eventually let 1-2 places for eventual new state flags)
- fixing all the places where flags values are called by their int values directly

but I would prefer to do that after the filter PR as land, to avoid big headaches in rebasing... btw, I'll certainly need your help @phweyland as you are doing some strange things with this in your colorfilter... I'll ping you ;)

2022-04-10 15:39 UTC, phweyland commented
> you are doing some strange things with this in your colorfilter.

Please tell me where, I'll try to understand what I've done ...

2022-04-10 15:46 UTC, AlicVB commented
this is in src/lib/tools/filters.c for example in `_update_colors_filter`...
Note that I don't say it's wrong or whatever (I'm sure of the contrary)... just that I don't understand what is done exactly and so I fear to broke something if I change the numeric value of CPF flags...

Anyway, as said, as this part is moved in another place in code with my filtering PR, I would prefer to do this work once the PR merged...

2022-04-10 18:06 UTC, Nilvus approved these changes

2022-04-10 18:31 UTC, TurboGit approved these changes
Works for me, thanks!

2022-04-10 18:31 UTC, merged