filter : enhance legacy rating widget
darktable-org/darktable pull request #11804
Opened 2022-05-14 19:56 UTC by AlicVB

this : 
- remove the "double background" effect of the comparator combobox
- let more room between the comparator combobox and the text in the case we select "5 stars"
![Capture d’écran_2022-05-14_21-52-17](https://user-images.githubusercontent.com/1818223/168446487-9a088593-84e5-4fd3-accd-c7440591c094.png)

2022-05-14 20:18 UTC, Nilvus commented
CSS is not good. There's a transparent background class to use. No need to add CSS.

I can't test actually but seeing code, adding that class (with dt_gui_add_class) to `rating_legacy->stars` should work

2022-05-14 20:19 UTC, Nilvus commented
Oups, my bad, of course better to add class to `rating_legacy->comparator`

2022-05-14 20:20 UTC, Nilvus requested changes

2022-05-14 20:20 UTC, Nilvus commented on src/libs/filters/rating_legacy.c
> +  dt_bauhaus_combobox_set_entry_label(rating_legacy->stars, 6, "             ★ ★ ★ ★ ★");
I would remove 2 spaces here. On your screenshot, seems to be a little too much space

2022-05-15 11:20 UTC, AlicVB commented
You're right of course. Both suggestions done !
Thanks

2022-05-15 17:48 UTC, TurboGit approved these changes
Thanks!

2022-05-15 17:48 UTC, merged