metadata: avoid to apply on hovered image instead of selection
darktable-org/darktable pull request #11863
Opened 2022-05-21 15:09 UTC by phweyland

attempt to fixe #11589

This should fix the above issue but I see a remaining problem: when a non validated field loses the focus the edited value is lost. It should be saved and restored when the focus is given back. This change is bit complicated as it implies to differentiate visually a field currently edited from a field already validated. Would the subject of another PR.

2022-05-21 18:19 UTC, TurboGit requested changes
This does not work on my side.
- I select an image
- I enter "azerty" on the title
- I move the mouse over some other pictures
- I press enter
- The title of the hovered image is changed

BTW, note that the same issue is found with the keywords.

2022-05-21 18:20 UTC, TurboGit commented on src/libs/metadata.c
> +    int32_t hovered = dt_control_get_mouse_over_id();
could be const

2022-05-21 19:20 UTC, phweyland commented
What a shame ! At the last minute I've found dt_control_get_mouse_over_id() faster than dt_selection_get_list() and it seems I haven't tested it properly... Sorry for inconvenience.

2022-05-21 19:23 UTC, phweyland commented
I'll have a look on tagging too.

2022-05-21 19:33 UTC, phweyland commented
Same workaround done for tagging.

2022-05-22 17:36 UTC, TurboGit approved these changes
Works for me now, thanks!

2022-05-22 17:36 UTC, merged