remove unused macros
darktable-org/darktable pull request #12249
Opened 2022-07-29 22:13 UTC by rabauke

The static analyzer of my IDE complains about unused macros. Let's get rid of some of them.

2022-08-02 16:55 UTC, TurboGit requested changes
Mostly ok, except for some, see comments.

2022-08-02 16:55 UTC, TurboGit commented on src/views/view.h
> -#define DT_VIEW_ALL                                                                              \
Sounds legitimate to keep. This could be used as mask for example.

2022-08-02 16:55 UTC, TurboGit commented on src/common/mipmap_cache.c
> -void dt_mipmap_cache_write_get_with_caller(dt_mipmap_cache_t *cache, dt_mipmap_buffer_t *buf, const uint32_t imgid, const int mip, const char *file, int line)
This is part of an API (not a macro) I think we should keep it. Could well be needed and better keep the API than letting user's redefining it somewhere else.

2022-08-02 16:55 UTC, TurboGit commented on src/common/mipmap_cache.h
> -// convenience function with fewer params
Likewise for the header part.

2022-08-05 19:21 UTC, rabauke commented
@TurboGit: Changes applied as requested.

2022-08-11 17:45 UTC, TurboGit approved these changes
Thanks!

2022-08-11 17:45 UTC, merged