[RFC WIP] Olympus embedded metadata lens correction
darktable-org/darktable pull request #12760
Opened 2022-11-04 04:23 UTC by paolodepetrillo

Attempting to add support for Olympus lens correction for #12714. The exif tags are all undocumented and nobody else has published any code for interpreting them, so nothing here should be considered authoritative - just my attempt to figure them out.

Distortion and CA is supported for Micro Four Thirds lenses. I'm pretty sure this is correct, these tags were identified by comparing the tag values to their conversion to WarpRectilinear opcodes by Adobe DNG Converter.
There are two different tags that can contain the distortion - older bodies use one (Exif.OlympusIp.0x150a), newer bodies use the other (Exif.OlympusIp.0x1510), and some bodies use both. The only difference when they are both present is that 0x1510 crops slightly more (exactly like increasing 'scale' in lensfun mode). I use 0x1510 if both are present.
In general, the crop resulting from this distortion correction usually won't match the crop of the in camera jpeg or DNG with opcodes, but this should not affect the correctness of the distortion correction.

Unfortunately some older bodies (for example E-P5) which do not support CA correction for the in camera jpegs also do not put the CA correction tags (Exif.OlympusIp.0x150c) in the raw file. Unless there is some other tag that contains them encoded differently?

Distortion correction is also supported for Four Thirds SLR lenses, on newer FT bodies and when used with an adapter on MFT bodies. This one is a different tag (Exif.OlympusIp.0x0800). Not sure if I'm interpreting it exactly right - it contains three sets of coefficients which are very close together. The first one always applies less correction, the second one always applies more, and the third one is somewhere in between. They vary with focal length and focus distance. I don't know why there are three separate sets, but I just picked the third one and it seems to work well; the difference between them is barely noticeable in the undistorted image.

Vignetting is not supported at all yet. I suspect that Exif.OlympusIp.0x0801 might contain it but have not been able to work out the relationship to the amount of correction applied by the camera to the raw file contents when 'Shading Compensation' is turned on in camera settings.

2022-11-04 17:16 UTC, sgotti commented
@paolodepetrillo Great work. I'm not yet doing a full review. Just curious:

* Am I wrong or the various grade/exponents of the polynomial for both distortion and tca are the same as the one reported by the dng spec for WarpRectilinear?
* JFYI I noticed in this [image](https://discuss.pixls.us/uploads/short-url/CFRWIcdzotCJvUpYYIsV2pMNGj.ORF) that lensfun is cropping a bit less while the embedded jpeg is cropped quite more. 

> Vignetting is not supported at all yet. I suspect that Exif.OlympusIp.0x0801

That is reported as list of Shorts. I supposed it should be Float like the other fields. BTW the unique Float fields under Exif.OlympusIp are: 0x0800, 0x150a, 0x150c, 0x1510 and 0x1513. Only 0x1513 isn't used by you.

2022-11-04 17:29 UTC, TurboGit requested changes
Probably worth adding a reference to a RAW file having those data for testers. TIA.

2022-11-04 17:29 UTC, TurboGit commented on src/iop/lens.cc
> +  int nc = _init_coeffs_md(img, p, d->scale_md, d->knots, d->cor_rgb, d->vig, &d->modify_flags_image_md);
const

2022-11-04 17:29 UTC, TurboGit commented on src/iop/lens.cc
> +  int nc = _init_coeffs_md(img, p, 1, knots, cor_rgb, NULL, NULL);
const

2022-11-04 18:38 UTC, paolodepetrillo commented
>     * Am I wrong or the various grade/exponents of the polynomial for both distortion and tca are the same as the one reported by the dng spec for WarpRectilinear?
It is the exact same formula, the Brown-Conrady model: https://www.tangramvision.com/blog/camera-modeling-exploring-distortion-and-distortion-models-part-ii
The coefficients don't match exactly between the orf and dng, because the distortion and TCA are combined into a single warp applied to each color channel, and because the crop is changed. I don't know what rule Adobe DNG Converter is using to decide how much to crop; it might be looking at some other tag in the file.
In one file I found that the radius adjustment was exactly based on the ratio of the radius of the full uncropped image (which WarpRectilinear applies to) to the image cropped by the Exif.OlympusIp.CropLeft/Top/Right/Bottom tags. But in many other files the radius was adjusted more.

> > Vignetting is not supported at all yet. I suspect that Exif.OlympusIp.0x0801
> 
> That is reported as list of Shorts. I supposed it should be Float like the other fields. BTW the unique Float fields under Exif.OlympusIp are: 0x0800, 0x150a, 0x150c, 0x1510 and 0x1513. Only 0x1513 isn't used by you.
It looks like 0x1513 doesn't have any useful info - it only appears in files from newer bodies and always has the value '1 1' in all the samples from RPU.

I am also looking at 0x1503 now. It's 12 signed integers, it shows up in all the files that have distortion correction, and it seems to vary similarly to 0x150a / 0x1510 with changes in focal length and focus distance. So maybe it also has the distortion encoded differently, or maybe it is related to vignetting?

2022-11-07 09:14 UTC, sgotti commented
> The coefficients don't match exactly between the orf and dng, because the distortion and TCA are combined into a single warp applied to each color channel

Looking at the DNG spec and at your statement I'm a bit confused. In the dng spec I see that WarpRectilinear provides both the radial and tangential coefficients so I thought the formulas will be similar with the unique difference that in the olympus metadata the radial and tangential coefficients are split in two different exif tags. Or am I missing something?

2022-11-07 14:01 UTC, paolodepetrillo commented
Tangential coefficients are not used at all in the correction; as far as I know they do not exist in the orf and are always 0 in the WarpRectilinear opcode. Both distortion and CA correction are radial only.

The orf has separate tags for distortion and CA. The distortion tag is a polynomial that defines a function dist(r) mapping from a radius in the undistorted output image to a radius in the distorted input image, and it is applied to all pixels. The CA tag contains two polynomials that define functions ca_red(r) and ca_blue(r) which are to be added to a radius in the distorted input image to correct for CA. The green channel is only undistorted, and the red and blue channels are undistorted and have CA corrected.
So to correct for both distortion and CA at the same time, a radius in the output image is mapped to a radius in the input image as:
Red pixels: r_in = dist(r_out) + ca_red(r_out)
Green pixels: r_in = dist(r_out)
Blue pixels: r_in = dist(r_out) + ca_blue(r_out)

It looks like Adobe DNG converter is solving for coefficients for a WarpRectilinear for each color that fits these curves as closely as possible (additionally with a scaling of the radius for crop) so that it can handle both distortion and CA with a single opcode.

2022-11-07 14:44 UTC, sgotti commented
@paolodepetrillo Much more clearer now! Thanks a lot for the explanation!

For future reference I'll suggest to put this as a comment in the code.

2022-11-07 19:35 UTC, sgotti commented
@paolodepetrillo JFYI and to know if your findings are the same:

* All Olympus raw I found around have ShadingCompensation exif tag to true (do you have some free otf with it disabled?)

* In such images the conversion with Adobe DNG Converter only generates 1 opcodeList3 WarpRectilnear.

* So looks like, for the DNG Converter, no vignetting correction is required... 

* Other images like Fuji ones when converted provides also a opcodeList2 GainMap. No FixVignetteRadial, so I think GainMap is used for vignetting correction

* as a consequence, if DNG Converter is right, also lensfun corrections should be manually applied by the user using "Distortion and TCA" instead of "all" (or, as an improvement, the lens module should handle the ShadingCompensation tag and automatically disable it by default).

2022-11-07 21:19 UTC, paolodepetrillo commented
That is all correct - when the Shading Compensation option is enabled for an Olympus body it applies the vignetting correction to the raw image (so it's no longer strictly 'raw'). I was hoping there would also be a tag containing the vignetting parameters so that it could be applied by the raw converter afterwards if Shading Compensation was off when the photo was taken, but I'm not sure yet if there is any tag like that.

I have not found any case where Adobe DNG Converter output any kind of vignetting correction in the dng for an Olympus raw file, regardless of any settings.

That does make sense to automatically disable vignetting for lensfun when ShadingCompensation is on, unless the camera's correction doesn't fully correct it and some additional correction from lensfun is needed? I wonder if the lensfun profiles for Olympus lenses are even all consistent - some people might have created the profiles with the option on and others with the option off?

I do have a series of raws taken with ShadingCompensation on and off that I have been using to try to figure out what correction curve the camera was applying to them, can post them later today.

2022-11-09 14:27 UTC, paolodepetrillo commented
Making some more progress figuring out these tags. 0x1500 / 0x1501 / 0x1503 looks like it is distortion (varies with focal length and focus distance but not aperture). I'm guessing that 0x1503 and 0x150a / 0x1510 have the same correction, just encoded differently. Maybe 0x1503 is in a form that can be applied efficiently by the camera's CPU and 0x150a / 0x1510 is intended for use by a PC raw processor. So I think we can ignore 0x1503.

0x0801 appears to be the vignetting correction. It looks like a spline, always starts around 8192 and increases monotonically.
I have a Panasonic lens which doesn't get any vignetting correction by the camera body and has an almost null 0x0801 tag - it is always 8192, 8193, 8194, .... , 8207, 8208.

I am still not sure exactly how to apply the correction from this tag though, don't know what to use as a reference to compare to. The ShadingCompensation applied to the raw by the camera body seems to under-correct. Maybe it doesn't apply any correction at all if the max vignetting is below some threshold, and maybe there is a limit to the maximum amount of correction it will apply. The lensfun model for the lens I have been testing always applies more correction. If I just divide the value from the 0x0801 vignetting spline by 8192 and multiply the pixels by that, it looks roughly ok although might over correct in the far corners. Maybe when looking up the correction amount in the 0x0801 spline for a given radius, that radius should be scaled down so that the value for the far corner of the image is taken from somewhere in between the second-to-last and last elements, rather than the last element which can be much larger in the case of strong vignetting.

I don't know what to do with this - I can guess at how it should work but have no way to know if I'm interpreting it as the lens manufacturer intended.

@FreddieWitherden How did you figure out the formulas for the Sony and Fuji splines?

2022-11-09 19:18 UTC, FreddieWitherden commented
Vignetting is one of the easier ones to handle.  My process was to find a lens I owned for which there were good reviews online which analysed the vignetting and did so with camera corrections off.  Then, I attempted to correlate these numbers (usually darkening %) with those of the review.

It could well be that the final knot of the spline is outside the usual dimensions of the sensor.  Indeed, this makes sense as some m43 cameras are known for having 'oversized' sensors; see https://www.dpreview.com/reviews/panasonic-lumix-dc-gh5s-review for example.

2022-11-11 12:33 UTC, sgotti commented
> I am still not sure exactly how to apply the correction from this tag though, don't know what to use as a reference to compare to.

Does the adobe DNG convert generate some opcodes GainMap or FixVignetteRadial for a file with ShadingCorrection off?

I don't have any file with ShadingCorrection disabled and all the one with it enabled only have a WarpRectilinear opcode.

2022-11-12 14:54 UTC, sgotti commented
> I don't know what to do with this - I can guess at how it should work but have no way to know if I'm interpreting it as the lens manufacturer intended.

@paolodepetrillo I think that, like done for the Fuji and Sony corrections, we should use the ooc image as the reference leaving lensfun out from the comparison.

In the original PR @uchrisu made some good charts to compare ooc jpeg from correction functions: https://github.com/darktable-org/darktable/pull/7092#issuecomment-1076847621

Not sure how he did them, but something like a Jupiter notebook could be created to visually see changes in distortion, tca and vignetting, try to "manually" understand/tune the correction factors and it could be reused also for future cameras manufacturers.

2022-11-12 22:44 UTC, paolodepetrillo commented
I have started working on some scripts to test these things, was using @uchrisu method of plotting a line from the center to the corner to try to check distortion. It's pretty close but I'm still having some trouble exactly matching the OOC distortion.

Vignetting is tricky because there isn't a way to get the exact same shot processed through the camera with shading compensation on and off. I have been taking two shots of the exact same white wall with same camera settings, one with the option on and one with the option off, taking the ratio of those images after blurring, fitting a curve to it, and trying to relate that curve to the values of the 0x0801 tag. Haven't figured it out yet.

Maybe I will try next modifying the values of the 0x0801 tag in an orf file and seeing if that affects how it gets processed through OM Workspace or Olympus Viewer with vignetting correction on. That would show if the manufacturer's app is actually using the tag, or ignoring it and using some kind of built in profile.

2022-11-15 03:57 UTC, paolodepetrillo commented
Finally figured out exactly how Adobe DNG Converter is interpreting the `OlympusIp.0x150a` tag and converting it to a WarpRectilinear DNG opcode. This holds true for every orf file I could find on RPU with a 0x150a tag.

The orf file defines a crop region with the Exif.Olympus.CropLeft, CropTop, CropWidth, and CropHeight tags. The center of the image is at (CropWidth/2+CropLeft, CropHeight/2+CropTop). The DNG opcode processing is applied to the entire raw image, not only the crop region. For WarpRectilinear, the maximum radius (r = 1) is defined as the distance from the center of the image to the furthest corner. Let $R_{scale}$ equal the ratio of the distance from the center to the corner of the crop region, to the distance from the center to the furthest corner of the image.

For example my E-P5 produces a 4640x3472 raw image with a crop region starting at 8,8 of size 4608x3456. The center is at 2312,1736. The distance from the center to the corner of the crop region is 2880, and the distance from the center to the furthest corner of the image is 2904.011, so $R_{scale} = 0.99173178$.

Let $e_2$, $e_4$, $e_6$, $e_0$ be the four coefficients in the `OlympusIp.0x150a` tag. For the WarpRectilinear distortion formula:
$$r_{input} = r (k_0 + k_2 r^2 + k_4 r^4 + k_6 r^6)$$

Adobe DNG Converter calculates the coefficients $k_0$, $k_2$, $k_4$, $k_6$ as:

$k_0 = e_0$

$k_2 = e_2 \cdot e_0 \cdot (\dfrac{e_0}{R_{scale}})^2 $

$k_4 = e_4 \cdot e_0 \cdot (\dfrac{e_0}{R_{scale}})^4 $

$k_6 = e_6 \cdot e_0 \cdot (\dfrac{e_0}{R_{scale}})^6 $

2022-11-15 23:23 UTC, paolodepetrillo commented
Trying to figure out the meaning of the change of distortion coefficients from the exif to the DNG - I think this is what's happening:

Let $e_2$, $e_4$, $e_6$, $e_0$ be the four coefficients in the `OlympusIp.0x150a` tag. This defines a distortion function:
$$r_{input} = r_{out} \cdot (1 + e_2 r_{out}^2 + e_4 r_{out}^4 + e_6 r_{out}^6)$$

The camera applies this to each pixel within the crop region, defining the corner of the crop region in the output image as $r_{out}=e_0$ and defining the corner of the crop region in the input image as $r_{input}=1$.

WarpRectilinear defines the radius of the corner of both the input and output image as $r_{input}=1$ and $r_{out}=1$, requiring an adjustment to the formula:

$$ r_{input} = (e_0 r_{out}) \cdot (1 + e_2 (e_0 r_{out})^2 + e_4 (e_0 r_{out})^4 + e_6 (e_0 r_{out})^6)$$

Both $r_{input}$ and $r_{output}$ need to be adjusted to account for WarpRectilinear applying to the entire image, not just the crop region:

$$ \dfrac{r_{input}}{R_{scale}} = (\dfrac{e_0 r_{out}}{R_{scale}}) \cdot (1 + e_2 (\dfrac{e_0 r_{out}}{R_{scale}})^2 + e_4 (\dfrac{e_0 r_{out}}{R_{scale}})^4 + e_6 (\dfrac{e_0 r_{out}}{R_{scale}})^6)$$

Which can be rearranged like the WarpRectilinear formula showing how $k_0$, $k_2$, $k_4$, and $k_6$ are calculated:

$$ R_{input} = R_{out} \cdot (e_0 + e_2 e_0 (\dfrac{e_0}{R_{scale}})^2 r^2 + e_4 e_0 (\dfrac{e_0}{R_{scale}})^4 r^4 + e_6 e_0 (\dfrac{e_0}{R_{scale}})^6 r^6)$$

2023-02-10 14:12 UTC, jenshannoschwalm commented
@paolodepetrillo maybe you could rebase on current master as we might continue your work?

2023-04-14 15:40 UTC, geni1105 commented
Would be really great if this pull request would proceed. Unfortunately my own darktable code insights are quite shallow, and I would not be able to rebase / merge ... I could contribute to testing, if that's required.

2023-04-14 17:08 UTC, jenshannoschwalm commented
> Would be really great if this pull request would proceed. Unfortunately my own darktable code insights are quite shallow, and I would not be able to rebase / merge ... I could contribute to testing, if that's required.

The rebasing would not be the problem; it's about being sure the way data are used is "correct" :-) @paolodepetrillo is the person investigating (in fact that's tedious work he has done ... )

2023-05-28 15:39 UTC, pitbuster commented
@paolodepetrillo do you need any help to move this PR forward (testing, coding, RAW samples)?

2023-05-31 04:44 UTC, paolodepetrillo commented
Sorry it's taking so long, I will try to get it rebased on master soon. I just got an EM-1 II which I can experiment with.. was surprised to see that it outputs 0x150c and 0x1510 tags for distortion/CA when using an old Four Thirds SLR lens - I had assumed those tags were for Micro Four Thirds lenses only.

As a short term workaround until this is done - Adobe DNG Converter understands the Olympus tags, and the Darktable lens module now supports the DNG tags. So the ORF files can be run through the converter and the resulting DNGs can be edited in Darktable with the corrections applied. I just tried it and it seems to line up pretty well with the camera jpeg, after correcting for slightly different crop and image center.

2023-06-06 02:55 UTC, paolodepetrillo commented
I've rebased to the latest master and am making some more progress figuring out what the tags mean. In its current state this is working and is approximately at parity with the way Adobe DNG Converter handles the tags, although there might be some very slight differences related to scaling / cropping. It applies distortion correction from the 0x150a tag, CA correction from the 0x150c tag, and no vignetting correction.

Based on the way OM Workspace handles the files with both 0x150a and 0x1510 distortion tags, I suspect that 0x150a is a mandatory distortion correction for micro four thirds lenses where an end user should never see the image without that correction applied under any circumstances, and 0x1510 is an optional stronger correction. The camera JPEG exactly matches the OM Workspace output with the distortion correction option off, which also matches (after scaling) the DNG from Adobe DNG Converter through darktable lens module, and the ORF through darktable lens module with this patch using the 0x150a tag. For one image I tested with strong barrel distortion, this resulted in a mostly corrected image with some slight barrel distortion remaining. Switching on the distortion correction set to Auto in OM Workspace resulted in a slightly over corrected image (some pincushion), which corresponded to the ORF through darktable lens module using the 0x1510 tag instead.

The simplest thing to do is to follow the example of Adobe DNG Converter, use 0x150a, and ignore 0x1510. But maybe it could be offered as an option, or used to implement an adjustment? Like increasing the strength of the correction could interpolate from 0x150a to 0x1510?

For one Four Thirds adapted SLR lens I tested, there was a valid correction that worked well to correct the barrel distortion, which was in the 0x0800 tag (Four Thirds only) and also in 0x1510, but 0x150a was null. So for lenses like that, they wouldn't get corrected if we use 0x150a only.

2023-06-06 21:17 UTC, jenshannoschwalm commented
tested this on a number of images (Pen-F and E-M10) with various lenses. VERY good results here, for the zuiko 17mm/F1.8 it looks better then what lensfun does :-)

I also would opt for supporting MFT only...

2023-06-07 03:02 UTC, paolodepetrillo commented
Just pushed a small correction to the distortion formula, which affects images with strong distortion and 0x150a[3] coefficient significantly < or > 1, like these:
[Olympus - E-PL3 - 16bit (4:3).ORF](https://raw.pixls.us/getfile.php/1330/nice/Olympus%20-%20E-PL3%20-%2016bit%20(4:3).ORF)
[Olympus - E-P7 - 16bit (4:3).ORF](https://raw.pixls.us/getfile.php/5980/nice/Olympus%20-%20E-P7%20-%2016bit%20(4:3).ORF)

The corrected images line up well with the export from OM Workspace when the distortion correction in OM Workspace is switched off - more examples that suggest 0x150a is the mandatory MFT correction that can never be switched off in camera or in apps that officially support ORF files.

2023-06-08 10:08 UTC, Donatzsky commented
I have a ZX-10 (compact zoom), if you want some RAWs to test with.

2023-06-11 12:58 UTC, geni1105 commented
Tested with the E-M1 Mark III and the 12-45 / f4 Pro. 
Distortion correction works great, but with corrections set to "all", a pronounced TCA is added at the wide-angle settings (12...13 mm), which goes away with "distortion only" or "distortion & vignetting".

2023-06-11 13:42 UTC, paolodepetrillo commented
@Donatzsky I checked the XZ-10 sample on RPU [Olympus - XZ-10 - 12bit (4:3).ORF](https://raw.pixls.us/getfile.php/2431/nice/Olympus%20-%20XZ-10%20-%2012bit%20(4:3).ORF) and it seems to work exactly the same as a MFT camera.

@geni1105 I wasn't sure if the TCA was working exactly right.. please provide a sample (orf and camera jpg) and I will take a look.

2023-06-11 17:13 UTC, geni1105 commented
Attached - thanks for your effort :-) 
[M3001586.zip](https://github.com/darktable-org/darktable/files/11715279/M3001586.zip)

2023-06-13 05:13 UTC, paolodepetrillo commented
The CA implementation was totally wrong - from comparing to what Adobe DNG Converter does with the tag, it's supposed to be applied after distortion correction to the undistorted radius. This is how it should be done:

Let $e_2$, $e_4$, $e_6$, $e_0$ be the four distortion coefficients in the `OlympusIp.0x150a` tag. This maps a radius in the distorted input image to a radius in the undistorted output image, with the corner of the input and output defined as radius 1:
$$r_{in} = e_{0} r_{out} \cdot (1 + e_{2} (e_{0} r_{out})^2 + e_{4} (e_{0} r_{out})^4 + e_{6} (e_{0} r_{out})^6 )$$

If there is CA correction in the `OlympusIp.0x150c` tag, then correction is added to the red and blue channels separately. There is no change to the green channel. Let $c_0$, $c_2$, $c_4$ be the red or blue CA coefficients from the tag.
$$r_{inCA} = r_{in} \cdot ((1 + c_0) + c_2 r_{in}^2 + c_4 r_{in}^4)$$

The 6 values in the `0x150c` tag are [red $c_0$, red $c_2$, red $c_4$, blue $c_0$, blue $c_2$, blue $c_4$].

I will push a fix for this soon.

2023-06-13 14:04 UTC, paolodepetrillo commented
CA is fixed, should give the exact same results as a DNG from Adobe DNG Converter now.

2023-06-20 19:51 UTC, geni1105 commented
Thanks, now it works!

2023-08-29 00:16 UTC, pitbuster commented
I finally got to test it and it seems to be working nicely and hopefully we get also vignetting correction, but awesome work so far.

Regarding @TurboGit comment on adding a reference file, at least https://raw.pixls.us/getfile.php/1051/nice/Olympus%20-%20E-M1%20-%2016bit%20(4:3).orf and https://raw.pixls.us/getfile.php/1787/nice/Olympus%20-%20E-M10%20Mark%20III%20-%2016bit%20(4:3).ORF have them (and probably most if not all Olympus RAWs in the https://raw.pixls.us repository, but I tested those two).

2023-10-17 15:53 UTC, dtrtuser commented
I was able to manually merge the code to master (as of 10/16/2023) and it works beautifully. Can't wait to have this PR officially committed to master.

2023-10-17 15:57 UTC, jenshannoschwalm commented
It's been only @paolodepetrillo working and testing on this, so howto proceed? Maybe add this in a way to have embedded for olympus not being default?

2023-10-18 20:31 UTC, paolodepetrillo commented
I am pretty sure that in its current state this matches the behavior of OM Workspace or Adobe DNG Converter - always applying TCA correction when present, and applying the 'mandatory' distortion correction for MFT lenses. So it would be worthwhile to go ahead and merge now to have that available in the next release.

The only thing I'm unsure about is what to do in the future, if we figure out how the other distortion tags work (0x1510 and 0x0800 for the older Four Thirds SLR lenses). Maybe we add a new option at that point to switch between 'apply mandatory distortion correction only' and 'apply all / additional distortion correction'?

2023-10-19 03:46 UTC, ig9000 commented
Thanks for working on this. I was wondering, have you included in your tests any images in which the image circle has become uncentered in the frame due to strong actions of the sensor-shift stabilization? I haven't tried yet to determine if in-camera correction takes this into account or not, but maybe it would be worth some testing to check? I've noticed the center-shifting can be substantial sometimes.

2023-10-19 14:27 UTC, paolodepetrillo commented
@ig9000 I haven't experimented with that but haven't noticed anything that would indicate it's happening. When the Adobe DNG Converter converts the 0x150a / 0x150c tags into a WarpRectilinear opcode, that opcode has a parameter for the center for correction that allows it to be placed anywhere. But it always sets it to the exact image center (0.5, 0.5).

The E-M1 II has an option 'Sequential Image Stabilization' - from the user manual:

> Sets the priority function during sequential shooting.
> [Fps Priority]: Shooting speed gets priority over image stabilization. The sensor will not be reset to the center
> during sequential shooting.
> [IS Priority]: Image stabilization gets priority over shooting speed. The sensor will be reset to the center per frame of sequential shooting. The shooting speed will drop slightly.

So if one were trying to intentionally create an image with a lot of sensor shift to test its effect on distortion correction, probably should set this option to Fps Priority, use sequential shooting, and pan the camera around while shooting. I haven't tried this myself though.

2023-10-20 06:01 UTC, ig9000 commented
> When the Adobe DNG Converter converts the 0x150a / 0x150c tags into a WarpRectilinear opcode, that opcode has a parameter for the center for correction that allows it to be placed anywhere. But it always sets it to the exact image center (0.5, 0.5).

That's interesting, so the capability of an offset is there. I suppose there might be some value to letting a user adjust that manually (in the darktable spirit of giving control over as much as possible)? Speaking of shooting a sequential burst while panning, that might be a good way to create a detectable graduation of values in any "unknown" tags where sensor offset information may (or may not) exist. If I have time soon maybe I'll try it.

2023-10-21 07:10 UTC, jenshannoschwalm commented
> That's interesting, so the capability of an offset is there

Yes but i think you might have misunderstood the meaning. From my understanding of the dng specs this is not for such displacements but for lens versus sensor "aligning".

2023-10-22 06:49 UTC, ig9000 commented
>  but for lens versus sensor "aligning".

Sorry if I'm misunderstanding, but wouldn't the effect of sensor shift be a case for lens versus sensor aligning?

2023-10-24 19:00 UTC, jenshannoschwalm commented
Yes but that's not what these parameters are for. That would only be the case if a multi-image raw has coeffs for every part. That's not in dng  specs afaik

2023-11-14 00:13 UTC, paolodepetrillo commented
I just rebased on the latest master. Is there any possibility of getting this merged for 4.6 or is it too close to feature freeze?

2023-11-14 20:04 UTC, dtrtuser commented
> I just rebased on the latest master. Is there any possibility of getting this merged for 4.6 or is it too close to feature freeze?

Just tested this latest version with multiple Olympus cameras  and lenses combinations and it works great, thank you!

2023-11-14 20:19 UTC, jenshannoschwalm commented
I only had 2 different mFT olys and a couple of lenses. All good for me.

2023-11-14 20:45 UTC, TurboGit requested changes
The changes are well localized, so ok for merging. Please just 2 consts to be added. TIA.

2023-11-14 20:45 UTC, TurboGit commented on src/common/exif.cc
> +        float kd = pos->toFloat(i);
const

2023-11-14 20:45 UTC, TurboGit commented on src/common/exif.cc
> +        float kc = pos->toFloat(i);
const

2023-11-14 21:18 UTC, TurboGit approved these changes
Thanks!

@paolodepetrillo : We need a release note entry for this. Can you propose a little description? TIA.

2023-11-14 21:18 UTC, merged

2023-11-15 01:52 UTC, paolodepetrillo commented
Some notes, maybe more detail than needed for the release notes:


Lens correction using embedded metadata now supports distortion and chromatic aberration correction for images from Olympus Micro Four Thirds cameras.

Vignetting correction from embedded metadata is not supported. If the camera's Shading Compensation option is enabled then vignetting correction will already be applied to the data in the raw file.

The correction is equivalent to that applied by the camera body to in-camera JPEGs. For older bodies which do not support chromatic aberrattion correction for JPEGs, it is also not supported in the embedded metadata.

For any given lens and image, either the embedded metadata or a Lensfun model may result in better correction, so it may be worthwhile to try both options if available. Unlike the Lensfun models, the embedded metadata correction can take into account the focus distance in addition to the focal length.

2023-11-16 06:26 UTC, jenshannoschwalm commented
Jus one remark, after this being merged i did test on a big number of my oly images and in almost all cases the new algo is far better than what we had with lensfun. The most noteworthy lens is the Olympus 17mm prime. It was highly recommended in tests so i got it some years ago and was disappointed by it's ca errors. All gone now! The bad thing: i had to define a style for that lens, reset to new lens default and disable raw ca correction module :-)

2023-11-16 09:21 UTC, TurboGit commented
@jenshannoschwalm : Good to hear!

2023-11-18 21:53 UTC, AxelG-DE commented
I didn't do a super intensive test yet, but I do have the 15mm Summilux 1.7 and also a lot of CA disappears.

I am just missing the vignette correction, as I often shoot wide open :)

2023-11-18 22:06 UTC, AxelG-DE commented
For the 15mm Summilux, not all CA's disappear, they just flip :-)
https://github.com/darktable-org/darktable/assets/49004103/54e148dd-f9cd-43e8-bfef-c5a9f21353d8