Fix hdr merging
darktable-org/darktable pull request #13217
Opened 2022-12-28 13:28 UTC by jenshannoschwalm

1. The first commit is a bugfix - there might be more in `dt_imageio_export_with_flags()` - also for 4.2.1
2. The second is just maintenance while checking dng header writing so for 4.4

Fixing #12162

2022-12-28 13:47 UTC, kmilos commented
I'd probably separate these two. The DNG header writing could (should?) be further improved to not use those magic numbers at all...

2022-12-28 15:27 UTC, jenshannoschwalm commented
Don't use magics any more ...

2022-12-29 09:13 UTC, TurboGit commented
@jenshannoschwalm : Issue ref https://github.com/darktable-org/darktable/pull/12162 is Spanish translation update.

2022-12-29 09:18 UTC, TurboGit requested changes
First commit merged in master & 4.2 branch.

Can you rebase and squash the other two commits for 4.4? TIA.

BTW, it is better to have separate PR when parts are for different versions.

2022-12-29 09:52 UTC, jenshannoschwalm commented
Closing this for #13223

2022-12-29 09:52 UTC, closed without merging