Bugfix: Opposed chroma correction OpenCL update
darktable-org/darktable pull request #13385
Opened 2023-01-19 18:55 UTC by jenshannoschwalm

As reported the current OpenCL code for chroma correction is **very** slow at least on AMD cards, in fact it only works fine on nvidia cards as they support an atomic float add (the other cards use a simulated instruction involving a poll).

The new code doen't use any atomic instructions at all, as the algorithm doesn't allow a simple reduction based on 2d data a bunch of new functions for 1d kernels was introduced.

On my machine the new code has no penalty (in fact seems to be a bit faster) and should also work fine on non-nvidia devices.  

Fixes #13362
Replaces #13372

2023-01-19 20:10 UTC, MStraeten commented
looks fine on mac with amd gpu

2023-01-19 20:20 UTC, piratenpanda commented
here as well on my RX580 on arch

2023-01-19 20:45 UTC, TurboGit commented on src/common/opencl.c
> +  buf[0] = '\0';
Is equivalent to:

`char buf[256] = { 0 };`

2023-01-19 20:46 UTC, TurboGit requested changes
Apart the minor style comment, looks good to me.

2023-01-19 21:10 UTC, dterrahe commented
I have to say, I don't understand the technical issue here on the driver side _at all_, so I have no idea if this is going to be used much/the majority of cases?

But assuming not, do we really need duplicates for `dt_opencl_enqueue_kernel_1d_with_local`, `dt_opencl_enqueue_kernel_1d` _and_ `dt_opencl_enqueue_kernel_1d_args_internal`?

My approach when I refactored this was to _only_ in the bog standard case use `dt_opencl_enqueue_kernel_2d_args` and otherwise just call `dt_opencl_set_kernel_args` and set up `sizes` first (in `_process_opposed`) and then directly call `dt_opencl_enqueue_kernel_2d_with_local` (you can find many examples in the codebase).

The latter you'll have to create a duplicate `dt_opencl_enqueue_kernel_1d_with_local` for, but they could both simply call a refactored `dt_opencl_enqueue_kernel_nd_with_local` which would have an additional parameter 1 or 2. Rather then lazily (sorry) copying _all_ the code. I may have missed some subtle differences. But that is really the point; two almost identical functions hide what are the essential differences. And that means in future people will always resort to just adding one more special case function because they can't really understand anymore what is reusable.

2023-01-19 21:19 UTC, da-phil commented
Also works fine on my Radeon RX 5700 XT :+1:

2023-01-20 06:36 UTC, jenshannoschwalm commented
> But assuming not, do we really need duplicates for ...

I fully accept your critics ! (should have done better ...)

2023-01-20 11:10 UTC, dterrahe commented
It must have been a really nasty problem to track down, so I can understand the joy of finally finding _something_ that fixes it. You can count on me to spoil part of that joy!

2023-01-20 16:11 UTC, jenshannoschwalm commented
@dterrahe should be good now (except the va issue discussed elsewhere ...)
No maths changed, housekeeping in the commits ...

2023-01-20 16:36 UTC, dterrahe commented
All looking good! Thank you!

TBH I'm not sure why originally `sizes` was always loaded with n+1 values with the last one always set to 1. https://registry.khronos.org/OpenCL/sdk/1.0/docs/man/xhtml/clEnqueueNDRangeKernel.html says they only expect 1 or 2 values in the array. So this may be cargo cult _or_ it could be hard earned wisdom, so not really worth messing with imho.

2023-01-20 16:44 UTC, jenshannoschwalm commented
> TBH I'm not sure why originally `sizes` was always loaded with n+1 values with the last one always set to 1. https://registry.khronos.org/OpenCL/sdk/1.0/docs/man/xhtml/clEnqueueNDRangeKernel.html says they only expect 1 or 2 values in the array. So this may be cargo cult _or_ it could be hard earned wisdom, so not really worth messing with imho.

Don't know either, we can have up to three sizes for 3 dimensions. From my knowing the dt code we always do 2d kernels except the latest one introduced here. Maybe there were early issues long gone ...

2023-01-20 17:00 UTC, dterrahe commented
It may be that some flaky drivers always read 3 values, even when work_dim is set to 1 or 2. So if you want to be extra careful (and perpetuate the myth) you _could_ set
`size_t sizes[] = { iheight, 1, 1};`
like is done elsewhere (when dim = 2) but it _shouldn't_ lead to fewer crashes....

2023-01-20 17:25 UTC, jenshannoschwalm commented
> So if you want to be extra careful (and perpetuate the myth) you _could_ set

:-) Let's wait for report about out-of-resources error or "perpetuate"?

2023-01-20 18:00 UTC, jenshannoschwalm commented
Maybe we should always define with a specified array size like `size_t sizes[3] = { a, b, c};`?

2023-01-20 18:33 UTC, dterrahe commented
This is done in many places, but the [3] is inferred by the compiler anyway. I am not here to say that 3 elements _should_ always be enforced (rather the opposite) but only that they _have_ been and I've been too often guilty of breaking stuff because I assumed (or found "evidence") that parts could be removed because they looked to be the result of aggressive copy/pasting.

If you were to "fix" this across the whole codebase, then you maybe should have some indication that it _actually_ adds benefit, because you'll be setting a practice in stone. Otherwise, it seems that it is "working" so why not leave it alone :-)

2023-01-20 18:43 UTC, jenshannoschwalm commented
> then you maybe should have some indication that it _actually_ adds benefit,

Don't have that right now.

2023-01-20 21:40 UTC, jenshannoschwalm commented
Ready to go

2023-01-21 08:15 UTC, TurboGit approved these changes
Thanks!

2023-01-21 08:15 UTC, merged