allow resizing of widgets by dragging bottom
darktable-org/darktable pull request #13418
Opened 2023-01-23 17:27 UTC by dterrahe

This allows resizing of graph widgets using the mouse, similar to dragging the side panels or the filmstrip.
The previous method using ctrl+scroll is still supported and is consistently shown in the tooltip. 

Navigation and Histogram have also been converted to `dtgtk_drawing_area_new_with_aspect_ratio` so they both maintain their shape when the whole sidepanel width is changed (and navigation is now resizeable). The previously set size for histogram is ignored so users will once have to set that up again. New users can have a more reasonable default on hidpi.

![image](https://user-images.githubusercontent.com/1549490/214095761-fdf2e39d-0bc6-46db-8341-3b8cb98842e3.png)
![image](https://user-images.githubusercontent.com/1549490/214095939-943aa7fa-efbf-4564-835e-880963f0912e.png)

Some of the lists work as well (image information, duplicate manager) but others either sporadically (history) or always (tagging, styles) don't respond to a mouse drag. I haven't figured out why yet. Continue to use ctrl+scroll here.

Intends to address some of the issues in #13383

2023-01-24 18:36 UTC, TurboGit commented
Really nice ! A little issue I found:
- Enter darkroom
- Zoom in the image
- Change the size of the preview
- See the actual area is changed to match the mouse pos (bottom of the preview window).

2023-01-24 18:36 UTC, TurboGit requested changes
Issue with preview.

2023-01-25 15:19 UTC, dterrahe commented
Fixed.

The only thing I'm still struggling with is why for some treeviews it works and others it doesn't. For example, in the tagging module, the bottom one is fine, but the top one doesn't receive the button click (and thus doesn't start a resize). The only thing I can find so far is that the bottom one seems the have a css margin-bottom of 3.5px whereas the top one has 0. But I don't know where that comes from and if that really makes a difference (and why).

2023-01-25 15:34 UTC, dterrahe commented
OK, got it. It's the `dt_gui_add_class(GTK_WIDGET(box), "dt_spacing_sw");` applied to the _parent_ of the scrolled window. Which makes it harder to integrate into `dt_ui_resize_wrap` because at that point to scrolled window hasn't been added to a box yet.

@Nilvus I haven't looked into _why_ this makes a difference or if it would be ok to apply this to the styles and top tagging lists too.

2023-01-25 16:42 UTC, dterrahe commented
There's nothing that can't be fixed with just one more GtkEventBox.

@TurboGit I believe this now works for all previously ctrl+scroll resizable widgets.

2023-01-25 19:02 UTC, dterrahe commented
Got rid of some warnings (and fixed workaround in metadata).

2023-01-25 20:34 UTC, TurboGit approved these changes
Works for me, thanks for this nice clean-up (many lines removed) and this new feature far more discoverable for new users.

2023-01-25 20:34 UTC, merged

2023-03-01 13:29 UTC, dterrahe commented
Release note here https://github.com/darktable-org/darktable/pull/13523#issuecomment-1450156383