[fix #13231] sigmoid : add OpenCL support
darktable-org/darktable pull request #13615
Opened 2023-02-11 19:31 UTC by erzsig

[fix #13231] sigmoid : add OpenCL support
I have adapted the code from sigmoid.c process function to opencl. As far as I can see the modul now has the same effect on the image either opencl is switched on or off.

2023-02-12 21:14 UTC, TurboGit requested changes
Some style comments, not tested yet.

2023-02-12 21:14 UTC, TurboGit commented on data/kernels/sigmoid.cl
> +static inline float generalized_loglogistic_sigmoid_scalar(const float value, const float magnitude, const float paper_exp,
some style changes to follow dt convention.

- static routines must start with underscore
- the parameters one per line when there is too many to fit on a line

So it should be:

```
static inline float _generalized_loglogistic_sigmoid_scalar(const float value, 
                                                            const float magnitude, 
                                                            const float paper_exp,
                                                            const float film_fog, 
                                                            const float film_power, 
                                                            const float paper_power)
{
```

Many other occurrences in following code.

2023-02-12 21:14 UTC, TurboGit commented on data/kernels/sigmoid.cl
> +  const float full_hue_correction = per_channel[order.min] + ((per_channel[order.max] - per_channel[order.min]) * (pix_io[order.mid] - pix_io[order.min]) / (pix_io[order.max] - pix_io[order.min]));
line too long, please split for readability

2023-02-13 07:15 UTC, TurboGit commented
Just tested this implementation and to me it works fine. The integration test 0097 pass fine.

2023-02-13 14:57 UTC, erzsig commented
Hi @TurboGit , thanks for your comments and the test.
I have corrected the style, and checked that the code remained functional.
Please, review it again.

2023-02-13 16:50 UTC, TurboGit approved these changes
Thanks!

2023-02-13 16:50 UTC, merged

2023-02-15 20:26 UTC, MStraeten commented
kernel doesn't compile with macos arm64:
```
[opencl_synchronization_timeout] synchronization timeout set to 200
     1,1256 [opencl_create_kernel] could not create kernel `sigmoid_loglogistic_per_channel'! (CL_INVALID_PROGRAM)
     1,1256 [opencl_create_kernel] could not create kernel `sigmoid_loglogistic_per_channel_interpolated'! (CL_INVALID_PROGRAM)
     1,1257 [opencl_create_kernel] could not create kernel `sigmoid_loglogistic_rgb_ratio'! (CL_INVALID_PROGRAM)
```
all other kernels compiles fine

2023-02-15 21:41 UTC, MStraeten commented
one macos update later it's fine again ;)