OpenCL supports --dump-pipe
darktable-org/darktable pull request #13757
Opened 2023-02-26 16:49 UTC by jenshannoschwalm

As said, while processing the pipe also the cl_mem buffers of opencl devices for input & output of the specified modules are dumped.

Requisite for work on color-correct scaling

2023-02-26 21:05 UTC, TurboGit requested changes
Looks good, a minor comment for a missing const.

2023-02-26 21:05 UTC, TurboGit commented on src/common/opencl.c
> +  int err = dt_opencl_read_host_from_device(devid, in, img, width, height, element_size);
const

2023-02-27 06:35 UTC, jenshannoschwalm commented on src/common/opencl.c
> +  int err = dt_opencl_read_host_from_device(devid, in, img, width, height, element_size);
done plus some more of them

2023-02-27 18:21 UTC, jenshannoschwalm commented
Some more work on this pending ...

2023-02-28 06:33 UTC, jenshannoschwalm commented
Sorry about re-reviewing, the latest commits
1. make sure for not-crashing if writing non-float data (happens in rawprepare as input)
2. write int16 data in those cases

Ready to go from my side. Hope this will help us to track down scaling related stuff.

2023-02-28 08:21 UTC, TurboGit approved these changes
Looks good to me, thanks!

2023-02-28 08:21 UTC, merged