More pixelpipe stuff
darktable-org/darktable pull request #14160
Opened 2023-04-09 17:55 UTC by jenshannoschwalm

- Fixes some ints that should be gbooleans
- `dt_imgid_t` and macro usage related to `dt_act_on_get_main_image()`_

2023-04-09 18:18 UTC, TurboGit requested changes
Some minor indentation missing. TIA.

2023-04-09 18:18 UTC, TurboGit commented on src/common/iop_profile.c
>                                             const int devid,
indent please.

2023-04-09 18:18 UTC, TurboGit commented on src/common/iop_profile.c
>                                                 cl_mem dev_img_in,
likewise

2023-04-09 18:18 UTC, TurboGit commented on src/common/iop_profile.h
>                                             cl_mem dev_img_out, const int width, const int height,
indent

2023-04-09 18:18 UTC, TurboGit commented on src/common/iop_profile.h
>                                                 const int width, const int height,
indent

2023-04-09 18:18 UTC, TurboGit commented on src/common/iop_order.c
>                               const dt_imgid_t imgid,
indent

2023-04-10 05:56 UTC, jenshannoschwalm commented
@TurboGit while "indenting" i spotted at least a possible problem.

Could you check `gboolean dt_ioppr_generate_profile_info()`, it should now correctly return the error flag.

2023-04-10 06:51 UTC, TurboGit approved these changes
Loos good, and indeed dt_ioppr_generate_profile_info() seems better now and return an error code instead of always 0.

2023-04-10 06:51 UTC, merged