style: fix export/import overwrite message.
darktable-org/darktable pull request #14281
Opened 2023-04-21 12:15 UTC by sgotti

Fix the export/import overwrite messages by printing the already
existing destination file name when exporting and the destination
stylename when importing.

Export:

Currently when exporting a style where the destination file already
exists we got:

```
style 'stylename' already exists.
```

With this patch we have

```
style '/path/to/style.dtstyle' already exists.
```

Import:

Currently when importing a style where the destination style already exists
we got:

```
style '/path/to/style.dtstyle' already exists.
```

With this patch we have

```
style 'stylename' already exists.
```

@TurboGit 
Just asking here but will open a new issue if you prefer:
The config keys to not ask for overwrite anymore is `plugins/lighttable/style/ask_before_delete_style`
but its name is not related to overwrite but to style deletion.

Perhaps a different config key like `plugins/lighttable/style/ask_before_overwrite_style` that affects both file overwrite on export and style overwrite on import could be better (or to be pedant two different keys for import overwrite and export overwrite).

2023-04-22 08:06 UTC, TurboGit commented
@sgotti : Or just do nothing, the overwrite is also a kind of delete. Maye just add a tooltip for the preference and so avoiding another pref.

2023-04-22 08:11 UTC, TurboGit requested changes
All in all to me style can be used for a file name or a style name. Given the external data presented (a full path or a single name) the user will not be confused.

2023-04-22 08:11 UTC, TurboGit commented on src/libs/styles.c
> +            GtkWidget *dialog_overwrite_export = gtk_dialog_new_with_buttons(_("overwrite file?"), GTK_WINDOW(win), GTK_DIALOG_DESTROY_WITH_PARENT,
I would keep style here. The fact that it is a file for a style is mostly a details not really important for users.

2023-04-22 08:11 UTC, TurboGit commented on src/libs/styles.c
> +            sprintf(overwrite_str, _("file `%s' already exists.\ndo you want to overwrite existing file?\n"), stylename);
Likewise I'll keep `style` and indeed using `stylename` here is better.

2023-04-22 08:11 UTC, TurboGit commented on src/libs/styles.c
> +            GtkWidget *overwrite_dialog_check_button = gtk_check_button_new_with_label(_("apply this option to all existing files"));
I'll keep styles.

2023-04-22 08:11 UTC, TurboGit commented on src/libs/styles.c
> +            sprintf(overwrite_str, _("style `%s' already exists.\ndo you want to overwrite existing style?\n"), bname);
Ok.

2023-04-22 12:41 UTC, sgotti commented on src/libs/styles.c
> +            GtkWidget *overwrite_dialog_check_button = gtk_check_button_new_with_label(_("apply this option to all existing files"));
Done

2023-04-22 12:41 UTC, sgotti commented on src/libs/styles.c
> +            sprintf(overwrite_str, _("style `%s' already exists.\ndo you want to overwrite existing style?\n"), bname);
Done

2023-04-22 12:41 UTC, sgotti commented on src/libs/styles.c
> +            GtkWidget *overwrite_dialog_check_button = gtk_check_button_new_with_label(_("apply this option to all existing files"));
Done

2023-04-23 06:22 UTC, TurboGit approved these changes
Thanks!

2023-04-23 06:23 UTC, merged