grain.c: optimize
darktable-org/darktable pull request #14440
Opened 2023-05-07 04:53 UTC by ralfbrown

Change data types and literal types to avoid implicit typecasts.
Precompute modulus on lookup table.
Constify, and a bit of code reformatting.

Passes test 0059 in about 15% less time.  I also looked at adding fast-math, finite-math-only, fp-contract=fast, no-math-errno optimization options; those got another 3% speedup but cause the test to fail with max dE 3.5 and most pixels changed (actually, the same results as testing with build-type Release instead of RelWithDebInfo, just even faster than Release without those optimization flags).

Because of the relatively small extra gain at the cost of changing the output, I have not included the optimization flags in the PR, but present the benchmark results below.
```
Thr	Master	PR		fastmath
1	1407.55	1194.64	-15.1%	1144.32	-18.7%
2	 705.26	 598.10	-15.1%	 573.06	-18.7%
4	 353.00	 299.02	-15.2%	 287.41	-18.5%
8	 176.47	 149.91	-15.0%	 143.90	-18.4%
16	  88.54	  75.19	-15.0%	  72.61	-18.0%
32	  45.50	  38.38	-15.6%	  37.11	-18.4%
64	  32.14	  25.08	-21.9%	  24.50	-23.7%
```

2023-05-07 10:19 UTC, TurboGit requested changes
Minor comment.

2023-05-07 10:19 UTC, TurboGit commented on src/iop/grain.c
> +//      out[3] = in[3];
Please remove or add a comment about why we keep it there.

2023-05-07 14:09 UTC, dterrahe commented
> cause the test to fail with max dE 3.5 and most pixels changed (actually, the same results as testing with build-type Release instead of RelWithDebInfo

For the avoidance of doubt; you are only referring to the speed differences here or does the Release build fail the test?

2023-05-07 17:21 UTC, ralfbrown commented
Release build fails multiple tests....  And has for years.  Max dE on those is 3-6.  ISTR a discussion about that not long after the integration tests were set up.

I'm beginning to think that the main culprit is that GCC likes to use a fast approximate reciprocal instruction with only 12 bits of precision to replace vectorized divisions when -ffast-math is enabled.

2023-05-07 17:54 UTC, dterrahe commented
> Release build fails multiple tests.... And has for years.

To an extent that its use should be discouraged? The Readme seems to do the opposite:
`./build.sh --prefix /opt/darktable --build-type Release --install --sudo`

@TurboGit ?

2023-05-07 19:19 UTC, ralfbrown commented
Or we could remove the -ffast-math from  the compiler flags for Release.  The other optimizations probabily make a bigger difference between RelWithDebInfo and Relase than that one (particularly now that the SSE code has been removed and we need to rely on the compiler to infer vectorization).

2023-05-08 05:46 UTC, TurboGit commented
> To an extent that its use should be discouraged?

Not really, what is important if you want to keep your edits the very same is to build using the same set of option.

We know that the OpenCL, CPU, SSE, compiler Release, Debug, RelWithDebug are all producing different images. The good news is that we have removed most of the SSE. But yet, a using not using OpenCL at some point and changing to use OpenCL will get different results. I don't see a way around that... Oh not speaking about different processors, I have slightly different result on two computer and the diff is even bigger for ralfbrown.

2023-05-08 05:59 UTC, TurboGit approved these changes
Thanks!

2023-05-08 06:00 UTC, merged

2023-05-08 12:25 UTC, dterrahe commented
Thanks for the extensive answer! Might be good to have a condensed version ("There are minute differences between different build types and depending on whether OpenCL is used, so in order to achieve identical results it is recommended to use as near identical configurations as possible.") Is RelWithDepInfo the most regression tested? Could other configs see bigger changes over time?

> we also have differences when using different number of CPU core

That just sounds like there might be a bug somewhere (possibly within OpenMP)? I can't really think of a reasonable explanation why this might occur (whereas, obviously, OpenCL/SSE/Optimisations all use slightly different math/shortcuts, so small changes _there_ are "expected". Or am I missing something? This is a learning thread for me :-)

2023-05-08 15:22 UTC, ralfbrown commented
The differences with different number of threads are due to different subdivision of labor among the threads leading to different accumulation of round-off errors, and only affect a couple of modules doing sliding-window computations (nlmeans being the main one).  It's fixable in principle by computing values from scratch for every pixel instead of doing incremental updates, at the cost of substantial slowdown.

The modules affected by number of threads would also be affected in a corresponding way by tiling.