Some details mask related fixes
darktable-org/darktable pull request #14442
Opened 2023-05-07 06:58 UTC by jenshannoschwalm

Be more defensive if no details mask data are available or can't be processed
- possibly write mask data to zero
- avoid processing at all if no valid hash or size of detail roi

Some improvements of debugging output via dt_print_pipe

An internal improvement is related to processing of very small images like previews. We do some blurring of the detail mask while blending, the strength of this blurring has been decreased for such data to have an effect at all.

2023-05-07 08:16 UTC, jenshannoschwalm commented
There are more problems, hold on

2023-05-07 13:56 UTC, jenshannoschwalm commented
Ready to go ... couldn't trigger any crashes or wrong data any more.

2023-05-07 17:56 UTC, jenshannoschwalm commented
Latest commit fixes inverted raster masks.

2023-05-07 18:03 UTC, jenshannoschwalm commented
@TurboGit Please have a look into raster masks inversion, that seems to be a very old bug. From my understanding the opacity is applied at the end of that function and must not be there. Right?

2023-05-08 05:40 UTC, TurboGit commented
@jenshannoschwalm: I'll have a look today.

2023-05-08 17:58 UTC, TurboGit commented
> @TurboGit Please have a look into raster masks inversion, that seems to be a very old bug. From my understanding the opacity is applied at the end of that function and must not be there. Right?

@jenshannoschwalm : No the actual code is correct to me. We are speaking about the opacity of the module using the raster mask. So we do need to take the opacity into account.

To be sure I have tested this with an image (flat grey). I have create a mask for half of the image.

On a module above I have used the raster mask. Apply a strong change, invert the mask and see that each part are equal. Set opacity to 50% check that each side are equal by inverting the mask. This is true with current master but not with your change here.

2023-05-08 18:18 UTC, jenshannoschwalm commented
Ok. Sort of understood :-) Will cleanup the rest

2023-05-08 19:01 UTC, jenshannoschwalm commented
Also added the opencl fix related to #14447

Should be good for a full review and ready to merge as i see it.

2023-05-09 07:51 UTC, TurboGit requested changes
Not yet tested, some comments after review.

2023-05-09 07:51 UTC, TurboGit commented on src/develop/blend.c
> +  cl_mem dev_blurmat = dt_opencl_copy_host_to_device_constant(devid, sizeof(float) * 13, blurmat);
`sizeof(float) * 13` -> `sizeof(blurmat)`

2023-05-09 07:51 UTC, TurboGit commented on src/develop/masks/detail.c
> +    memset(out, 0, msize * sizeof(float));
`memset(..)` could be replaced by:
`dt_iop_image_fill(out, 0.0f, details->roi.width, details->roi.height, 1);`

2023-05-10 05:54 UTC, TurboGit approved these changes
Works for me, thanks!

2023-05-10 05:54 UTC, merged