lens: new embedded metadata algorithm
darktable-org/darktable pull request #14468
Opened 2023-05-10 12:07 UTC by sgotti

This replaces PR #14333 with an improved version.

---
Introduce new embedded metadata algorithm (v2).

Keep backward compatibility for old edits keeping also the old
algorithm.

Increase the parameters version to 8.

The new algorithm introduces many fixes to the logic, fuji corrections and vignetting corrections.

## Fuji fixes

The old algorithm scales only the spline values trying to match the output of the ooc jpeg. This scaling was sospicius since it doesn't make much sense. After an analysis of the corrections done by ADC and other proprietary tools that provides a better correction than the ooc jpeg, looks like the ooc jpeg doesn't provide a good correction and cannot be trusted to do reverse enginerring.

From the above analysis looks like the fuji distortion metadata are related to the source image radius. For example corrections for radius 1 means that input image radius should be multiplied by the provided factor.

Since we want to map from destination radius to source radius, using that spline is not correct and will lead to not perfect correction and the v1 algorithm strange scaling logic.

So we map the source radius based spline to a destination radius based spline.

* Also add a knot with no corrections if a there isn't a knot for the center (radius 0) or the spline interpolation will return the same values for inputs from 0 to the first knot giving not good distortion corrections for this range.

## Sony images

The sony image logic has not been changed but with the new algo there's a little change since there isn't the spline values scale anymore. Looking at some sony images looks like the current version is better than the old one but this requires further investigation to understand if also sony images requires a mapping from source radius to destination radius or they are already ok.

## Scaling improvements

PR 12880 introduced a scaling fine tune parameter. This isn't used anymore.

Instead add an image scaling parameter that will scale the image like already done by the lensfun method.

The new algorithm automatically scales the spline knots and values to only show the visibile image (without distortion borders) so when the scaling parameter is 1.0 the image is displayed to its maximum visible contents.

## Vignetting fixes

Fix vignetting correction by not using the square of the correction factor since I tested different fuji images and there was too much vignetting correction. Using the correction factor as is looked much better.

I also tested some sony images and I think that also these images don't need the squared factor.

For dng there was already a fix during spline calculation that took the square root of correction factor to counteract the squaring done during vignetting correction.

---

@jenshannoschwalm some notes:
* Since the new parameters v7 introduced by PR #12880 were introduced in this development cycle I reused this version to simplify the code. This will break edits for only the ones using the development version (with the unclear error `module 'lens' version mismatch: history is 7, darktable is 7` caused by different parameters sizes). Is it ok for you? 
* The cor_scale has been removed and a scale_md parameter is used to just scale the image (zoom in, out) like done by lensfun.
* Sony corrections looks good also if changed a bit due to the removed autoscale multiplication. They needs some further investigations (perhaps in future) to understand if the current changes are ok also for sony images.
* Now the spline knots and values are scaled like already done by the dng metadata, so for a scale_md == 1.0 the images is already correctly scaled to its maximum visible contents.
* This also merges vignetting fixes in PR #14455. The init_coeffs_md_v1, to keep backward compatibility calculates the square factor for sony and fuji images and removes the square root for dng images.
* This also merges dng knots fixes in PR #14454

2023-05-10 12:40 UTC, sgotti commented on src/iop/lens.cc
> +    const float cx = (xoff + i - w2) / d->scale_md;
@FreddieWitherden Done for all the functions. Can you check if it's what you meant? Thanks.

2023-05-10 12:42 UTC, FreddieWitherden commented on src/iop/lens.cc
> +    const float cx = (xoff + i - w2) / d->scale_md;
Can simplify a little more in some cases as `cx` and `cy` get the same factor. So `sqrt(cx*cx + cy*cy)` can have the factor pulled out of the square root entirely.

2023-05-10 12:48 UTC, sgotti commented
@FreddieWitherden While I was changing `_modify_roi_in_md` I noticed this part:

https://github.com/darktable-org/darktable/blob/382b305dbd674e6566396698f19250164a0f6b1a/src/iop/lens.cc#L2384-L2393

But I don't understand the check and the relation between the vignetting factor and the radius (since vignetting should only affect the pixel value, not the position).

2023-05-10 12:52 UTC, FreddieWitherden commented
I do not recall writing that check.  Appears to have come in here:

https://github.com/darktable-org/darktable/commit/24e4139096f86c0285510974e9d55d59149a2ec3

@jenshannoschwalm do you recall what the issue was that necessitated this check?

2023-05-10 13:06 UTC, jenshannoschwalm commented
BTW - i am testing it here on the DNG files i have -- no issue

2023-05-10 13:16 UTC, sgotti commented
> I was doing this because of the DNG specs. For 1.6 it says (jus a screenshot for my conveniance)

Thanks. The dng specs is confusing. The first formula looks the same as the current lens.cc code: it doesn't change position on vignetting correction but only multiple the channels values for the correction factor. The "where" parts adds the confusion but probably only explain how to find the radius in the required coordinates space.

But the code here https://github.com/darktable-org/darktable/blob/382b305dbd674e6566396698f19250164a0f6b1a/src/iop/lens.cc#L2384-L2393r multiplies the radius for the vignetting correction and it looks wrong.

2023-05-10 19:03 UTC, jenshannoschwalm commented
One more comment, i know that people using master "should expect trouble" :-) But also we encourage people to use OBS or self-compiled darktable for better dev feedback. And i guess many - not only me - have some presets for lens module or just one with "enable-all-defaults". 

So i would really suggest to do a version bump again. While doing so you might add a float or int reserved for idea to be implemented later ...

2023-05-10 20:20 UTC, sgotti commented
> So i would really suggest to do a version bump again. While doing so you might add a float or int reserved for idea to be implemented later ...

Ok!
* When upgrading from versions < v6 the metadata algo is set to v2 since no metadata method existed at the version
* When upgrading from parameters v6, if the method is metadata, the old algo v1 is used.
* The algorithm version is hidden and not selectable
* To switch to the new Algo a reset is needed

Questions:
* Should we show somewhere that an old metadata algorithm is in use and that to switch to the new a reset is needed?
* The new bump version will be v8, will use the same logic used for v6 also for v7->v8, ok?
* We should use two different sliders for cor_scale and scale_md, and show cor_scale only when using algo v1 and scale_md only when using algo v2, this could be confusing since both slider contains the "scale" word (scale fine-tune and scale) but with totally different meaning//effects.

2023-05-10 20:30 UTC, TurboGit commented
> * Should we show somewhere that an old metadata algorithm is in use and that to switch to the new a reset is needed?

Would be nice, you may want to look at what has been done for `fix_anscombe_and_nlmeans_norm` in `denoiseprofile.c` when moving from v7 to v8.

2023-05-10 20:34 UTC, TurboGit commented
> * We should use two different sliders for cor_scale and scale_md, and show cor_scale only when using algo v1 and scale_md only when using algo v2, this could be confusing since both slider contains the "scale" word (scale fine-tune and scale) but with totally different meaning//effects.

Not sure to understand. I'll use a single slider on the UI which will be used for controlling the algorithm. The current one for current algorithm and when the history is reset the new algorithm is used and the "same" slider is used even if having different behavior. No?

So to me your first part is ok: "We should use two different sliders for cor_scale and scale_md, and show cor_scale only when using algo v1 and scale_md only when using algo v2".

2023-05-11 07:46 UTC, sgotti commented
> Not sure to understand. I'll use a single slider on the UI which will be used for controlling the algorithm. The current one for current algorithm and when the history is reset the new algorithm is used and the "same" slider is used even if having different behavior. No?

@TurboGit It's just that they have different descriptions and min/max values. So internally they must be implemented as two sliders since they're managed by the introspection code. Then only one of them will be shown.

But, since the cor_scale introduced in v7 is pratically unuseful, I'd like to just never show it in the gui. I'll keep it in the params and use it in the algo v1 so it won't break current edits (if anyone ever used it), but users won't be able to change it in the gui. What do you think?

2023-05-11 09:11 UTC, sgotti commented
> Would be nice, you may want to look at what has been done for `fix_anscombe_and_nlmeans_norm` in `denoiseprofile.c` when moving from v7 to v8.

Did something similar. The toggle button will update to the latest alghoritm. Let me know if it's ok for you.

> But, since the cor_scale introduced in v7 is pratically unuseful, I'd like to just never show it in the gui. I'll keep it in the params and use it in the algo v1 so it won't break current edits (if anyone ever used it), but users won't be able to change it in the gui. What do you think?

Did this and also always show the new "scale image" slider.

In the meantime I renamed `cor_scale` to `scale_md_v1` to better understand its meaning.

2023-05-11 11:08 UTC, TurboGit commented
> @TurboGit do you think it could be useful to add an image and two related xmp (migration from v6->v8 and v7->v8) to the integration tests to check the outcome is the same (use old metadata algo)?

A good idea yes.

2023-05-11 14:44 UTC, sgotti commented
> A good idea yes.

@TurboGit @jenshannoschwalm I created some new integration tests, but I noticed that between dt 4.2.1 and current master (without this PR AND without the lens module enabled) the generated image width is 1px smaller (1366x2048 vs 1365x2048).
So it's not related to this PR but they cannot be added to the integration tests repo since they'll fail.

It looked something related to my xtrans file (I added a new file for this test) width/height and scaling to 2048 since without scaling the output size is the same. So looking for "scaling" in commits history I found that the change was introduced by 4f845428f54cc02793bf723199d2e34b1091f116 (PR #13329)

2023-05-11 15:04 UTC, TurboGit commented
> I created some new integration tests, but I noticed that between dt 4.2.1 and current master (without this PR AND without the lens module enabled) the generated image width is 1px smaller (1366x2048 vs 1365x2048).
> So it's not related to this PR but they cannot be added to the integration tests repo since they'll fail.

This is expected as in 4.3 we have reworked the pipeline and have more stable picture size. Anyway, what we should do is create a .xmp without this PR and not with 4.2.1 which is too old.

2023-05-12 05:55 UTC, TurboGit commented
> So yes, we encourage users to test new code, but we must clearly state that the results of using such code are of unguaranteed quality and reproducibility.
> 
> My idea is that it is not worth it without a real and unavoidable need to increase the complexity of the code, so I am against the version bump, which will increase the possibility of errors when updating between versions.

I generally agree with you about this. Yet in this case there has been quite some time between both implementation and we encourage more and more people to try out dt master and report for issues. The field testing is very important for us and so when possible and not too complex we must try to avoid any breaking of edits. In this case I did feel that it was the case.

2023-05-12 08:35 UTC, sgotti commented
While we are changing params I also added CA fine tuning like already available for distortion and vignetting. From various tests on fuji images I noticed that some looks good with the default values while other requires fine tuning.

2023-05-12 13:15 UTC, TurboGit requested changes
One minor issue:
- Have at least two images with an old algorithm
- Got to darkroom with the first one
- Tick : use new algorithm
- The tick line is now hidden (I would have kept it visible until we change image to let a chance to the user to revert the choice if this is not acceptable for the edit - a minor point and I have no strong opinion on this).
- Go to next image (using SPACE)
- See that the "use latest algorithm" is ticked (which is wrong)
- And if you click on it the line is hidden and new algorithm actually  selected

So a clear state for this tick is needed when changing image (maybe in gui_update?).

2023-05-12 13:39 UTC, sgotti commented
> So a clear state for this tick is needed when changing image (maybe in gui_update?).

Thanks, should be fixed.

> The tick line is now hidden (I would have kept it visible until we change image to let a chance to the user to revert the choice if this is not acceptable for the edit - a minor point and I have no strong opinion on this).

I just kept the same logic as done for fix_anscombe_and_nlmeans_norm in denoiseprofile.c. To go back users can undo (trying to keep it visible until the user changes something else will be quite difficult, at least for me...). 

Perhaps a button instead of a toggle should be better?

2023-05-12 14:27 UTC, TurboGit commented
> I just kept the same logic as done for fix_anscombe_and_nlmeans_norm in denoiseprofile.c.

Ok then. As I said no strong opinion here. I'll review/test again soon.

2023-05-12 17:18 UTC, TurboGit approved these changes
Thanks!

2023-05-12 17:19 UTC, merged

2023-05-12 17:21 UTC, TurboGit commented
@sgotti : Just need a little release notes entry please.

2023-05-12 20:55 UTC, sgotti commented
@TurboGit Release notes:

An improved algorithm for embedded metadata lens correction has been added to the lens module. It improves distortion and vignetting corrections for the supported Fujifilm and Sony images.
New sliders for changing the image scaling and chromatic aberration fine tuning has been added.

2023-05-12 21:03 UTC, TurboGit commented
@sgotti : Thanks, now integrated.