More finishing touches for the shortcuts system
darktable-org/darktable pull request #14991
Opened 2023-08-01 16:37 UTC by dterrahe

I. It is now possible to disable ("delete") default shortcuts and fallbacks and have them _stay_ disabled after a restart. This is done by moving them to a separate shortcut category "disabled defaults". "deleting" them from there restores them to their active state (possibly after confirmation to overwrite any conflicting shortcuts that had been defined replacing them). The other shortcut categories ("in active view"/"in other views"/"fallbacks"/"speed adjustments") have been renamed for clarity. The _no-op_ action (which previously could be used to overwrite a default shortcut with "nothing" and thereby disable it) has been removed as it is no longer needed. This new approach works better with fallbacks; you can now define "e" as exposure and have ctrl+e make small adjustments. It also exposed a double definition of ctrl+k as both the collections "history" button and "jump back to previous collection". The latter now has been moved to ctrl+shift+k, but will still be in existing users shortcutsrc file as ctrl+k as well, so "history" will show up as a disabled default. Deleting (restoring) it from there will overwrite the double definition.
![image](https://github.com/darktable-org/darktable/assets/1549490/d7be4ea9-fe41-46ce-ac64-eb62dd9b7d46)

II. The "keyboard" icon in the shortcut mapping mode button is now also used as the mouse cursor when in mapping mode, closing  #9483. If a widget can be added to or removed from the quick access panel, a + or - is added to the mouse cursor.
![image](https://github.com/darktable-org/darktable/assets/1549490/e4101c41-5453-4376-8f01-f69d03e4ba5a)

III. A text is added to the shortcuts dialog (whether embedded in preferences or freestanding) to explain that shortcut mapping mode may be faster. Clicking on it removes so it does not permanently take up space. This may have more success being read than a tooltip or manual entry.
![image](https://github.com/darktable-org/darktable/assets/1549490/2b419d58-a7e0-4392-8cff-1be475d43751)

IV. The ability to assign separate shortcuts to an up and down move has been extended. This works with key+scroll wheel as well as mouse moves, which could be a left/right or diagonal, and gamepad joystick moves or midi encoder turns.  Previously only the same action/widget was supported (so you could already assign different dropdown items to `key+scroll up` and `key+scroll down`). Now this works for any combination of single effect shortcuts that are active in the same views. So if you assign a "command" action to a key+move shortcut, if you assign the same shortcut again (but with opposite move) to a different command, you will be asked if you want to split (and if not, if you want to overwrite). If you map a move to a slider or combo, you can change the _effect_ and then assign the opposite move to a different effect. As an example, the `b` key (which toggles the panel expander indicators) can be overloaded to toggle hiding the top/bottom/left/right side panels by moving the mouse up/down/left/right while holding the key.
![image](https://github.com/darktable-org/darktable/assets/1549490/aff467a2-e45f-4f3a-90ce-88d1b9a3fb44)

V. This always created the problem that if a key+move shortcut was assigned to a slider or combo popup, the repeating key would immediately start filling the popup. This has now been resolved by linking the bauhaus popup into the shortcut dispatcher. This means shortcuts and keys not handled by the popup, like full screen or panel hiding, will continue to work as normal. As a silly exercise you can quickly check all hue and chroma values in the color balance module even when it is hidden by pressing r and moving the mouse in a circle after defining these shortcuts:
![image](https://github.com/darktable-org/darktable/assets/1549490/047b4fd8-9ef8-4cc3-a3f6-0e03aec0077f)

VI. It also meant the bauhaus popup keyboard input had to be fixed to correctly indicate what was being handled by it. During that work I improved (imho) the filtering of combobox items when typing. Previously this only matched on the start of items (which made it less useful for multiple items starting with RGB for example). Now it matches any part of the item and only fades (rather than completely removes) unmatched items. This means group headings are still visible and makes what's going on more clear. If only one item is remaining, pressing Enter selects it. Otherwise arrow keys and scroll wheel moves between them.
<img src="https://github.com/darktable-org/darktable/assets/1549490/71f570e7-4297-4322-a043-50dd9a9c065c" width="30%" height="30%"><img src="https://github.com/darktable-org/darktable/assets/1549490/779cf769-07e0-4732-940e-7bf76612f783" width="30%" height="30%"><img src="https://github.com/darktable-org/darktable/assets/1549490/ac5a3c96-aaec-4e28-ba17-b5fc2faaed25" width="30%" height="30%">

VII. Some refinements to fallbacks. For example, if a key is assigned to a specific value in a slider or combo (using _effects_), then pressing the key will select that value but holding the key and scrolling still adjusts the value as it normally would if no specific value was selected (fast or slow if shift or ctrl held).

VIII. In the darkroom, you can now switch between module groups using the scroll wheel (just like you can with other notebook tabs). This can be useful when you are in mapping mode and you want to setup shortcuts for several modules at once; clicking on a module group to find the module you want would open the shortcuts dialog.

2023-08-02 17:28 UTC, TurboGit requested changes
Minor changes. I also tested and it feels ok to me. One point is the new way to select entries in combo-boxes. It is ok by me the way you propose it but could be a bit controversial for others. We'll see...

2023-08-02 18:06 UTC, dterrahe commented on src/gui/accelerators.c
> +      _("The recommended way to assign shortcuts to visual elements is the <b>visual shortcut mapping</b> mode.\n"
Fixed; thanks for catching!

2023-08-02 18:06 UTC, dterrahe commented
> could be a bit controversial for others

In the existing implementation there are quite a few strange behaviors when combo items are being filtered by entering text, and I haven't seen any complaints about that, which leads me to believe very few people use this functionality. It is really only useful when combined with shortcuts, i.e. when using only the keyboard, arrow keys etc, and then even if it looks different, it still works the same. But as you say, we'll see. Usually people only complain about improvements.

2023-08-03 07:16 UTC, TurboGit requested changes
Found another issue, entering a value in a slider is not working.

On any slider:
- Right click
- Enter a value, say 0.1 on exposure module
- Press enter
- ERROR: See that the value just entered is ignored

2023-08-03 23:04 UTC, dterrahe commented
> entering a value in a slider is not working.

Fixed in the last commit. I tried to somewhat simplify the handling of actions that close the popup. There was an apparently mac specific workaround (e29997f) that seemed maybe unnecessarily complicated, but I can't test on that platform. Maybe @MStraeten is willing to assist?

A subtle improvement for combos; when the popup is open, clicking (and holding) on an item and then dragging to another item seemed to change the selection, but when the button was released the first clicked-on item was left active. Now the popup immediately closes on the click, so there's no confusion.

2023-08-04 08:36 UTC, MStraeten commented
> Found another issue, entering a value in a slider is not working.
> On any slider:
> * Right click
> * Enter a value, say 0.1 on exposure module
> * Press enter
> * ERROR: See that the value just entered is ignored

can't reproduce that on my mac build with #14991 integrated 

need to understand first what needs to be tested ...

2023-08-04 11:34 UTC, dterrahe commented
Thanks Martin for looking at this so promptly and for pointing out I wasn't very clear in what I needed from you. In this PR I am partly reverting/replacing the fix in e29997f71552597bbe71115033ecdb70331d2863 for a mac specific issue. I think the new code is more straightforward and should work (it does on linux and windows), but I can't test it on the mac and therefore don't know if the previous problem returned. It was described as:

> fix popup closing on mouse button release on macOS
behaviour was different depending on whether tooltip was shown or not
without tooltip popup stayed open (as expected),
otherwise popup window closed as soon as mouse button was released

Do you see anything like that when interacting with bauhaus widgets after applying this PR? It's not clear to me either whether this happened when left clicking or right clicking to open the popup or whether it occurred with combos or sliders. Do you see any strange behavior basically. :-)

2023-08-04 16:53 UTC, TurboGit approved these changes
Works for me, didn't find other issues.

So ready to go, just waiting for @MStraeten to check on macOS.

2023-08-05 09:56 UTC, MStraeten commented
did some test with right mouseclick slider popup - works as i expect:
right click opens, stays open as long as the mouse cursor stays on the popup and isn't moved to another object reacting on mouse events.
closes if moved to another gui object without taking over a value typed in but not confirmed by enter or mouseclick after using mouse around to change values.
closes on enter or mouseclick with aking over values

2023-08-05 11:52 UTC, merged

2023-11-24 13:58 UTC, TurboGit commented
@dterrahe : Anything to add in the release notes or should I just remove the tag from here? TIA.

2023-11-24 17:10 UTC, dterrahe commented
release notes:
- The shortcuts system received several refinements:
  - deleting or overwriting a default shortcut moves it to the "disabled defaults" category from where it can restored by pressing Delete. It is no longer necessary to uncheck "load default shortcuts at startup" (in prefs/misc/interface) to keep it disabled.
  - visual mapping mode has better mouse cursors to indicate whether the widget under the cursor can have a shortcut or be added to (or removed from) the quick access panel.
  - the shortcuts preference tab now explains that it may be more convenient to use visual mapping mode.
  - when combining a shortcut with a move (for example b+scroll) separate actions can be triggered by up and down moves. b+scroll _up_ could cycle through the top panel options and b+scroll _down_ through the bottom panel combinations.
  - a problem with dropdown and slider popups opened via a shortcut was fixed. They would immediately fill with the shortcut key character. Now those popups are integrated into the shortcut system, so most non-alphanumeric shortcuts continue to work. If a dropdown value is changed while the popup is open (for example via a calculation (AI detection in color calibration), lua script or midi shortcut, the popup is correctly updated/repositioned. After a popup is closed it can quickly be reopened to enter another value by pressing Enter (as long as the corresponding widget still has focus).

2023-11-24 17:53 UTC, TurboGit commented
@dterrahe : Thanks a lot, we are now complete for the release.