further improvements to thumbnail placement in culling
darktable-org/darktable pull request #15197
Opened 2023-09-05 22:17 UTC by Solarer

@ Reviewer: I have not cleaned up / squashed the commits yet because I want to get the functionality of this PR approved first before I do a final cleaning. Since I changed many code lines I will try to organize this in a way to make review easier.

This is a follow up PR to #14966 which left a few issues unaddressed.
* sometimes images do not have the same height (see #12875)
* 'stacking' functionality was completely borked

Fixed issues:
* Stacking now works as intended without overlapping thumbnails or leaving the screen. To reproduce, display 3 or more thumbnails where the combined height of 2 thumbnails is smaller than the third.

original             |  fixed
:-------------------------:|:-------------------------:
![image](https://github.com/darktable-org/darktable/assets/2805109/aa672724-270d-4af6-9cf1-b2afbf430dbf)  |  ![image](https://github.com/darktable-org/darktable/assets/2805109/37148d7a-1a87-4480-87b9-3509f4f41416)

* Thumbnails are now scaled to equal height. 
To avoid gigantic thumbnails when scaling very slim thumbnails, I limited this to 2 times the average thumbnail width.
This does even out slight differences (example 1) but also makes better use of the available space when displaying mixed aspect ratios of portrait and landscape images (example 2)

original             |  fixed
:-------------------------:|:-------------------------:
![image](https://github.com/darktable-org/darktable/assets/2805109/fe8bc399-06c2-4034-8786-a81a1e659dbd)  |  ![image](https://github.com/darktable-org/darktable/assets/2805109/2d83f148-c501-4c8b-a694-8a386a38cffd)
![image](https://github.com/darktable-org/darktable/assets/2805109/1cc8e72b-5308-4b53-8515-6fe58b10004a)  |  ![image](https://github.com/darktable-org/darktable/assets/2805109/7053ac6a-b858-45f9-8079-e9947dbafc82)

I personally found this irritating when looking at only 2 images (one a landscape and the other a portrait) since the landscape will appear to be bigger than the portrait. Therefore I limited scaling to 20% if only 2 images are displayed. This does even out small differences but portrait and landscape will not be scaled to the same height.

without 20% limit (just a test, I do not like this)            |  with 20% limit (my final implementation - looks like before)
:-------------------------:|:-------------------------:
![image](https://github.com/darktable-org/darktable/assets/2805109/e4cd311f-5292-4a18-b219-b87c50fc500c)  | ![image](https://github.com/darktable-org/darktable/assets/2805109/dca69f80-1846-4c59-bf0e-18d8229fc797)

* Scaling all images to the same height allowed me to simplify the thumbnail placement algorithm and achieve better placement results in some situations

original             |  fixed
:-------------------------:|:-------------------------:
![image](https://github.com/darktable-org/darktable/assets/2805109/23e7592c-bdb3-4764-9472-9b0cb3647f32)  |  ![image](https://github.com/darktable-org/darktable/assets/2805109/116061ee-80b1-4d4a-9ae4-30d9b2e50e01)

2023-09-06 08:40 UTC, TurboGit commented
First test on my side and this looks really better. I was about to create an issue yesterday as on two duplicated images I had not a proper synch of the view when zooming in (that is, one image was zoomed a bit more than the other even-though they were true duplicate - only one was B&W). This is now working properly on my side, so this issue is also fixed here.

All in all, this seems really good to me.

2023-09-06 08:45 UTC, TurboGit requested changes
Some minor style issues.

2023-09-06 08:45 UTC, TurboGit commented on src/dtgtk/culling.c
> +
duplicate empty line - can be removed

2023-09-06 08:45 UTC, TurboGit commented on src/dtgtk/culling.c
> +
likewise

2023-09-06 08:45 UTC, TurboGit commented on src/dtgtk/culling.c
> +    float planned_total_width_tmp = total_slot_width / (float) row_cnt_tmp;
const

2023-09-06 08:45 UTC, TurboGit commented on src/dtgtk/culling.c
> +    int planned_total_height_tmp = row_cnt_tmp * max_slot_heigth;
const

2023-09-06 08:45 UTC, TurboGit commented on src/dtgtk/culling.c
> +        dt_thumbnail_t *thumb = (dt_thumbnail_t *)slot_thumb_iter->data;
const

2023-09-06 08:45 UTC, TurboGit commented on src/dtgtk/culling.c
> +        dt_thumbnail_t *thumb = (dt_thumbnail_t *)slot_thumb_iter->data;
const

2023-09-10 21:03 UTC, Solarer commented
@TurboGit I fixed the style issues.
Did you check for them manually or did you run a command that showed you missing `const` and duplicated newlines?

2023-09-11 06:09 UTC, TurboGit commented
> Did you check for them manually or did you run a command that showed you missing `const` and duplicated newlines?

By code reading.

2023-09-11 06:45 UTC, TurboGit approved these changes
Very nice improvements. Thanks!

2023-09-11 06:46 UTC, merged