imageio_libraw: double check Canon CR3 model support
darktable-org/darktable pull request #15301
Opened 2023-09-22 13:38 UTC by kmilos

This avoids LibRaw reading CR3 files with a wrong input profile for unsupported cameras (substring match e.g. R50->R5, R100->R10, R6m2->R6 etc.)

It should also handle the impending scenario where a darktable package (appimage, snap, etc.) is built w/ in-tree (public beta) LibRaw that is e.g. ahead of a system supplied (stable) one.

2023-09-22 15:53 UTC, wpferguson commented
Current master and 4.4.2 open R6m2 files just fine.  This PR stops that from happening and produces the unsupported camera error.

Since darktable has supported those images up until this PR, there are probably existing edits for these images and this PR will break them and make the image inaccessible.

I'm not sure what the right answer is here....

2023-09-22 16:45 UTC, kmilos commented
> Current master and 4.4.2 open R6m2 files just fine.

It does not. You're getting the incorrect input profile of R6, so any future edits will be incompatible once LibRaw truly supports it.

2023-09-22 16:58 UTC, wpferguson commented
So how do we handle user expectations?  

They could open the images and edit them and now they'll be greeted with an error.  Should we start a public relations campaign on pixls and the mailing list to manage user expectations?

2023-09-22 17:26 UTC, kmilos commented
First off, dt never announced support for these models, so...

Second, we don't have to merge this now. I hope LibRaw will release a public beta in the 4.6 timeframe, so we can include these, and the not allow opening of future unsupported models. However, there is still some risk of breakage for people using distros that build against the stable LibRaw 0.21 for dt 4.6...

2023-09-22 18:21 UTC, wpferguson commented
> I hope LibRaw will release a public beta in the 4.6 timeframe, so we can include these, and then not allow opening of future unsupported models

That would be a very good solution

2023-10-07 06:43 UTC, TurboGit commented
Given the release cycle and discussion I'll merge this at the very last moment, so around mid-november.

2023-11-17 15:23 UTC, kmilos commented
My plan for this one: let's wait until Nov 24, when LibRaw discount sale of their commercial products ends - I don't see them releasing the new public beta version before then. If it still doesn't happen, let's then work on making this into a warning rather than an error.

2023-11-28 08:23 UTC, kmilos commented
Cyber Monday came and went, but still no new public release...

I've changed the PR so a warning is shown instead for the Canon CR3 models not yet officially supported by LibRaw.

Please feel free to change the warning message as you see fit before the string freeze.

2023-11-28 21:35 UTC, TurboGit requested changes
Minor comment otherwise ok to me.

2023-11-29 07:35 UTC, TurboGit commented
I'll merge now before the string freeze and do the casing change.

2023-11-29 07:35 UTC, merged

2023-11-29 08:23 UTC, kmilos commented
Thanks, sorry I haven't managed to do it sooner.

2023-12-18 21:15 UTC, agriggio commented
Thanks for the ping @kmilos, not nice indeed...