thumbtable: Remove two g_list_length calls in loop.
darktable-org/darktable pull request #15454
Opened 2023-10-20 06:58 UTC by TurboGit

The call to g_list_length does iterate over all items to count them. As inside the loop we don't add or remove object it is safe to count items before entering the loop.

@AlicVB : If I'm not mistaken this bring some speed up and should be safe.

2023-10-20 11:16 UTC, dterrahe commented
Or you could just directly get `g_list_nth_data` and check that it is not NULL. That saves another list traversal :-)

2023-10-20 11:29 UTC, TurboGit commented
> Or you could just directly get `g_list_nth_data` and check that it is not NULL. That saves another list traversal :-)

I don't think so since `g_list_nth_data` do traverse all the list to check for the Nth item.

2023-10-20 12:21 UTC, dterrahe commented
Currently you do `g_list_length` and then if `pos < length - 1` you do `g_list_nth_data(pos+1)`. Two traversals.

Instead you could do `g_list_nth_data(pos)` and `if !NULL && next !NULL` take next. That is just one traversal.

2023-10-20 12:24 UTC, ralfbrown commented
I've only taken a very quick look, but I think the `g_list_nth_data` can be removed as well.  At the time it gets called, the `pos+1` position in table->list is simply the next element beyond the one being processed, so we can use `l->next->data` to get it.

2023-10-20 12:46 UTC, dterrahe commented
> I've only taken a very quick look

That's cheating! You actually tried to figure out what the code _does_. If you keep going on like this, the thumbtable will have finished scrolling before we even reach for the mousewheel!

2023-10-20 17:02 UTC, TurboGit commented
> Currently you do `g_list_length` and then if `pos < length - 1` you do `g_list_nth_data(pos+1)`. Two traversals.

No, I'm doing a single `g_list_length` outside of the loop avoiding N traversal (N = number of thumbs on collection) and so avoiding most of the traversal as `g_list_nth_data(pos+1)` is done only for is `pos < table_len`, and `pos` being a simple variant incremented into the loop. That being said, I'm tired tonight so I could well be missing the point especially since most of your comments are valid...

2023-10-20 18:48 UTC, dterrahe commented
> I'm tired tonight

I had the opposite problem; I had not woken up this morning before responding. Somehow I interpreted the title of the PR as _both_ g_list_length calls being inside the loop and didn't look closely enough to realise I was being stupid. Not even after your response. Apologies for wasting your time. :embarrassed:

I do think @ralfbrown does have a point that all the (conditional, so probably not that many anyway, unless the groups are large) calls to `g_list_nth_data` can also be removed or sped up, by referring to the current position in the list directly. `g_list_nth_data(table->list, pos + table->thumbs_per_row)` is I believe equivalent to `g_list_nth_data(l, table->thumbs_per_row)` and `g_list_nth_data(table->list, pos - table->thumbs_per_row)` could be simplified to `g_list_nth_prev(l, table->thumbs_per_row)`.

2023-10-20 20:08 UTC, AlicVB requested changes
some small addition to @ralfbrown  and @dterrahe great proposals...
(except that we need a `->data` after `g_list_nth_prev(l, table->thumbs_per_row)` if I'm not mistaken.

I'm quite sure that we do a lot a such enhancement in that code. I prpopose to let you enhance just this part and I check the rest of the code now...

2023-10-20 20:08 UTC, AlicVB commented on src/dtgtk/thumbtable.c
>            if(table->mode != DT_THUMBTABLE_MODE_FILMSTRIP
this check is superfluous (tested in parent condition)

2023-10-20 20:08 UTC, AlicVB commented on src/dtgtk/thumbtable.c
> +             && pos < table_len - 1
or we can just test if `g_list_next(l)` is valid... but as I'm not sure how to remove the next call to `g_list_length` maybe it's more clear to write it like that...

2023-10-20 21:28 UTC, merged

2023-10-20 21:29 UTC, TurboGit commented
@AlicVB : As proposed, I have merged this PR and let you continue on the other optimizations. TIA.

2023-11-06 02:35 UTC, ralfbrown commented
> thumbtable will have finished scrolling before we even reach for the mousewheel!

I finally had a chance to update my installation to current master and give it a quick whirl.  While it isn't _quite_ that fast yet :), I'm unable to out-scroll the thumbtable even with a collection containing all 361k images in my library.