Fix ashift crashes while removing lines
darktable-org/darktable pull request #15750
Opened 2023-11-26 18:32 UTC by jenshannoschwalm

Found two bugs here
1. avoid out-of-array access while removing line segments
2. use dt_alloc_align_float and dt_free_align for image data and we make use of vector-optimized functions so we want to make sure

While being here
- added some safety checks while allocating
- avoid g_malloc0 and use calloc instead to safely use free()
- changed int to gboolean where appropriate

2023-11-26 21:49 UTC, TurboGit approved these changes
Looks good, thanks!

2023-11-26 21:52 UTC, TurboGit requested changes
Makes dt crash, I open an image and clicked on the auto line detection of ashift.

2023-11-26 21:54 UTC, TurboGit commented
Sadly the backtrace is not really helpful :

```
(gdb) bt
#0  dt_iop_image_copy._omp_fn.0 ()
    at /home/obry/dev/builds/c-darktable/x86_64-linux-gnu-default/src/src/common/imagebuf.c:171
#1  0x00007ffff770d36e in  () at /lib/x86_64-linux-gnu/libgomp.so.1
#2  0x00007ffff78a63ec in start_thread (arg=<optimized out>)
    at ./nptl/pthread_create.c:444
#3  0x00007ffff7926a4c in clone3 ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
```

2023-11-26 21:58 UTC, TurboGit commented on src/iop/ashift.c
> +    buffer = dt_alloc_align_float((size_t)width * height);
missing 4 ?

2023-11-26 22:26 UTC, jenshannoschwalm commented on src/iop/ashift.c
> +    buffer = dt_alloc_align_float((size_t)width * height);
Thanks!

2023-11-26 22:27 UTC, jenshannoschwalm commented
force-push squashed commit with the bug spotted by @TurboGit

2023-11-27 07:05 UTC, TurboGit approved these changes
Works for me now, thanks!

2023-11-27 07:05 UTC, merged