Stellen Sie einen dpi-Faktor von mindestens 1,0 sicher
darktable-org/darktable pull request #15845
Opened 2023-12-08 17:39 UTC by zisoft

What really annoys me from my beginning of using darktable was some extremely small GUI elements on my Mac.

After doing some research I found out that the DPI screen resolution of a Mac screen is reported by `gdk_screen_get_resolution()` as 72 DPI (96 is assumed to be the default), leading to a `darktable.gui->dpi_factor` value of 0.75

That means that those GUI elements are actually shrinked, making it very hard for some of them to be used.

I have changed the macro `DT_PIXEL_APPLY_DPI` so that the computed dpi_factor cannot be less than 1.0 to avoid that shrinkage.

Some examples:

The panels of the main window can be collapsed/expanded by clicking in the border areas. The border size is set to be 10 pixels with respect to the dpi_factor, now resulting in only 7 pixels. The clickable area is even smaller, making it nearly impossible to hit that few pixels with the mouse. So I always used the shortcuts to expand/collapse.

before:
<img width="1792" alt="Bildschirmfoto 2023-12-08 um 17 37 59" src="https://github.com/darktable-org/darktable/assets/4083281/b21dcf1b-c084-449e-95a7-cbd1e4e14025">

after:
<img width="1792" alt="Bildschirmfoto 2023-12-08 um 17 44 06" src="https://github.com/darktable-org/darktable/assets/4083281/a6325ecc-279f-4efa-9720-984b5677a205">

The color indicators in the vectorscope are tiny.

before:
<img width="261" alt="Bildschirmfoto 2023-12-08 um 17 39 00" src="https://github.com/darktable-org/darktable/assets/4083281/b31d7352-1e1f-4658-b374-cf2d25a62704">

after:
<img width="265" alt="Bildschirmfoto 2023-12-08 um 17 44 26" src="https://github.com/darktable-org/darktable/assets/4083281/e6101706-2b59-48d1-866f-89baf3beac04">

The handles of drawn masks are tiny also.

before:
<img width="653" alt="Bildschirmfoto 2023-12-08 um 17 39 49" src="https://github.com/darktable-org/darktable/assets/4083281/6db16a08-6014-4d3d-a017-fdb43a6dabe8">

after:
<img width="644" alt="Bildschirmfoto 2023-12-08 um 17 44 53" src="https://github.com/darktable-org/darktable/assets/4083281/ad2d540b-c8f2-440f-be9e-4f5d73c7b0ab">

This PR does not change anything for system which report a screen resolution of 96 DPI or above.

It makes the usability MUCH better on my Mac.

2023-12-08 19:20 UTC, parafin commented
So is DPI totally bogus on your system? What is the physical size of your monitor and resolution in pixels?

2023-12-08 20:59 UTC, zisoft commented
@parafin thanks for looking into this!

I have now followed your proposal, can you please review?

2023-12-08 21:06 UTC, parafin approved these changes
Yes, that’s what I meant. Does it solve your issue?

While at it, I think it makes sense to just remove dt_osx_autoset_dpi function, since it now just confuses things.

2023-12-08 21:07 UTC, zisoft commented
> Yes, that’s what I meant. Does it solve your issue?

Yes, result is the same 

> I think it makes sense to just remove dt_osx_autoset_dpi function, since it now just confuses things.

Great, will do!

2023-12-08 21:16 UTC, zisoft commented
Unfortunately that does not solve the issue. Now the fonts in the modules are too big:

<img width="256" alt="Bildschirmfoto 2023-12-08 um 22 15 39" src="https://github.com/darktable-org/darktable/assets/4083281/7468e6f5-943d-4bbb-8020-60d847f57fe0">

2023-12-09 07:24 UTC, zisoft commented
The only solution that works so far is to set `arktable.gui->dpi_factor` to 1.0 for `GDK_WINDOWING_QUARTZ`, leaving the dpi as detected (72). 

@MStraeten can you please verify on your ARM64 system?

2023-12-09 08:02 UTC, MStraeten commented
before: 
![image](https://github.com/darktable-org/darktable/assets/39386816/5babff26-0258-4cd0-acff-0e1369c1f707)
after:
![image](https://github.com/darktable-org/darktable/assets/39386816/72b2b1a1-fec5-4fb1-8b35-601ab90a689d)

2023-12-09 08:16 UTC, parafin commented
How does that compare to how it looks on Linux with 72 or 96 DPI? This approach feels like a hack, that will produce Mac-specific GUI rendering (well, more Mac-specific than now), which means more Mac-specific bugs.
I think better understanding of how DPI works on Mac and why this change is needed might be beneficial.

2023-12-09 08:22 UTC, parafin commented
Isn’t what you want is to set dpi override to 96 through config (and remove the changes in this PR)? It might help with font sizes, but then dt will look different from other Mac apps. Your current change, I think, makes it different from Linux rendering.

2023-12-09 08:53 UTC, zisoft commented
> Isn’t what you want is to set dpi override to 96 through config (and remove the changes in this PR)?

That doesn't help. Setting the DPI to 96 leads to much bigger fonts all over the interface, but leaving the size of the controls (panel borders, color indicators, mask handles) as tiny as before. It is the dpi_factor causing the problems.

2023-12-09 08:58 UTC, parafin commented
But dpi_factor is DPI / 96, isn’t it? Why overriding DPI doesn’t change dpi_factor? It doesn’t make sense, maybe there’s a bug there.

2023-12-09 11:28 UTC, zisoft commented
Ok, I digged a bit deeper and can now summize:

On macOS, `gdk_screen_get_resolution()` gives a screen resolution of 72 DPI, giving a value of 0.75 for `darktable.gui->dpi_factor`. With this setting (out of the box for a fresh install of dt), the interface has well proportions with the fonts, but other elements such has mask handles, color indicators, ... are too small and hard to use because they are scaled down to 75% of their desired size.

The DPI setting can be overridden in the preferences. A setting of 96 gives a dpi_factor of 1.0 so the handles, indicators have their correct size but now the fonts in the interface are way too big. On my system I need to compensate that in the preferences by setting the font size to 8.

So there is indeed no change in the code required and this PR can be closed. But that leads to the problem that a new user is required to play with the preference settings to avoid the GUI elements being too small.

2023-12-09 18:34 UTC, parafin commented
How does currently macOS GUI rendering compares to Linux GUI  rendering if you set DPI manually through config?
My expectation is that they should be the same, more or less, at least regarding sizes.
If it’s true, then the code works as it should. The problem then is only that macOS has fixed DPI of 72 instead of using actual monitor DPI. But if you try to use real DPI (see commit I linked), dt looks strange regarding font size compared to other Mac apps (but not if you compare to Linux). Which seems to be true, given that you say that changing DPI and font size solves your issue.
Does dt use some system font size? That would explain the too big font when you force DPI to 96.
What you probably need then is to scale dpi_factor by 72/96 on Mac (or more clearly change the formula for dpi_factor from dpi / 96 on Linux to dpi / 72 on Mac. That change would be at least understandable (different DPI defaults between systems).

2023-12-09 20:08 UTC, zisoft commented
> change the formula for dpi_factor from dpi / 96 on Linux to dpi / 72 on Mac

That is indeed more clear than setting a fixed value of 1.0 for the dpi_factor.
Would you mind checking my latest commit?

2023-12-09 21:09 UTC, parafin requested changes
There is also dev->preview2.dpi_factor in darkroom.c (presumably it does affect something)

2023-12-10 12:55 UTC, zisoft commented
Yes, and it is in fact a code duplication.
I have separated that snippet into a function.

2023-12-11 08:37 UTC, parafin approved these changes

2023-12-12 08:16 UTC, TurboGit approved these changes
Thanks, I'll squash all the commits together.

2023-12-12 08:17 UTC, merged

2023-12-12 08:32 UTC, zisoft commented
For the release notes: 
Fixed a DPI scaling issue on macOS causing some GUI elements being rendered too small