New IOP Color Equalizer (II)
darktable-org/darktable pull request #16073
Opened 2024-01-09 17:07 UTC by jenshannoschwalm

The Color Equalizer module started for darktable and updated in Ansel (not yet merged on master).

This PR is a followup of #15926 after quite some testing and work.
Basically:

- use gaussian blurring all over. This leads to
  - less artifacts at "color borders"
  - no top/bottom leaking
  - more radial type of blurring
  - code could also be done with OpenCL
- minor refactoring using roi passed instead of dimensions
- works depending on roi scale so less differences while zooming in
- code style adopts
- removed temporary code and some comments from @aurelienpierre
- slightly changed defaults

2024-01-10 05:34 UTC, jenshannoschwalm commented
Latest commit a) enables guiding as default b) less digits in UI c) some renaming intending "what it means" instead of technical description d) first tooltips

2024-01-10 06:46 UTC, jenshannoschwalm commented
How to proceed? I would certainly want feedback about "quality" from you all pinging especially @flannelhead and @s7habo here.

Some comments from my side
1. I can not see any relevant artifacts due to high iso images or "strong effects" of prior modules in the pipe any more and would concider this module as an excellent addition to dt.
2. Any ideas of (better) naming and tooltips for the guiding tab? I thought of "blend" instead of "parameter" ...
3. Absolutely no intention from my side to write the docs, would love to see such from the original author :-) Hinted to the most relevant bugfix #16071 at the corresponding ansel pr hoping for some progress there too. (i think there is a remaining problem in the specific blurring algo introducing chroma bleeding from roi top<->bottom, one reason that code has been removed from dt implementation here) 
4. Would implement an OpenCL path (in spring so still possible for 4.8) after being merged, more field testing and possibly still some fixes

2024-01-10 08:15 UTC, TurboGit commented
I did some more testing this morning, the new default works for me really nicely in my images. The module is stable and really usable.

2024-01-10 19:23 UTC, KarlMagnusLarsson commented
I still have the same issue as before https://github.com/darktable-org/darktable/pull/15926#issuecomment-1874345084

Issue: I get grey artifacts in darkroom main view, when color equalizer is active, if a certain set of preconditions are fulfilled:

- Color equalizer module is active, ON, default state (no equalizer curve changes = flat).
- Preferences -> processing -> always use littleCMS 2 = ticked, ON
- Diffuse & Sharpen ON, activated using sharpen demosaicing AA filter preset.
- Sharpening module is ON, active using default values.
- Filmic rgb module is OFF, deactivated.

RAW file example: Canon 5D mk IV, CR2: 0Y8A7917.CR2
https://drive.google.com/drive/folders/18o-BrOp6fnk7zTHa2y6U3z2bl5NQ4LWz?usp=sharing

2024-01-10 20:59 UTC, jenshannoschwalm commented
MMh, i can't reproduce your issue - or i don't understand it exactly.

1. LCMS on/off doesn't change anything here
2. I see see "bleeding" of colors into grey areas but no greys where colors should be 
3. you are sure you compiled this pr on current master?

2024-01-10 22:09 UTC, KarlMagnusLarsson commented
I am on current master + PR. I can see bleeding of colors.

If I activate color balance rgb with preset basic colorfulness: standard, added to other modules in steps to reproduce, then I can toggle filmic rgb module, OFF without grey artifacts.

If I do not have color balance rgb active and then toggle filmic rgb module, OFF then this gives me grey areas as per https://github.com/darktable-org/darktable/pull/15926#issuecomment-1874345084 darkroom image example.

2024-01-10 22:39 UTC, jenshannoschwalm commented
@KarlMagnusLarsson could you provide a video ?

2024-01-10 23:11 UTC, KarlMagnusLarsson commented
@jenshannoschwalm , try this video:
https://drive.google.com/file/d/1Av9lAGIw34pfrENfnz4A97HlJrEp0yL7/view?usp=sharing

2024-01-10 23:30 UTC, jenshannoschwalm commented
> @jenshannoschwalm , try this video: https://drive.google.com/file/d/1Av9lAGIw34pfrENfnz4A97HlJrEp0yL7/view?usp=sharing

Ok i can clearly see what you mean. I had such issues while working on this module using the a) box blurring and b) non-fixed colorspace conversion. But not all in this pr code... don't know atm. I am pretty sure you tested also without the guiding option - such artifacts were only visible by using this but again, i can't reproduce here

2024-01-11 06:31 UTC, KarlMagnusLarsson commented
@jenshannoschwalm, can you confirm from my git commit number in upper left dt corner that I have all code?

I thought I had everything working using the old PR https://github.com/darktable-org/darktable/pull/15926. But that local copy was messy with old_PR + master + other PR.

2024-01-11 06:45 UTC, TurboGit commented
> can you confirm from my git commit number in upper left dt corner that I have all code?

No we can't really. As you've merged the PR into master the SHA-1 is probably unique for you.

2024-01-12 08:51 UTC, jenshannoschwalm commented
Only remaining issue for me atm is, i can't sort out how to bind the sliders to midi events properly. Always fall back to saturation page.

Otherwise
1. might want to do better tooltips
2. maybe some gui stuff would like renaming
3. no stability issues
4. not completely sure about sane defaults yet. After fixing some colorspace conversion maths the "bleeding" effect is well under control and with parameter defaults plus guiding enabled the visual difference between module enabled / disabled is pretty small.

Again, how to proceed? We certainly need/want more "experienced user" feedback to a) get notice about remaining issues to be fixed and b) decide if we want this module to be included in dt or if we don't.

2024-01-12 09:37 UTC, SoupyGit commented
I probably don't count as "experienced user", but to answer (b) I vote yes, if it produces nicer results than color zones. That may be subjective, but is worth comparing. What do you think? I will test when in master.

2024-01-12 10:20 UTC, TurboGit commented
> i can't sort out how to bind the sliders to midi events properly. Always fall back to saturation page.

The solution is to give a unique name to all sliders, for example:

```
  dt_bauhaus_widget_set_label(g->sat_sliders[3], N_("saturation"), N_("green"));
  dt_bauhaus_widget_set_label(g->hue_sliders[3], N_("hue"), N_("green"));
  ...
```

With the above you should be able to have the green on hue and saturation working.

2024-01-12 10:38 UTC, TurboGit commented
@jenshannoschwalm : How I see things...

> Again, how to proceed?

First fix the slider issue with MIDI mapping. I can help if needed, but I suppose the solution above should work.

> We certainly need/want more "experienced user" feedback to 
> a) get notice about remaining issues to be fixed and 

Right, and this probably after first merging in master as many experienced users are using the nightly builds and not building themselves.
 
> b) decide if we want this module to be included in dt or if we don't.

Frankly, this is not a question to me :) We want this module in dt, especially with the huge amount of effort you've done to make it working properly.

2024-01-12 10:48 UTC, jenshannoschwalm commented
I will add the midi support.

2024-01-12 11:20 UTC, jenshannoschwalm commented
@TurboGit - done the MIDI bindings and included reference bindings for the loupedeck+ :-)

2024-01-12 11:48 UTC, jenshannoschwalm commented
> Frankly, this is not a question to me :) We want this module in dt, especially with the huge amount of effort you've done to make it working properly.

Most of the work already paid off by fixing things in other parts of the code :-)

Plus - even if i now understand main parts of the code fairly well - there is still some color-magic involved which i simply don't understand. So if we have bigger issues than we would like to have - i might run into limits!

But overall, i am pleased a lot about current status.

2024-01-12 12:40 UTC, TurboGit commented on src/iop/colorequal.c
> +  dt_bauhaus_widget_set_label(g->bright_sliders[0], N_("bright"), N_("red"));
I would use `brightness` here instead of `bright` (name consistency with the notebook tab).

2024-01-12 13:01 UTC, TurboGit requested changes
Some more things to do:
- Add a way to resize the graph (ctrl+alt+scroll) as for other graphs like color zone
- Should we add interaction with the graph directly?

We can plan this after merging this. No problem, and again I can help.

2024-01-12 13:09 UTC, TurboGit commented
Also, let's reorder the tab, we have multiple choices:
- HSL
- Or like in Color Zones : LCH

But here `SHB` looks awkward, no?

2024-01-12 13:15 UTC, TurboGit commented
We also need slider control (triangle) filled not just the edge stroke.

2024-01-12 13:59 UTC, jenshannoschwalm commented
> But here `SHB` looks awkward, no?

Indeed :-) Fixed that to HSL

2024-01-12 14:02 UTC, jenshannoschwalm commented
About all this gtk stuff like triangles, area enlarging, direct graph interaction ... i would certainly love to get around this in a safe distance :-)

Also - how to let the module name start with an uppercase?

Otherwise, good to me now.

2024-01-12 14:12 UTC, jenshannoschwalm commented
> I'll try to do that in the coming weeks then.

Very nice. Would love to concentrate on a) late D65 color and b) the gimp interface. Currently b) is prio to keep gimp-is-broken as short as possible.

2024-01-12 18:55 UTC, TurboGit commented
Closing, finally I have done the interactive & resizing graph. See #16089.

2024-01-12 18:55 UTC, closed without merging