CI: bump to XCode 16
darktable-org/darktable pull request #17509
Opened 2024-09-21 22:54 UTC by kmilos

2024-09-22 09:13 UTC, zisoft commented
Please don't raise the deployment target. We want to support the oldest OS version with the newest Xcode version.

2024-09-22 09:15 UTC, zisoft requested changes

2024-09-22 09:15 UTC, zisoft commented on .github/workflows/nightly.yml
> -          - { os: macos-14, xcode: 15.4, deployment: 14.0 } # LLVM16, arm64
deployment should be left at 14.0

2024-09-22 09:15 UTC, zisoft commented on .github/workflows/nightly.yml
> +            The macOS `*-x86_64.dmg` package requires at least macOS 13.5 (Ventura), the `*-arm64.dmg` package requires at least macOS 14.5 (Sonoma).
likewise

2024-09-22 10:27 UTC, zisoft commented
oh, sorry, my fault.
Xcode 16 requires macOS 14.5, so all good!

2024-09-22 10:29 UTC, zisoft approved these changes

2024-09-23 17:17 UTC, MStraeten commented
be careful with xcode16 - highway as a dependency for some darktable dependencies won’t build due to a clang issue …
see https://github.com/google/highway/issues/2317

2024-09-26 08:08 UTC, zisoft commented
For now we have no pressure to bump the Xcode version.
We will drop support for macOS 13 with the winter release 2025 when macOS 16 will be released.

2024-09-26 08:09 UTC, closed without merging

2024-09-30 16:56 UTC, zisoft commented
Thanks!
So for the nightly builds and my release builds we will stay on the macos-14 runner with Xcode 15 to ensure the deployment target of macOS 14.

For the CI we can use the next macos-15 runner with Xcode 16.