Better mixing of Shadows & Highlights fixing negative L* values increasing in brightness
darktable-org/darktable pull request #5668
Opened 2020-06-30 00:31 UTC by hatsunearu

Negative L* values are invalid to begin with, and right now when there is a negative mask and a negative input value, they multiply together to form a positive value, which caused weird behavior, causing things that are meant to be darker to become brighter. Fixes #5625.

Not sure if this is the best way to do it, but since math on negative L* values are invalid to begin with, I'd say we just use this method to be "less wrong".

2020-09-17 13:54 UTC, TurboGit commented
One thing about this is that changing process means that old edits are not preserved. I'm not against a better algorithm (didn't check it BTW) but we really want to keep previous edit intact meaning that we need to keep old algorithm for old edits and introduce a new one. This means adding a version field in params struct and an entry into legacy_params() to migrate from previous version.

2020-09-17 13:55 UTC, TurboGit requested changes
support legacy params.

2020-10-09 15:07 UTC, TurboGit commented
Any news on this ?

2020-10-13 04:06 UTC, hatsunearu commented
Hi sorry, I'll take a look at this again once I get some more time...

2021-05-06 07:56 UTC, closed without merging