export lib: add ability to define export size from print size × resolution
darktable-org/darktable pull request #6336
Opened 2020-09-19 15:40 UTC by aurelienpierre

Long asked feature.
![Screenshot_20200919_173800](https://user-images.githubusercontent.com/2779157/93670884-ed3a0200-fa9e-11ea-93e1-172ce063e078.png)
![Screenshot_20200919_173746](https://user-images.githubusercontent.com/2779157/93670886-ef03c580-fa9e-11ea-9c84-ae76a2fab739.png)
@elstoc I have a problem with the `insert_text_handler()` function, it doesn't really work with floating point input, especially when we try to erase numbers, the cursor gets repositionned at the beginning. I don't really get what happens there, could you have a look ? Thanks !

2020-09-21 06:26 UTC, TurboGit commented
The control of the entry is strange. For example, I select cm I double click on the first entry, I want to enter 21 and in fact the entry contains 210. The 0 is added automatically and only if I type the dot (or coma) I have 21.0. This is the only entry working this way in dt!

2020-09-21 06:26 UTC, TurboGit requested changes
Entry control strange behavior.

2020-09-21 06:29 UTC, TurboGit commented
Note also that we have two competing PR (see #6079) on the export module. I suppose this one will be in first and the other will have to be reworked based in this one.

2020-09-22 10:02 UTC, aurelienpierre commented
> The control of the entry is strange. For example, I select cm I double click on the first entry, I want to enter 21 and in fact the entry contains 210. The 0 is added automatically and only if I type the dot (or coma) I have 21.0. This is the only entry working this way in dt!

Yes, there is a problem with the text entry and numbers, that is hidden with integers (in the px entries).

This issue comes from the fact that the entry is text, but the validation layer forces conversion to float then back to text with 3 decimals. As long as you input numbers, the entry is treated as integers and the numbers are inserted before the 0 if any. Only inputting a . or , will force-set the numbers position.

I'm not sure what the best option would be. Text entries are not really suited for that work, but the spin buttons we had earlier seem too ugly. 

> Note also that we have two competing PR (see #6079) on the export module. I suppose this one will be in first and the other will have to be reworked based in this one.

I'm also in process of removing all the direct read-write to config file that makes a mess of this module. I discovered that, with this PR, current px sizes are not properly saved to config. But the incessant read-write to config make it impossible to track. So I have 3 functions, one that reads config at init time and save params to a struct, one that sanitizes the values, and one that writes the config at cleanup time, and everything else reads or writes in the params. That would also make the presets blobs encoding and decoding much easier… (notice that resetting the module is broken currently).

2020-09-22 10:27 UTC, elstoc commented
>  but the spin buttons we had earlier seem too ugly

Agreed, though the primary reason for their removal was the large minimum width the +/- buttons imposed on the right panel. Keeping the spin buttons with _three_ entries will be worse for that. Unfortunately GTK doesn't give us many options here :(

2020-09-22 10:58 UTC, TurboGit commented
> I'm also in process of removing all the direct read-write to config file that makes a mess of this module. I discovered that, with this PR, current px sizes are not properly saved to config. But the incessant read-write to config make it impossible to track.

Beware that those configs are used because using for example Ctrl+E from darkrroom does not give access to the export libs parameters.

2020-09-22 10:59 UTC, TurboGit commented
> This issue comes from the fact that the entry is text, but the validation layer forces conversion

Maybe just remove the validation for now. We can validate when leaving the entry.

2020-10-05 09:47 UTC, TurboGit commented
@aurelienpierre : any update on this, there is another PR waiting to be worked on top of this one and I want to avoid squashing too many things at the last minute (we are close to 1 month from code freeze) :)

2020-10-05 12:32 UTC, aurelienpierre commented
@TurboGit this lib is a clusterfuck of bad things, it turns out to be much more work than expected so I'm not sure I will be able to finish it before code freeze. Don't wait for me :-)

2020-10-06 19:23 UTC, TurboGit commented
Closing this PR, I'm working on a new one on top of this to fix the remaining issues.

2020-10-06 19:23 UTC, closed without merging