Update or remove links pointing to the redmine wiki in the README
darktable-org/darktable pull request #6400
Opened 2020-09-28 19:21 UTC by amousset

2020-09-28 21:04 UTC, TurboGit commented on README.md
> +This process might be tedious but you only need to do it once. See this (partly outdated)
I'm not ok with the "partly outdated" here. I agree that it is, but this should not be part of the README.md we could add a notes on the Wiki itself maybe?

2020-09-28 21:05 UTC, TurboGit requested changes
No need to state that the wiki is outdated.

2020-09-28 21:13 UTC, amousset commented
Indeed. BTW I also started actually updating the page (general build instructions and instructions for Fedora).

2020-09-29 06:54 UTC, TurboGit approved these changes
Thanks !

2020-09-29 06:55 UTC, merged