[prefs] visually highlight changed prefs
darktable-org/darktable pull request #6406
Opened 2020-09-29 18:57 UTC by johnny-bit

I haven't had the best idea here, but hey - at least it works ;)

I'm open to recommendations on making this better!

Fixes #6176 :)

2020-09-29 22:36 UTC, rgo commented
Hi, could you add an span or something with a class(instead of the b tag) ? And then add the style using the css. 
Thanks for your time!

2020-09-30 11:04 UTC, TurboGit requested changes
Yep, better to use the CSS here. I would try setting a specific widget name for changed label and add a corresponding CSS rule.

2020-09-30 11:05 UTC, TurboGit commented on src/control/conf.c
> +gboolean dt_conf_is_default(const char *key)
This would be rewritten using dt_confgen_get() from my po/conf_gen branch.

2020-09-30 11:14 UTC, johnny-bit commented
Yeah, thought so too... Will check this after your PR lands.

2020-10-01 21:14 UTC, TurboGit commented
PR is merged now.

2020-10-01 21:29 UTC, johnny-bit commented
I think I'll rework this PR totally now :)

2020-10-02 21:10 UTC, johnny-bit commented
I'm closing this one in favour of  #6429 - hope new PR makes more sense :)

2020-10-02 21:10 UTC, closed without merging