Implement styles dialog when exporting style[s].
darktable-org/darktable pull request #6670
Opened 2020-10-29 03:16 UTC by darkelectron

This implements a dialog for overwriting existing style(s) when exporting. It uses a similar dialog to copy/move dialog from file managers.

Hey, @junkyardsparkle.

2020-10-29 08:23 UTC, junkyardsparkle commented
I only did quick test, but seems to be working here, thanks! One thing: "Applying this option" should read "Apply this option".

2020-10-29 09:54 UTC, darkelectron commented
Thanks, fixed now.

2020-10-29 10:27 UTC, TurboGit requested changes
Some translations issues.

Also this dialog should be controlled by a security option. Maybe reusing the "ask before deleting a style" ?

Conf key is : `plugins/lighttable/style/ask_before_delete_style`

2020-10-29 10:27 UTC, TurboGit commented on src/libs/styles.c
> +          sprintf(overwrite_str, "style `%s' already exists.\ndo you want to overwrite existing style?\n", (char*)style->data);
this string must be translatable

2020-10-29 10:27 UTC, TurboGit commented on src/libs/styles.c
> +          GtkWidget *dialog_overwrite_export = gtk_dialog_new_with_buttons("overwrite style?", GTK_WINDOW(win), GTK_DIALOG_DESTROY_WITH_PARENT,
string must be translatate

2020-10-29 10:27 UTC, TurboGit commented on src/libs/styles.c
> +          GtkWidget *overwrite_dialog_check_button = gtk_check_button_new_with_label("apply this option to all existing styles");
string should be translatable

2020-10-29 10:29 UTC, TurboGit commented on src/libs/styles.c
> +  gtk_entry_set_placeholder_text(GTK_ENTRY(d->entry), _("filter style names"));
Also you want to rebase  your branch on top of current master as this change is already committed.

2020-10-29 12:06 UTC, darkelectron commented
> Some translations issues.

For the translations, does that mean using `ngettext`.

2020-10-29 12:32 UTC, TurboGit commented
> > Some translations issues.
> 
> For the translations, does that mean using `ngettext`.

No, just `_(" ... ")`

2020-11-02 13:38 UTC, TurboGit commented on src/libs/styles.c
> +            GtkWidget *label = gtk_label_new(_(overwrite_str));
the `_(...)` should be above around the real string, not the variable.

2020-11-02 13:39 UTC, TurboGit requested changes
One more translation fix needed.

2020-11-02 18:21 UTC, TurboGit commented
Looks good to me now. Thanks !

2020-11-02 18:21 UTC, merged