ctrl+click iop reset button to apply auto-presets
darktable-org/darktable pull request #6687
Opened 2020-10-30 23:55 UTC by elstoc

`Ctrl+click` on an iop module reset button will reapply any automatic
presets to that module. If no automatic presets are found, the module
parameters will be reset to their default values (i.e. same as
left-clicking on the reset button).

Resolves #6682

2020-10-31 10:24 UTC, dterrahe commented
Great additional functionality.

Looking at the additional work required to achieve this makes me wonder if there's room for a little refactoring here. I always worry when a block of mostly/partly duplicate code appears, especially in a different file, that future changes/fixes won't get applied here. Then it could start to diverge from what happens originally at import, or get buggy.

2020-10-31 10:37 UTC, elstoc commented
> makes me wonder if there's room for a little refactoring here

I would tend to agree with you and I did consider it, but the techniques for applying the presets in the two sections of code where this appears are so different that I'm not sure I know the best way to go about it. The other place this exists performs a direct insert into the history and sits alongside other bits of code that auto-enable modules.

So I would prefer to merge this for 3.4 (assuming it's not too late) since this change is fairly low risk, and consider refactor for the next release.

2020-11-01 17:29 UTC, TurboGit commented
> So I would prefer to merge this for 3.4 (assuming it's not too late) since this change is fairly low risk, and consider refactor for the next release.

I'm always uneasy about this, but I'm ok to merge in 3.4 just be sure to open an issue for the refactoring otherwise it won't happen I fear :)

2020-11-01 17:31 UTC, TurboGit requested changes
A memory leak to fix.

2020-11-01 17:31 UTC, TurboGit commented on src/gui/presets.c
> +  gchar *workflow = dt_conf_get_string("plugins/darkroom/workflow");
should be freed at some point.

2020-11-01 17:34 UTC, elstoc commented
> A memory leak to fix.

Fixed

>  just be sure to open an issue for the refactoring

Will do

2020-11-01 21:38 UTC, TurboGit approved these changes
Works for me now, thanks !

2020-11-01 21:38 UTC, merged