map: scrolling over an images group scrolls the images of the group
darktable-org/darktable pull request #6834
Opened 2020-11-10 14:42 UTC by phweyland

some related changes:
- scrolling over an images group scrolls the images of the group
- fixes dnd of a group of images (only the first was moved since the grouping function)
- dnd of a group shows the next image while the first one is dragged

2020-11-10 16:43 UTC, phweyland commented
Good for review.

2020-11-10 17:17 UTC, TurboGit commented
Not sure it is related to this PR, but I have set the minimum of image for a group to 5. But only after having dnd 6 images close to each others I had a group created.

>     * fixes dnd of a group of images (only the first was moved since the grouping function)

Still the case for me.

BTW, another enhancement that could be great is to show the locations (circle or square) when moving them. It is hard otherwise to place it at the proper location.

2020-11-10 17:19 UTC, TurboGit requested changes
Code looks ok, just a minor comment.

2020-11-10 17:19 UTC, TurboGit commented on src/views/map.c
> +typedef struct geo_position_t
dt_get_position_t

2020-11-10 17:19 UTC, TurboGit commented on src/views/map.c
> +} geo_position_t;
likewise

2020-11-10 17:45 UTC, phweyland commented on src/views/map.c
> +} geo_position_t;
Done!

2020-11-10 17:52 UTC, phweyland commented
> Not sure it is related to this PR, but I have set the minimum of image for a group to 5. But only after having dnd 6 images close to each others I had a group created.

Hummm. I've already checked this issue but I haven't found yet why. I don't give up.



> > ```
> > * fixes dnd of a group of images (only the first was moved since the grouping function)
> > ```
> 
> 
> Still the case for me.

It works well for me. Do you use shift-click ? Do you release the shift before the left click ?




> BTW, another enhancement that could be great is to show the locations (circle or square) when moving them. It is hard otherwise to place it at the proper location.

The flying pixbuf has no transparency. This seems to be a known issue of cairo pixbuf. So I've let the cross but it is really not ideal.

2020-11-10 17:55 UTC, phweyland commented
> The flying pixbuf has no transparency. This seems to be a known issue of cairo pixbuf. So I've let the cross but it is really not ideal.

If you have any idea to solve this let me know. The dnd from filmstrip to map suffers the same issue.

2020-11-10 17:55 UTC, TurboGit commented
> It works well for me. Do you use shift-click ? Do you release the shift before the left click ?

Oh I see, you need shift-click and you need to release shift before ! Not really nice :( Could all this be just a shift-click and whatever is done when releasing ?

2020-11-10 17:56 UTC, phweyland commented
> > It works well for me. Do you use shift-click ? Do you release the shift before the left click ?
> 
> Oh I see, you need shift-click and you need to release shift before ! Not really nice :( Could all this be just a shift-click and whatever is done when releasing ?

Also an old behaviour. I look at it and tell you.

2020-11-10 21:50 UTC, phweyland commented
Just remains the pixbuf transparency.

2020-11-11 12:18 UTC, phweyland commented
I've found a way to control transparency differently (I don't know if that would work) but I cannot compile it:

      GdkPixmap *pixmap;
      GdkBitmap *mask;
      gdk_pixbuf_render_pixmap_and_mask(cross, &pixmap, &mask, 1);
      gtk_drag_set_icon_pixmap(context, NULL, pixmap, mask,
                               DT_PIXEL_APPLY_DPI(cross_size),
                               DT_PIXEL_APPLY_DPI(cross_size)); 

GdkPixmap, GdkBitmap, gdk_pixbuf_render_pixmap_and_mask and gtk_drag_set_icon_pixmap are unknown ...
Any idea on this ?

2020-11-11 12:53 UTC, parafin commented
I'm not sure what exactly you are trying to achieve here, but you may want to check that your solution works on non-compositing window managers (see #5438 and #5382 for context).

2020-11-11 12:59 UTC, phweyland commented
> I'm not sure what exactly you are trying to achieve here, but you may want to check that your solution works on non-compositing window managers (see #5438 and #5382 for context).

Thanks for jumping in.
Currently the icon (pixbuf) on drag and drop doesn't respect the alpha channel. This is not an issue for plain image but it is for an empty circle or rectangle.
I'll look at your links.

2020-11-11 17:52 UTC, phweyland commented
@parafin, yes, css was the way to go. Thanks !

2020-11-11 18:26 UTC, phweyland commented
Travis is happy. So I am.

2020-11-11 19:14 UTC, TurboGit commented
@phweyland : the circle & rectangle when dragged are not adjusted for the ratio so a circle becomes an ellipse.

2020-11-11 19:15 UTC, TurboGit commented
Apart from that, the shift-click and min number of image for creating a group is working fine on my side.

2020-11-11 19:21 UTC, phweyland commented
> @phweyland : the circle & rectangle when dragged are not adjusted for the ratio so a circle becomes an ellipse.

I've also a slight difference between the original and the dragged one, but it is very small. 
Let me check.

2020-11-11 20:06 UTC, phweyland commented
I've forgotten to check the most important, i.e. the Dieppe area, sorry ... :)
Well done. Thanks.

2020-11-11 20:19 UTC, TurboGit commented
Ah ah ! Dieppe is THE place to check:) note that I was born there but I live around Paris now... Even if I would prefer not!

2020-11-11 20:54 UTC, TurboGit commented
Perfect for me now, thanks !

2020-11-11 20:54 UTC, merged

2020-11-11 21:40 UTC, phweyland commented
I've seen some discussions about docs. Where I should update them now ?

2020-11-12 06:08 UTC, TurboGit commented
On the same documentation as before until 3.4. After that we will migrate to the new support.