don't accelerate hidden sliders/combos
darktable-org/darktable pull request #7078
Opened 2020-11-26 10:39 UTC by dterrahe

In response to https://github.com/darktable-org/darktable/issues/7037#issuecomment-732369258

This will not disable accelerators for widgets that are on a different (not the active) notebook tab. I think this is desirable behavior.

For dynamic accelerators, this just means pressing the key does nothing (it doesn't switch to the "dynamic" mode) so if you then scroll, it will zoom (normal scroll key behavior). Alternatively, the mode can be changed but the actual scroll ignored; in that case the hint (at top of screen) will be misleading. So we'd have to do both; amend the hint (to say widget is hidden/inactive) _and_ ignore, rather than passthrough, the scroll. Then you might want the hint to contain an explanation of _why_ the widget is hidden and _then_ you've created a lot of work...

2020-11-26 11:26 UTC, johnny-bit commented
Does that work with white balance and R/G/B (not emerald) sliders when expander is collapsed?

2020-11-26 11:38 UTC, dterrahe commented
Afk.

Probably/maybe not. The "correct" approach there is to expand them when moved via accelerator, because they're just _hidden_, not really _disabled_, imho.

2020-11-26 12:41 UTC, jenshannoschwalm commented
Yeah. A sort of defensive solution but a safe one :-) Thanks for looking into this.

2020-11-26 18:24 UTC, TurboGit requested changes
This breaks dynamic accels. Just assign E to exposure dynamic accel. Press E and scoll the darkroom is zooming instead of changing the exposure.

2020-11-26 18:33 UTC, dterrahe commented
You're right, this needs a more careful approach. Using _get_visible instead of _is_ probably doesn't give the same breakage, but might also not disable some _really_ hidden sliders.

Tbh i didn't think this was needed for 3.4. Changing a value that is hidden and not used isn't _pretty_, but it shouldn't cause major issues and as far as i know this is not a regression.

2020-11-27 09:25 UTC, dterrahe commented
Second attempt.

There are two cases (that I can think of) where this would not work:
1. If a widget is hidden by hiding an outer box that contains an inner box that contains the widget. To catch this, the parent's parent could be checked as well, but...
2. if a widget (slider/combo) is directly set as the module's top-level widget. In that case, when the module is closed/not shown in the modulegroup, the widget would not respond to shortcuts because this code would think it was deliberately hidden.

I think both cases are hypothetical, at least I'm not aware of any instances, so I'm not sure if it is necessary to make the code more robust (and slower), by adding the extra parent and by comparing the widget and parent to widget->module->widget before checking if _their_ parent is visible. There might also be side-effects to that that I'm not considering. @TurboGit what do you think?

2020-11-29 16:44 UTC, TurboGit commented
> There might also be side-effects to that that I'm not considering. @TurboGit what do you think?

The new implementation seems ok to me. I cannot thinks of a case where this would _actually_ not work. So let's merge this now, I'm confident that this will fill 99.9999% of the needs :) Thanks.

2020-11-29 16:44 UTC, merged