refactor: move dwt_denoise into common/dwt.c
darktable-org/darktable pull request #7194
Opened 2020-12-05 01:41 UTC by ralfbrown

...where it belongs and would have been originally if not for another pending PR on dwt.c.
Also put dwt_interleave_rows into dwt.h where it will be available to filmicrgb.c for an upcoming PR.

Finally, refactor the X-Trans codepath in rawdenoise.c to use the new common function for computing noise thresholds.

2020-12-05 10:40 UTC, TurboGit commented on src/iop/rawdenoise.c
> +  float *const fimg = dt_alloc_sse_ps((size_t)size * 4);
dt_alloc_sse_ps -> dt_alloc_align_float.

2020-12-05 10:41 UTC, TurboGit commented on src/common/dwt.c
> +  float *const details = dt_alloc_sse_ps(2 * width * height);
dt_alloc_align_float

2020-12-05 10:41 UTC, TurboGit requested changes
Minor clean-up for float alloc. TIA.

2020-12-05 15:23 UTC, ralfbrown commented
Done.

2020-12-06 14:46 UTC, TurboGit commented
@ralfbrown  : rawdenoise conflcts due to merging your other PR.

2020-12-06 16:13 UTC, ralfbrown commented
Rebased, and I've also switched over the X-Trans code path to the new common code.  X-Trans now shows 5.3x speedup single-threaded, 1.8x at 8 threads, but only 1.6 percent speedup at 32 threads because the memory bus is being saturated.  Output verified against the updated test 0068.

2020-12-06 16:58 UTC, TurboGit approved these changes
Thanks ! All good on my side.

2020-12-06 16:58 UTC, merged