add a new colorbalancergb module
darktable-org/darktable pull request #7347
Opened 2020-12-18 03:29 UTC by aurelienpierre

## Why ?

The current color balance works internally in RGB but needs Lab input and output, so it triggers up to 4 useless RGB -> Lab -> RGB conversions. Plus, as an Lab module, blending and masking happen in Lab too.

## So ?

1. We take this opportunity to use a special purpose RGB space, and its connected Yrg space, designed by Filmlight for artistic color grading : https://doi.org/10.2352/issn.2169-2629.2019.27.38 But I had to fix some mistakes (the color conversion in the paper doesn't roundtrip) and optimize the code for performance (linear operations reordered to allow factorization and spare 4 useless matrix products). 
2. Input and output of the module are gamut-mapped. We compute a LUT of the gamut boundaries of the working RGB space (Rec2020 by default) projected in Ych (luminance, chroma, hue) derivated from Yrg, and scale the chroma setting with the maximum chroma allowed at current hue, plus clip the chroma at the maximum allowed at the end. For example:
![image](https://user-images.githubusercontent.com/2779157/102569215-556fa280-40e5-11eb-933e-1152168a93c7.png)
![image](https://user-images.githubusercontent.com/2779157/102569582-00805c00-40e6-11eb-8933-4019c36e9622.png)
We see on these graphs that the usual way of uniformingly pushing chroma is going to make cyan and magenta escape gamut much quicker than green or red. So we need a correction that takes the boundaries into account, and that's what is done here.

## Prerequisite

Before going any further, reading of https://munsell.com/color-blog/difference-chroma-saturation/ is advised to catch the difference between chroma and saturation. Chroma is colorfulness at same luminance, saturation is colorfulness + luminance. That's confusing because 99% of image processing applications call "saturation" a chroma adjustment (as did the previous color balance). Saturation actually helps getting deeper colours because they don't wash to grey but to white, which is more like painting.

## How to use

As usualy, a lot of info is hidden in tooltips.

First tab is the master/general correction:
![Screenshot_20201218_040307](https://user-images.githubusercontent.com/2779157/102569547-f52d3080-40e5-11eb-8c4c-5e93fcd2e7fb.png)

Saturation can be corrected through a combination of an offset (that is, an absolute correction that doesn't care about the original saturation) and a factor (a relative correction that is proportional to the input saturation). The saturation adjustment gives deeper and more natural color than the chroma.

Hues can be rotated to practice despilling (removing a parasite light casting wrong hue on some object or subject) : https://learn.foundry.com/nuke/12.1/content/comp_environment/keying_with_chromakeyer/despill_controls.html

Then, the chroma can be adjusted depending on luminance. It's the same logic as the current color balance in slope-offset-power mode. People who are used to RGB tone curves applied on decorrelated channels can reproduce a highlights desaturation without the hue shift as a side effect. The midtones chroma is close to what usually is called vibrance in many pieces of software.

The second tab deals with the actual balancing:
![Screenshot_20201218_041105](https://user-images.githubusercontent.com/2779157/102570140-15112400-40e7-11eb-9321-0cebaee2c972.png)

The global adjustment is the exact equivalent of today's offset: it raises the whole range by some offset. The highlights adjustment with the weight pushed to 100% is the exact equivalent of today's slope: it raises values proportionaly to their input values. The midtones adjustment is the exact equivalent to today's power or gamma: it applies a power function.

The shadows adjustment is sort-of similar in logic to today's lift, feature-wise, although the algo is tuned for scene-referred editing while the lift assumes bounded signals.

Remember all the settings have an impact on the whole tonal range, but each one has more weight on some part of that range. For this reason, this color balance introduces a weighting factor, that let users choose how wide or narrow they want to define their shadows/midtones/highlights.

## Some notes

With so many parameters, you need to dive into that module with some color science knowledge and have a theoritical understanding of what you are doing. Don't expect to just fiddle with the sliders and grasp what's going on. For resources, I can only recommend https://play.google.com/books/reader?id=kDcdAgAAQBAJ (672 pages of just color balancing), or https://www.youtube.com/watch?v=CaKhcCgazP0 for a basic intro. This module is designed to allow great control with minimal side effects provided you know what you are doing. Colorist is a full-time job in the cinema industry, some people get their income only from using that kind of module.

## Samples

(Before/After)
![P1010263_01](https://user-images.githubusercontent.com/2779157/102570858-90bfa080-40e8-11eb-9561-01b1295805f4.jpg)
![P1010263](https://user-images.githubusercontent.com/2779157/102570909-a765f780-40e8-11eb-80c8-1aacfa0db62a.jpg)

![Demi-marathon Hadrien-0044-_DSC0487_03](https://user-images.githubusercontent.com/2779157/102570955-bf3d7b80-40e8-11eb-952a-4580f43995e1.jpg)
![Demi-marathon Hadrien-0044-_DSC0487_02](https://user-images.githubusercontent.com/2779157/102570944-b8af0400-40e8-11eb-8a54-302c7f942a27.jpg)

![Demi-marathon Hadrien-0018-_DSC0461_04](https://user-images.githubusercontent.com/2779157/102571368-a08bb480-40e9-11eb-89e4-d7e55b75c308.jpg)
![Demi-marathon Hadrien-0018-_DSC0461_03](https://user-images.githubusercontent.com/2779157/102571251-61f5fa00-40e9-11eb-9a3e-14fca4bfe9b9.jpg)

2020-12-18 09:27 UTC, GLLM commented
Aurélien has struck again ...  and along with that, the amount of literature I'm supposed to read has increased yet again. I sure won't be able to keep up :-)

Thanks for the relentless work @aurelienpierre !

2020-12-20 04:24 UTC, todd-prior commented
@aurelienpierre ...I have no doubt that you will achieve a mathematically and technically superior solution. The challenge will be to make it not be one of those 80% of the people use 20% of its potential. I have played with a lot of software and stumbled on to Picture WIndow Pro which is not opensource but it is free. It is the product of Jonathan Sachs one of the creators of Lotus 1-2-3...it has a quirky interface but lots of powerful modules and to date the selective color correction control he uses is so easy and intuitive. ...its a rotated cube with the primary colors on the vertices of the cube and the white point at the nearest one in the middle. It makes it so easy to select any color in the image a move it with a visual indicator of the shift. Some additional features as well but my point is it is intuitive...so if you can marry your technical expertise with something like this for application you will IMO hit a grand slam....great to see how you push the boundries.....section 2 of this link shows a bit of what I am talking about but you would likely have to try it to see what I am talking about...its sort of like a 3D color wheel....  https://oldgoodlight.blogspot.com/p/blog-page.html

2020-12-20 14:41 UTC, jade-nl commented
You mention on pixls that this is R&D and needs testing. I'm assuming that this means that externals like me can give it a go.

I've been trying to merge and build this one and I'm running into the following while building:
```

Scanning dependencies of target exr
[ 94%] Linking C shared module libppm.so
[ 94%] Building CXX object lib/darktable/plugins/imageio/format/CMakeFiles/exr.dir/exr.cc.o
[ 94%] Linking C shared module libnegadoctor.so
[ 94%] Built target ppm
[ 94%] Linking C shared module libpng.so
In file included from /home/jade/.local/git/darktable/build/lib/darktable/plugins/introspection_colorbalancergb.c:156:
/home/jade/.local/git/darktable/src/iop/colorbalancergb.c: In function 'commit_params':
/home/jade/.local/git/darktable/src/iop/colorbalancergb.c:424:64: error: 'LUT' is predetermined 'shared' for 'shared'
       dt_omp_firstprivate(input_matrix) schedule(static) shared(LUT)
                                                                ^
compilation terminated due to -Wfatal-errors.
make[2]: *** [lib/darktable/plugins/CMakeFiles/colorbalancergb.dir/build.make:69: lib/darktable/plugins/CMakeFiles/colorbalancergb.dir/introspection_colorbalancergb.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:7574: lib/darktable/plugins/CMakeFiles/colorbalancergb.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

Did not have any issues merging your branches into master and building before. Just in case:

**Platform**
* darktable        : 3.5.0+55 g635121134
* OpenCL installed : Yes (nvidia-opencl-common 450.80.02-1)
* OpenCL activated : Yes
* Graphics card    : GeForce RTX 2060 SUPER 7979 MiB
* Graphics driver  : nvidia (450.80.02)
* OS               : Linux (kernel 5.8.10-1)
* Distro           : Debian Buster (rel. 10.7)
* Processor        : AMD Ryzen 5 3600 6-Core Processor

**Additional context**
* Self compiled : Yes.
* Compilers     : gcc 8.3.0
* Cmake         : 3.13.4
* Gtk           : 3.24.5-1
* Glib          : 2.58.3-2
* Sqlite        : 3.27.2
* Optimization  : None

2020-12-20 14:53 UTC, johnny-bit commented
Eh,CI has GCC9 & 10 yet we're thwarted by gcc8 :/

Generic question: which OSes versions should we "support" as a baseline? Ubuntu 18.04 LTS?

2020-12-20 15:11 UTC, jade-nl commented
I just switched from gcc 8.3.0 to clang 10.0.1 and it now builds and runs nicely indeed....

My distro, Debian (10.7), is the most resent, stable one available (not counting testing/development). It does not yet have gcc 9 (also not as a backported option).

2020-12-20 15:24 UTC, aurelienpierre commented
> Some additional features as well but my point is it is intuitive...so if you can marry your technical expertise with something like this for application you will IMO hit a grand slam....great to see how you push the boundries.....section 2 of this link shows a bit of what I am talking about but you would likely have to try it to see what I am talking about...its sort of like a 3D color wheel.... https://oldgoodlight.blogspot.com/p/blog-page.html

I don't want to hear the word "intuitive" ever again. What is intuitive or not is 99% contextual to each user, that has no general meaning.

The color cube shown in the example seems to represent a primary shift, so a matrix linear operation, as performed in color calibration. As a matter of fact, I thought of a such representation for that module. But what we do here is different, it's non-linear.

It's also not new. Video editors do that as a core-feature. Examples with DaVinci Resolve and Filmlight Baselight:

![Screenshot_20201220_161236](https://user-images.githubusercontent.com/2779157/102716884-e2318080-42de-11eb-8aec-57f516f51ec5.png)
![image](https://user-images.githubusercontent.com/2779157/102716891-ef4e6f80-42de-11eb-8f08-ff7fa215593b.png)

So, we use 3 × 1D sliders (lumina / hue / chroma) instead of a 2D wheel (hue on the angle, chroma on the radius) + 1D slider (luma), but the feature is very much the same. Then we add a luminance-weighted algo **also** for chroma and saturation, which is new since all other color balances have only a flat setting for the whole luminance range (represented here by the "global" channel). 

I don't know whether this is intuitive or not, and to whom, but it's a color balance just like any other. We do it in a special RGB space and with gamut sanitization, but it's essentially the same.

> You mention on pixls that this is R&D and needs testing. I'm assuming that this means that externals like me can give it a go.

That's a very weird error you got, because it says that what is supposed to happen happens. Can you try with a more modern GCC (like 9) ? (The CI here doesn't seem to complain).

2020-12-20 15:40 UTC, jade-nl commented
> Can you try with a more modern GCC (like 9) ? (The CI here doesn't seem to complain).

I don't have the possibility to upgrade to GCC 9 (or higher) unless I'm willing to build v9 from scratch alongside the currently installed version on my stable Debian box. I remember from my Linux From Scratch days that building GCC comes with its own bag of snakes.... So, that's going to be a no-go.

There must be people here that already run the Testing (with GCC 9.3) or Unstable (with GCC 10.2) Debian version that might be able to help.

2020-12-20 15:42 UTC, johnny-bit commented
Well, @ralfbrown works afaik on gcc8 so I think I should aguament CI builds to GCC8 also... or just make them so that they match LTS os defaults...

2020-12-20 16:27 UTC, ralfbrown commented
Yes, my distro is still on GCC8 as well.  It's not an LTS release, but the next version got delayed from a planned August launch until at least the end of January....

It would be good to have at least one CI build with each major version that's still in LTS distros, provided the compiler has enough features to compile dt at all.  Keep in mind that GCC9 is a mere 19 months old -- first released May 2019.  Looking at the timeline of releases, I see that GCC has been on an annual schedule with late April/early May releases since GCC5 in 2015.

2020-12-20 17:32 UTC, todd-prior commented
@aurelienpierre Ah yes I forgot you hate that word....I get it but what I was trying to express was this ... look at the history of filmic. I would say still so many people don't really get it or how to control it and now it is at the core of DT. I think color balance tools are pivotal and your efforts to make them all that they can be is amazing.  I was merely suggesting that it would be great if there were a way to package all that in a way that helps to overcome the complexity of the task as you have pointed out in your comments about color grading. I provided the suggestion that I did as I found the cube very easy to understand and work with when I tried it out...it is based on HSL or HSV so not what you are looking for directly but more so I was reflecting on the application of the module. I could read this attached document and with a small bit of experimentation with this module I could balance and manipulate color quite easy and confidently. Again the science behind it might not be up to your math but if you could package your math and tools into a delivery system that is as relatable as something like this I think your efforts will be far more impactful in a shorter time frame with far less work defending and explaining your approach...that was what I was trying to articulate however poorly I did so...I look forward to watching how this progresses....
[Selective Color.zip](https://github.com/darktable-org/darktable/files/5721260/Selective.Color.zip)

2020-12-21 07:34 UTC, Mark-64 commented
> So, we use 3 × 1D sliders instead of a 2D wheel

What about using color weels in DT too? Could it make the gui more compact and less scary?
I could try to develop the custom widget in Gtk.

2021-01-01 17:33 UTC, aurelienpierre commented
> What about using color weels in DT too? Could it make the gui more compact and less scary?
I could try to develop the custom widget in Gtk.

Use the color correction module of dt and tell me if setting a color in a 2D space (chroma/hue) is more accurate and quicker than having 2×1D sliders for hue and saturation…

Video editors use 2D wheels because the editors have these kinds of control panels with **hardware** color wheels:
![image](https://user-images.githubusercontent.com/2779157/103443436-93c99d80-4c5f-11eb-9eac-1a29e1d7de37.png)
Us photographers have arrow keys and mouse cursors, so I don't think this kind of UI brings us anything more.

2021-01-01 17:41 UTC, aurelienpierre commented
@TurboGit if we are to merge early for larger test base, I think this is ready. At least, it's usable.

I renamed it "color balance pro" as someone suggested to get the 3-clicks crowd out of my back (yes, it's difficult, I get it, but there is nothing I can do to make it easier to grasp… You had to learn how to walk, read, write and count, it was difficult but you did it because you weren't given a choice, so I'm sure you can learn this tool too…).

Also, I used the deprecation warning to put in an experimental warning.

If changes happen in the underlying pixel algo, it will be on the way shadows and highlights are split apart for independent control. The color science seems to hold, so I don't expect problems in there.

2021-01-01 20:05 UTC, TurboGit commented
> I renamed it "color balance pro"

Bad idea to me as we have the "rgb" ending in many other modules and "rgb" do convey the fact that it is an rgb module and I don't think we want to rename all rgb module with pro.

Also, please can you fix the conflicts due to the merge of censorize module ? TIA.

2021-01-01 20:05 UTC, TurboGit requested changes
name + conflicts rework needed.

2021-01-01 22:44 UTC, johnny-bit commented
> Bad idea to me as we have the "rgb" ending in many other modules and "rgb" do convey the fact that it is an rgb module and I don't think we want to rename all rgb module with pro.

I'm more likely to agree with Aurelien though. It's not the fact that the module is in RGB that is important, is that it's "pro" and it's supposed to be "complex". And it would beat all "hurr durr the module's hard!1!" with "well, duh - it's 'pro'!" :stuck_out_tongue_closed_eyes:

2021-01-02 14:21 UTC, TurboGit commented
@johnny-bit : It would be a big mistake to me. If you name part of something pro it means that the rest is no? We have many modules that are pro level, perspective correction, contrast equalizer, tone equalizer, filmic... So to me better stick to rgb and if something is to be called pro it must be darktable itself :)

2021-01-02 15:35 UTC, TurboGit commented
I'm merging, this is good shape for the experimental trying on 3.6. Thanks for the hard work Aurélien.

2021-01-02 15:35 UTC, merged

2021-01-17 21:02 UTC, AxelG-DE commented
For one thing I am fully with Bruce Williams (donno why cannot add him via @)  

Why **high**lights is at the bottom and shadows (something dark, **low** in tone) is at the top. Feeling wise it should be opposite.