two "monochromes" bugs in fr.po
darktable-org/darktable pull request #7470
Opened 2020-12-26 17:24 UTC by chrisaga

Typo  : monchromes -> monochromes
Corrected : images monochromes -> images couleur (en : color images) + consitency with translation of message for monochromes images

2020-12-26 17:34 UTC, TurboGit requested changes

2020-12-26 17:34 UTC, TurboGit commented on po/fr.po
> +msgstr "enregistre la sélection comme images couleur"
non "enregistre" ici ne colle pas vraiment car rien n'est enregistré, c'est vraiment "set" et pas "save". je n'ai pas mieux et en tout cas pour la cohérence avec l'autre modification c'est mieux de laisser indique.

2020-12-26 19:08 UTC, Nilvus commented on po/fr.po
> +msgstr "enregistre la sélection comme images couleur"
"définit" me semblerait mieux que "indique" ici.

2020-12-26 19:09 UTC, Nilvus commented on po/fr.po
> +msgstr "enregistre la sélection comme images couleur"
Bien sûr, si "indique" est utilisé ailleurs pour "set", il faudrait aussi changer par "définit" ailleurs, pour rester cohérent.

2020-12-26 19:23 UTC, TurboGit commented on po/fr.po
> +msgstr "enregistre la sélection comme images couleur"
Oui 100% d'accord avec @Nilvus , "définit" est mieux !

2020-12-29 09:59 UTC, chrisaga commented on po/fr.po
> +msgstr "enregistre la sélection comme images couleur"
Donc je soumets de nouveau le pull request avec « définit » ?
N.B. je suis encore un peu débutant dans l'utilisation de github.

2020-12-29 10:10 UTC, TurboGit commented on po/fr.po
> +msgstr "enregistre la sélection comme images couleur"
Non tu peux corriger le code actuel sur ta branch patch-1 et pousser à nouveau ici.

2020-12-29 10:46 UTC, chrisaga commented on po/fr.po
> +msgstr "enregistre la sélection comme images couleur"
Done ! J'ai fait le nouveau commit et je vois qu'il y a un 2e commit dans ce pull-request.
Comme je ne vois pas d'action supplémentaire à faire de mon côté, je pense que c'est bon.

2020-12-29 10:53 UTC, TurboGit commented on po/fr.po
> +msgstr "indique comme images monochromes"
indique -> définit

2020-12-29 10:53 UTC, TurboGit commented on po/fr.po
> +msgstr "enregistre la sélection comme images couleur"
Encore une petite modification est on est bon :)

2020-12-29 11:13 UTC, merged

2020-12-29 11:14 UTC, TurboGit commented
Merged, thanks.

2020-12-29 11:14 UTC, chrisaga commented
oops ! celui-là aussi il était à moi ;-)
Sinon, il y a plein d'autres "indique" et je suppose que l'on ne peut pas les changer en masse car il doit bien y avoir des fois où c'est seulement une information. Toutefois, quand en anglais c'est "set" ou "sets", on doit pouvoir utiliser "définit" sans trop de risque. Quand en anglais c'est "wether", je ne m'avancerais pas sans une revue du code.

2020-12-29 12:08 UTC, Nilvus commented
> oops ! celui-là aussi il était à moi ;-)
> Sinon, il y a plein d'autres "indique" et je suppose que l'on ne peut pas les changer en masse car il doit bien y avoir des fois où c'est seulement une information. Toutefois, quand en anglais c'est "set" ou "sets", on doit pouvoir utiliser "définit" sans trop de risque. Quand en anglais c'est "wether", je ne m'avancerais pas sans une revue du code.

Certainement. Il serait au moins pertinent de vérifier chacun d'eux et si le terme "définit" ne serait pas meilleur pour certains afin d'améliorer la traduction et la cohérence de celle-ci. Penses-tu pouvoir t'en charger ? Sinon, je peux prendre le relais.

2020-12-29 14:50 UTC, chrisaga commented
> 
> Certainement. Il serait au moins pertinent de vérifier chacun d'eux et si le terme "définit" ne serait pas meilleur pour certains afin d'améliorer la traduction et la cohérence de celle-ci. Penses-tu pouvoir t'en charger ? Sinon, je peux prendre le relais.

Je peux déjà me charger facilement de tous ceux qui sont une traduction de "set". C'est la majorité, et de ce que j'ai vu pour l'instant, on peut éviter de remonter au code pour décider.
Pour les autres, je ne suis pas certain de pouvoir faire ça cette année ;-)