histogram: handle manually selected display profile
darktable-org/darktable pull request #7531
Opened 2020-12-29 04:34 UTC by dtorop

If the user manually selected a display profile, it was ignored when generating the histogram. Code always defaulted to using `DT_COLORSPACE_DISPLAY`.

Histogram colorspace process:
- the histogram is calculated just before the "gamma" iop
- pixelpipe data is in the display profile as selected by user
- the data is converted to histogram profile then processed

Before this commit, the conversion to histogram profile would be wrong anytime the user selected a display profile which was not the one found by dt_colorspaces_set_display_profile(). The histogram would change erratically as the user selected different display profiles.

Note that the histogram still will change subtly as certain display profiles are chosen. This is particularly noticeable if using a
device-specific output profile. This is because the transformation from work profile to such a display profile may lose data. See #3271.

2020-12-29 10:32 UTC, TurboGit commented
Better to use "Fixes #3271" than "See #3271" as it also close automatically the referenced issue.

2020-12-29 12:09 UTC, Nilvus commented
> Better to use "Fixes #3271" than "See #3271" as it also close automatically the referenced issue.

And so #3271 is not close. Maybe something to do.

2020-12-29 14:25 UTC, dtorop commented
I don't think this actually fixes the original problem with #3271: that after colorout the readouts can be a bit off if the display profile is bounded or otherwise not a well behaved profile (e.g. a device profile). I think it's still a decision as to whether to fix this (move the readouts to colorout) or just accept it as an architectural trade-off.

This PR fixes a simply bug by oversight on my part -- that DT_COLORSPACE_DISPLAY is the current display's profile, but doesn't represent the display profle which the user may choose. This bug became obvious while working through #3271.

Should I worry about the two unsuccessful CI tests?

2020-12-29 14:36 UTC, TurboGit requested changes
A little issue, when the display profile was wrong (.ICC from a print factory for example), a message was displayed saying that the profile was replaced by sRGB and the histogram was displayed. Now the same message is displayed but the histogram fails to be displayed. I suppose the .icc file do not make sense in such case and cause troubles. So I think we need here to check for this case and default to `DT_COLORSPACE_DISPLAY` and `""`

[Zor-Ex-Profile.icc.txt](https://github.com/darktable-org/darktable/files/5751022/Zor-Ex-Profile.icc.txt)

2020-12-29 14:37 UTC, TurboGit commented
> Should I worry about the two unsuccessful CI tests?

No these are MacOS failures which are known.

2020-12-29 15:03 UTC, dtorop commented
> A little issue, when the display profile was wrong (.ICC from a print factory for example), a message was displayed saying that the profile was replaced by sRGB and the histogram was displayed. Now the same message is displayed but the histogram fails to be displayed. I suppose the .icc file do not make sense in such case and cause troubles. So I think we need here to check for this case and default to `DT_COLORSPACE_DISPLAY` and `""`

This makes sense. I know there's similar fallback code other places. I'll look at this.

2020-12-29 19:41 UTC, johnny-bit commented
Hey @dtorop - plz edit your initial topic and add to  "see ..." "fixes  #7542" :)

2020-12-29 20:48 UTC, dtorop commented
> Hey @dtorop - plz edit your initial topic and add to "see ..." "fixes #7542" :)

I can, just as long as we're really clear that it doesn't *really* fix it -- it just fixes something serious after which #7542 is bearable..

2020-12-30 04:32 UTC, dtorop commented
Good news: One more commit, which should use sRGB as histogram profile if the chosen profile is invalid. A warning is displayed as well.

Bad news:
1) The output is noisy -- every time preview pixelpipe runs, the warning is displayed.
2) Behavior of the various "readouts" is inconsistent. Global color picker switches to display colorspace. Swatches in global color picker go black. Overexposed iop ends up with a buffer of all 0's. Is it worth fixing these to make them consistent? Or will the repeated onscreen warning to the user be enough?

More bad news:
I can't edit the initial topic to say Fixes #7542! No idea why. I can edit my alter comments. Maybe something locks after a while? Also, I was confused, sorry @johnny-bit. I thought we were still talking about fixes #3271!

2020-12-30 04:51 UTC, dtorop commented
Rebased to current master to fix merge conflicts.

Also: would it be better to check for an unworkable histogram profile when the user chooses it rather than every time the preview pixelpipe runs? The check could be in histogram_profile_callback()

https://github.com/darktable-org/darktable/blob/6b58bc079e9474291ecaaffdeb974a210a4de3e7/src/views/darkroom.c#L1886

2020-12-30 07:18 UTC, johnny-bit commented
> would it be better to check for an unworkable histogram profile when the user chooses it rather than every time the preview pixelpipe runs?

Yep :) After all if check is done in place of setting instead of every run, it has better chance of communicating to user what's wrong :)

2020-12-30 08:59 UTC, TurboGit commented
> Also: would it be better to check for an unworkable histogram profile when the user chooses it rather than every time the preview pixelpipe runs? The check could be in histogram_profile_callback()

Yes, let's do that as part of this PR. This makes more sense indeed and will avoid confusion. If not too costly it would even be better to list into the comboboxes only the profile that are OK for intent.

2020-12-30 16:57 UTC, dtorop commented
> If not too costly it would even be better to list into the comboboxes only the profile that are OK for intent.

I'll try this. Probably in load_profile_from_dir(), as that already reads/processes the profiles.

https://github.com/darktable-org/darktable/blob/c2dcf088d9f8d6f36dbd2115627cad114b7d11e4/src/common/colorspaces.c#L1308

A question: if the profile is unusuable (e.g. CMYK), is there any case where it should be displayed for selection by the user? I tried the CMYK profile @TurboGit supplied and it is either "replaced by sRGB" or causes glitches in every case I can try. Should such profiles just be dropped at startup with a warning message to stderr?

2020-12-30 17:35 UTC, johnny-bit commented
> Should such profiles just be dropped at startup with a warning message to stderr

Yes... and maybe to `dt_control_log` or something like that?

2020-12-30 22:47 UTC, TurboGit commented
Yes can be dropped, CMYK are not supported. No need to list them. Today we have a message:

`[_transform_rgb_to_rgb_lcms2] profile color space `CMYK' not supported`

2020-12-31 22:02 UTC, dtorop commented
> Yes can be dropped, CMYK are not supported. No need to list them.

Done in the most recent commit. RGB and grayscale (which are converted to RGB) profiles are accepted as histogram profiles. All others are not shown in the GUI, and a diagnostic is printed to stderr.

> and maybe to dt_control_log or something like that

I left out dt_control_log diagnostic, as this filtering happens in dt_colorspace_init(), and we may be running w/out a GUI.

It's possible to filter out non-RGB profiles in other cases, as the comment mentions. I was conservative here and didn't.

2021-01-01 18:04 UTC, dtorop commented
I'm thinking that as this PR is for 3.4.1, that it should be good to go now. For 3.6 it might be good to look into dropping other output (or input?) profiles which are not RGB/grayscale (or maybe XYZ, depending on what the code can handle). But a change such as that should wait on more use/testing, as it may turn out that someone's favorite profile will stop working.

2021-01-02 17:49 UTC, TurboGit commented
Works for me. Thanks!

2021-01-02 17:50 UTC, merged

2021-01-02 17:50 UTC, TurboGit commented
Merged on master, queued for 3.4.1.