channelmixerrgb: handle rotated orientations of color checker
darktable-org/darktable pull request #7700
Opened 2021-01-05 17:28 UTC by flannelhead

Previously the color checker extraction would calculate a small rectangle that is inside the checker patch. That calculation didn't work if the checker was rotated with respect to the original orientation of the grid - the sampling areas would become too small.

Instead, calculate the bounding box of the patch, run through these pixels and check for inclusion in the (possibly slanted) patch. This utilizes the patch area more efficiently.

Also deduplicate the color checker sampling code.

2021-01-06 10:58 UTC, aurelienpierre commented
Code looks good, I need to test.

2021-01-06 17:56 UTC, TurboGit commented
After merging another PR this one needs some work to resolve conflicts. TIA.

2021-01-06 18:37 UTC, TurboGit requested changes
Fix conflicts.

2021-01-06 19:06 UTC, flannelhead commented
Rebased on master and conflicts fixed.

2021-01-08 23:50 UTC, aurelienpierre commented
tested, works great. Thanks !

2021-01-08 23:50 UTC, aurelienpierre approved these changes
all good

2021-01-09 07:14 UTC, TurboGit commented
Works for me too. Thanks.

2021-01-09 07:14 UTC, merged

2021-01-09 09:42 UTC, flannelhead commented
Thanks for merging! Forgot to say, this should remove the need to rotate and perspective correct the checker image beforehand, removing a couple of steps from the profiling. Lens correction has to be still applied though.