import pref: insert an optional pref dialog before import action
darktable-org/darktable pull request #7717
Opened 2021-01-06 17:48 UTC by phweyland

fixes #7435

Attempt to answer the concerns risen in #7435.

- keep the hambuger pref
- add a step between the plugin import button and the actual import action to show the prefs
- the import action uses the visible (changed or not) prefs
- after importing the user can cancel not to save the prefs which have been used
- a flag allow not to show the in between dialog

![image](https://user-images.githubusercontent.com/23012047/103802261-a5c78980-502d-11eb-974b-5bf5a52c6e56.png)
 
Note: in import from camera, there is still a notebook (tabs), one tab just to define the date. This date setting could be moved to the intermediary dialog (no saving on it). One drawback however, if this intermediary dialog is skipped, the user cannot set the date (but he can always make the dialog appear back).

Note2: I assume than tethering works the same way but I haven't tested.

2021-01-06 21:40 UTC, TurboGit requested changes
Need a conflict resolution.

2021-01-07 00:33 UTC, phweyland commented
Conflicts solved.

2021-01-07 11:38 UTC, Nilvus commented
I will test that PR but on what I understand, I don't like that. If I understand correctly, when we click on image or folder button, we will now have at first screenshot on your first post. So one more action, even if we don't need to change settings. Bad idea!

I think a simple button to access settings in actual dialog window to import would be better, as I suggested in my last comment in #7707

2021-01-07 11:49 UTC, phweyland commented
> So one more action, even if we don't need to change settings. Bad idea!

have you read the first post and in particular the word optional ?

2021-01-07 12:03 UTC, Nilvus commented
> > So one more action, even if we don't need to change settings. Bad idea!
> 
> have you read the first post and in particular the word optional ?

I have read it but indeed missed just the "optional" word. My bad!

2021-01-07 19:18 UTC, Nilvus commented
> ![image](https://user-images.githubusercontent.com/23012047/103802261-a5c78980-502d-11eb-974b-5bf5a52c6e56.png)

Presets line and all entries after are put in a box widget. Could you add a name on it (like "import-fields") . This will need a margin after label in just those lines (margin between text and entries).

Other thing, the way it is done let too much space on the right of those lines (about lines with checkbox, it's ok and that space is related to -+ buttons. I've check and didn't see any padding or margin to change and let preset line combobox and all entries use the whole width. It would really be better to have those lines aligned on the right to -+ buttons above. Could you check if something need to be changed in your code to allow that? I know, it's the same in preferences made on your previous PR but I didn't notice that before.

Last thing, I think we need to have a way to better view image or folder button in that new dialog window. Something like a bold border to invite the eye user to understand at first view that the next step is that button and to differentiate it. I would suggest three things:

- align on the left cancel and save preferences button (in actual order)
- align to the right image or folder button
- add a CSS tag in image and folder button (same tag, something like "imp-nextstep")

Apart of that, It's all good for me.

2021-01-07 19:28 UTC, phweyland commented
@Nilvus, thanks for the review. I'll look at all this.

2021-01-08 11:26 UTC, phweyland commented
I haven't found the way to to left align cancel/save buttons and keep the action button on the right. This a property at the action-box (which contains the buttons) level.

The remaining points are done, in particular:
- metadata fields named as "import-metadata-fields"
- action button named as "import-action"

with "write sidecar file":
![image](https://user-images.githubusercontent.com/23012047/104010308-0d471b80-518b-11eb-9f37-f599fbf745a8.png)

without
![image](https://user-images.githubusercontent.com/23012047/104010257-facce200-518a-11eb-9253-1bee6e1ccff6.png)

2021-01-08 11:41 UTC, phweyland commented
@wpferguson , once more time digging around lua services...
In import module, lua can add some entries. I would like to check if that still works and if those entries are properly rendered. 
Is there an existing add-on adding import settings entries ?

2021-01-08 16:33 UTC, wpferguson commented
@phweyland you can use official/import_filter_manager.lua and official/import_filters.lua to check.  Be sure and start the filter manager before the filter.  If you need me to code up something, let me know...

2021-01-08 17:37 UTC, TurboGit commented
Tested and I must say that I'm not fan of this intermediate dialog that I almost never use. Indeed in my case I most of the time setup the global options and almost never change them. I suppose there is some people in my case and some not. May I suggest to:
- use the **default behavior** as set by the pref to show or not the dialog when a **click** is made
- to i*invert the behavior** when a **ctrl-click** is made to allow for an exception dialog to appear or an exceptional no dialog.

How does that sound ?

2021-01-08 18:15 UTC, phweyland commented
To be sure I understand properly.
>     * use the **default behavior** as set by the pref to show or not the dialog when a **click** is made

Here, no change as for now, correct ?
I've set "show the intermediary dialog" by default because that is the easiest way to discover it. Now we could hide it by default.
 
>     * to **invert the behavior** when a **ctrl-click** is made to allow for an exception dialog to appear or an exceptional no dialog.

Here is the change, right ? Yes, that can be handy (for who knows what he has configured :) ).

2021-01-08 19:18 UTC, TurboGit commented
@phweyland : yes, that's exactly my thinking.

2021-01-08 22:07 UTC, phweyland commented
Added ctrl-click to invert the pref behavior.
Remains to check lua.

2021-01-09 07:47 UTC, TurboGit commented
A little issue:
- I have disabled the dialog
- I do ctrl-click folder to show it
- I change some setting (2 stars for example)
- click on folder
- select the folder on the dialog now appearing
- and import picture, all fine up to here
- but import is done I still have the preference dialog opened, it should be closed when opening the import dialog

2021-01-09 07:47 UTC, TurboGit requested changes
close dialog when not needed anymore

2021-01-09 12:01 UTC, phweyland commented
>     * but import is done I still have the preference dialog opened, it should be closed when opening the import dialog

That's on purpose. First you can change again the settings or not, and do another import.
Then after import, you can choose to cancel or save the settings.

We could have other options to close automatically the dialog, with or without saving the settings, but that seems to me over killed...

2021-01-09 12:06 UTC, TurboGit commented
Then the question is how many time one do multiple imports in a row?

2021-01-09 12:12 UTC, phweyland commented
@nilvus has already given his feedback, but I would appreciate the others who have commented or requested features in #7717, @AxelG-DE, @elstoc, @johnny-bit, share their thoughts. TIA ;)

2021-01-09 12:27 UTC, phweyland commented
> Then the question is how many time one do multiple imports in a row?

Maybe not many, or even rarely, but closing the parent dialog seems a ugly, at least not expected. It is not natural and I don't see that as an improvement.

I understand you are not fan of the intermediary dialog. I would not need it neither but it doesn't bother me.
One can disable it and still access the preferences through the import hamburger or through ctrl-click when needed.

2021-01-09 12:39 UTC, phweyland commented
lua filters:
![image](https://user-images.githubusercontent.com/23012047/104091750-2f5d9e00-525e-11eb-811c-f48922b2866a.png)

![image](https://user-images.githubusercontent.com/23012047/104091768-56b46b00-525e-11eb-9871-18e633c6b000.png)

@Nilvus, lua entries are added in the same box as metadata. Do I let them as is or move I them after the metadata box ?

2021-01-09 13:05 UTC, phweyland commented
> > Then the question is how many time one do multiple imports in a row?
> 
> Maybe not many, or even rarely, but closing the parent dialog seems ugly, at least not expected.

A tooltip on the action button, warning the pref dialog will be closed, may turn this more expected...

2021-01-09 14:53 UTC, phweyland commented
>     * but import is done I still have the preference dialog opened, it should be closed when opening the import dialog

Given a try and changed my mind. It's fine as you suggest.
To make it work, the dialog loops now on save button (instead of action).

2021-01-09 15:30 UTC, elstoc commented
I'm not really a fan of the workflow. It isn't clear what the save and "image..." buttons do - it's not obvious that it only imports with the keyed metadata if you click save and then import - if you forget to do this it will import with whatever was present before you amended it. I remain of the opinion that the preferences should be used to set default values and that the box which appears before the file selection dialog should allow those defaults to be altered just for this import (i.e. should be a different dialog).

I'm not sure whether it's new with this PR but the preset workflow is a bit odd - i.e. that you can create user presets and save them in the lib ui but you can't set the hard-coded presets in the lib ui or access user generated ones from the preferences popup.

2021-01-09 16:05 UTC, TurboGit commented
@elstoc : To be sure we are on the same page.

This dialog can be use to set the default value or use to set some values for the import.

We still have the dialog into the [Preferences...] menu under the burger like icon to set the global preferences. And if one ask to not see this intermediate dialog the workflow is simpler.

So at this stage it seems that we have do our best to have anyone workflow covered. Maybe you have another proposal but I'm not sure to understand it.

2021-01-09 16:09 UTC, phweyland commented
Thanks for your comments.

> I remain of the opinion that the preferences should be used to set default values and that the box which appears before the file selection dialog should allow those defaults to be altered just for this import without having to change the global preferences

That's exactly what it does as long you don't click on save.

> that you can create user presets and save them in the lib ui but you can't set the hard-coded presets in the lib ui or access user generated ones from the preferences popup.

Sorry I don't get this. What are the "hard-coded presets"  or " user generated ones" ?

> the import preferences should be part of the module UI itself.

That makes sense to me. 
If these data are today in preferences (preset menu) or an intermediary dialog, it is just because the preferences commodities (generated automatically by preferences config) are based on a dialog, and are not usable in as such in module. Of course the old manually coded way is still possible.

2021-01-09 16:13 UTC, johnny-bit commented
How about this:
In case of import module, resign from dialog window for preferences. Instead - put import preferences directly in module itself, but behind expander. Similar to white balance module channel coeficients. Name expander "import options" and fill those options from presets. So it'd make import flow basically the same as it was before removing import options from file chooser dialog, only import options would be part of import module ui, not file chooser ui.

2021-01-09 16:17 UTC, elstoc commented
> That's exactly what it does as long you don't click on save.

You're right of course. I made the mistake of importing images which already had xmp files which overwrote the metadata

> Sorry I don't get this. What are the "hard-coded presets" or " user generated ones" ?

I mean that there's a preset list for the metadata fields (in the popup) and it's a little confusing that it's separate from the module presets (which are handled in the normal preset UI way).

Really though, the best way to overcome this, and do away with the need for a separate dialog is...

1. Incorporate the preferences into the module UI itself, in a separate collapsible section
2. If the user wants to save presets they can use the standard preset functionality to do so, otherwise whatever they key into the module UI will be used for the next import and stored in the "last_..." preference settings
3. Remove the option from the hamburger menu and the pre-import popup dialog.

If you want to keep the current workflow the easiest way is to remove the "save button" from the pre-file-chooser popup (don't allow the user to save the preferences) and just have OK/Cancel to take them to the file chooser or exit the workflow. But I still think it feels a little convoluted.

2021-01-09 16:19 UTC, TurboGit commented
I see, for the import from sdcard or camera we can have those options into a separate tab as before.

@phweyland : if you want to experiment this let me know, I suppose we need to adjust the generation of the code from darktableconfig.xml.in as today we are expecting a dialog as first parameter IIRC. Anyway, I can help on this part if needed.

2021-01-09 17:15 UTC, phweyland commented
Thanks ! That looks like a kind of reset, right ? :smiley: 

> I suppose we need to adjust the generation of the code from darktableconfig.xml.in as today we are expecting a dialog as first parameter

Yes. 
I'll start with that and update accordingly the modules which use this services without ui change (collect and import). 

When done, I'll rework the import module.

2021-01-09 18:28 UTC, TurboGit commented
@phweyland : What I propose is to split the current generation in two. We have today:

`GtkWidget *dt_prefs_init_dialog_collect(GtkWidget *dialog);`

I propose to add:

`GtkWidget *dt_prefs_init_grid_collect(void);`

The later will return a grid with all items. This is basically the code in `dt_prefs_init_dialog_collect();`. And this `dt_prefs_init_grid()` routine will be called by `dt_prefs_init_dialog_collect();` and you'll be to call it to to create the grid with all prefs items inside.

I suppose this would work for you. Is that ok?

2021-01-09 18:39 UTC, phweyland commented
I've started this way:

For dialog(s) I've replaced
`GtkWidget *dt_prefs_init_dialog_collect(GtkWidget *dialog);`
by
`GtkWidget *dt_prefs_init_dialog_collect(void);`
where signal "response" is removed.
I'll rename it to emphasis the grid.

For dialog(s)
I remove
`preferences_response_callback_xxx`
and add the data saving into
`preferences_changed_callback_xxx`

This is compiling. I'm starting to update the callers to check it.
Of course we can make all the changes you think useful.

2021-01-10 07:44 UTC, AxelG-DE commented
Good morning gentlemen,

did I get this right, for future safety (porting to GTK4, which potentially(!) never comes) we cannot have it, as it was?

TBH I am not a fan either of having a pop-up, which I have to click away to reach what I intentionally wanted to reach (import dialog). I see too many cases in my company, where such things are clicked away w/o reading (BTW: my expectation was, if I click on *safe*, the dialog disappears, but didn't. Maybe that's just me, as it appears to me similar like a save-dialog at the ending of a soft)

I understand @TurboGit when he says "I almost never need it". I am also not the guy who regularly needs it, but **there is one case I need it EVERYTIME** (I am not meaning to shout, just need another emphasize)

I often look after errors and hence start dt with --configdir {chose a new dir, likely /tmp}. **NOW subdir** is per default **off**. That is the moment (not seeing any pics after import), I realize, I need to go to import dialog again and click *include subdirs*



> Then the question is how many time one do multiple imports in a row?

@TurboGit please see my usecase above. Is not many imports in a row, I agree, also me don't do that

> Here is the change, right ? Yes, that can be handy (for who knows what he has configured :) ).

Exactly here I have my issue
Ppl. getting older, having other, harder priorities or turbulences in life (but looking for distraction in editing photos, so still don't run away)

If it is up to me, I just wanna have it back as it was. I still do not see any need from user perspective (so don't use GTK4 as argument), why the formerly well worked principle had to be changed.

I hope I do not sound grumpy (--> turbulences)
(me I still hate, github wastes so much space on left and right hand side margin (only 50% of screen width is used, not even to talk about height during editing, but this is OT)

2021-01-10 09:06 UTC, Nilvus commented
> @Nilvus, lua entries are added in the same box as metadata. Do I let them as is or move I them after the metadata box ?

Seems good for me like that. But I don't use lua filters to be totally sure.

2021-01-10 09:18 UTC, Nilvus commented
Reading all comments of that controversial step added, I would suggest that way. That seems for me a good compromise between all comments and GTK4 limits:

- Put line "show import preferences..." at first in settings dialog window and so first dialog when clicking on folder/image import
- @phweyland: you forget to put cancel and save buttons on the left. I think it will be better to quickly see folder or image option

See mockup below for those 2 suggestions.

- Then, I would keep that dialog window visible by default and with first line "show import preferences..." at first, all users, like @TurboGit, that want to not have that window will just have one time to unselect that option. And we will be sure that all users now that option. I suggest to show an alert when unselect that option, that this option could be reactivated by the settings option in the hamburger menu of the module. Would help users to learn new behavior
- Then, as suggested by @TurboGit, have click for dialog window without settings at first and ctrl+click to open settings window at first

![104010308-0d471b80-518b-11eb-9f37-f599fbf745a8](https://user-images.githubusercontent.com/45535283/104119025-2ee00880-532d-11eb-980e-a5706216bf50.png)

I think this would be good for all users that way, quite versatile way.

2021-01-10 09:21 UTC, Nilvus commented
@phweyland: did you add a css tag as I suggested previously to image and folder buttons in that setting dialog window? I don't find it in the code and it would be good to have it, to try something like bold text or more visible border, to show that it is the first natural step. Could you add it and ping me, to allow me to do some tests on that idea? Thanks.

2021-01-10 13:15 UTC, phweyland commented
@Nilvus
> did you add a css tag as I suggested previously to image and folder buttons in that setting dialog window?


![image](https://user-images.githubusercontent.com/23012047/104123704-82515700-532b-11eb-94cd-177b468b11e6.png)



>     * you forget to put cancel and save buttons on the left. I think it will be better to quickly see folder or image option

I haven't forget this, but to achieve it we need not to use the standard dialog buttons, and rebuild them manually. Could be done, but would be the last step. :)

This following graphical suggestion is currently not possible with automatic preference code, but I can try to have this setting at the first place.
![image](https://user-images.githubusercontent.com/23012047/104123834-19b6aa00-532c-11eb-9e2f-c3e3e86afb95.png)


>     * Then, as suggested by @TurboGit, have click for dialog window without settings at first and ctrl+click to open settings window at first

This is coded.

2021-01-10 13:23 UTC, phweyland commented
>  for future safety (porting to GTK4, which potentially(!) never comes)

There is another more immediate reason. These embedded widgets in file chooser dialog prevents us to solve performance issues with NAS on windows #7220.

2021-01-10 13:54 UTC, phweyland commented
I'll give a try implementing these parameters in the import module itself. Then we choose the best one.

2021-01-12 00:37 UTC, phweyland commented
> parameters in the import module itself

Available [here](https://github.com/phweyland/darktable/tree/imp-pref3)

Double click on label to reset to default value.
Import module presets functional.
Does that seems to be better ? What do we do ?

Some screenshots:

![image](https://user-images.githubusercontent.com/23012047/104253680-d8b9b500-5453-11eb-9462-310c43a041b5.png)

With save xmp
![image](https://user-images.githubusercontent.com/23012047/104253817-2fbf8a00-5454-11eb-820e-398275d31860.png)

![image](https://user-images.githubusercontent.com/23012047/104253867-51207600-5454-11eb-91b6-71687ae337e4.png)

Without save xmp
![image](https://user-images.githubusercontent.com/23012047/104253759-07d02680-5454-11eb-9186-e94a2bc4f18e.png)

2021-01-13 10:28 UTC, TurboGit commented
> I'll give a try implementing these parameters in the import module itself. Then we choose the best one.

Not convinced, not that it won't work but for consistency across modules. We have now preferences in the general pref dialog, in the [preference...] dialog under the hamburger menu and inside the menu. For me, even if I don't really like this intermediate dialog I prefer consistency for the GUI. Let's see what others think about this.

2021-01-13 10:58 UTC, johnny-bit commented
I am all for options IN the module ui for import module. Consistency is important when it makes sense. In case of import module one could look at export module: if it was like import module it'd have just "export" button with all the storage/format/global options hidden in preferences menu ;) instead export module has almost all options "front and center" with just metadata (which is additional stuff) hidden away.

So ultimately i think a balance should be sought between consistency, usability and flow: pereferences hidden away in menu when they make sense in menu and not in preferences dialog nor in main ui; preferences in main ui where they make sense in main ui (eg it's way better flow that way); preferences in settings dialog where they make sense (eg touch multiple different modules/parts of dt etc); preferences onlyin rc when having them is beneficial but only for those willing to change them.

2021-01-13 11:29 UTC, elstoc commented
I think for lib modules it makes sense for the module parameters to be displayed in the module UI itself. This is consistent with how the export module works. 

For iop modules, because by default their settings are not copied from one image to the next or between sessions, there needs to be some separate and obvious method for setting those persistent preferences. There aren't that many iop modules that have global preferences associated with them (lut3d, color balance, white balance is all  of them I think) and for these, the global settings dialog seems reasonable, because there are so few.

2021-01-13 12:15 UTC, phweyland commented
> consistency across modules

If one thinks about preferences, yes, consistency may be questionable. But if one thinks about parameters, that's just as for other modules (export, ...).
Besides the expander can be called `parameters` ...

2021-01-13 12:19 UTC, elstoc commented
> Besides the expander can be called parameters ...

or preferences?

2021-01-13 12:34 UTC, phweyland commented
> > Besides the expander can be called parameters ...
> 
> or preferences?

Yes, of course. But here comes Pascal's objection about consistency. 

On my side I'm happy with preferences in presets menu.
But I understand the process wise concerns when one needs to change often these parameters.
BTW this qualifies for me the fact these are more parameters than preferences (which usually are more or less permanent). 
Between the intermediary dialog and the in module parameters I prefer the last one (and forget the preference qualification ...).

2021-01-13 12:46 UTC, phweyland commented
The usage / modification frequency can be used to split the set of information which do not change often (=> preferences in presets menu) and those which are specific to almost each import (=> parameters in module).

For example, on the last screenshot, the first 4 can be seen as preferences (the import from xmp flags as well for those who don't use xmp files) while the metadata are more specific to that import action / context.

2021-01-13 12:54 UTC, elstoc commented
I would have said that only the rating ones qualified really. IIRC the jpeg setting just ignores all jpegs (so I'd want to change it if I was using a camera that only takes jpegs) and sometimes I want to import a recursive set of directories and sometimes I don't.

In which case, is it even worth a separate menu/dialog just for those two preferences?

2021-01-13 13:02 UTC, TurboGit commented
I've never for an in between solution which will look wrong as time goes to me. So let's explorer a radical change.

Let's the import module be like the export one. That is, all preferences are put there, all of them are removed from the general preference dialog and all of them are stored in presets.

On the implementation details then will require more changes:
- no more in the XML config
- no more default values
- no more indicator about a value being the default or not
- no more auto generated but maintained manualty as for the export module

The big advantage here is that the presets will be handy to have different settings store and readily available.

How does that sound ?

2021-01-13 13:09 UTC, phweyland commented
>     * no more in the XML config
>     * no more default values

XML config is here useful to retrieve by introspection display name, tooltip, default value, min, max, ...


> * no more indicator about a value being the default or not

I've remove this one to save space in width.

> * no more auto generated but maintained manualty as for the export module

Yes, no more generated code here.

2021-01-13 13:16 UTC, TurboGit commented
> XML config is here useful to retrieve by introspection display name, tooltip, default value, min, max, ...

Agreed, config must stay indeed.

2021-01-13 13:17 UTC, TurboGit commented
What about the preset support ? Is that already done (not tested yet on my side).

2021-01-13 13:24 UTC, phweyland commented
> What about the preset support ? Is that already done (not tested yet on my side).

Yes, it is done.

2021-01-13 13:33 UTC, TurboGit commented
So can you create a PR ?

2021-01-13 14:52 UTC, Nilvus commented
I've read your last comments. I'm also for consistency, but consistency depends on context. And import module is indeed, as @elstoc said, like export module.

So, regarding all our discussion here and how import work, last proposal by @phweyland is much better, having parameters inside the module, below buttons. So I'm all for that, quicker to set before clicking on image or folder, and quicker to hide/show with the arrow expander.

That's just the good way to do, and it is consistent with similar modules like export one and as it is also different for others modules about settings. And much much better than the intermediate step.

2021-01-13 19:03 UTC, closed without merging