Update french translation
darktable-org/darktable pull request #7736
Opened 2021-01-07 18:56 UTC by Nilvus

French translation update. @aurelienpierre and @TurboGit: if you could check all is good for you? Thanks.

2021-01-07 20:50 UTC, TurboGit requested changes
Difficult to review as many diffs are due to change in order of messages!!! Many diffs are not actual changes...

I have spotted at least widget used in many places which could well be replaced by **contrôle** as we are speaking about a specific control in a module.

2021-01-07 20:50 UTC, TurboGit commented on po/fr.po
> +msgstr "widgets basiques"
widgets -> contrôles ?

2021-01-07 20:50 UTC, TurboGit commented on po/fr.po
> +msgstr "ajoute un widget à la liste"
widget -> contrôle ?

2021-01-07 20:50 UTC, TurboGit commented on po/fr.po
> +msgstr "cliquer pour supprimer le widget"
widget -> contrôle ?

2021-01-07 20:50 UTC, TurboGit commented on po/fr.po
> +msgstr "cliquer pour ajouter le widget"
widget -> contrôle ?

2021-01-07 20:50 UTC, TurboGit commented on po/fr.po
> +msgstr[0] "widget recommandé"
widget -> contrôle

2021-01-07 20:50 UTC, TurboGit commented on po/fr.po
> +msgstr "supprimer ce widget"
widget -> contrôle

2021-01-07 20:50 UTC, TurboGit commented on po/fr.po
> +msgstr "Aller au module complet %s"
pas de majuscule

2021-01-07 20:50 UTC, TurboGit commented on po/fr.po
> +"Ce widget de base est désactivé car il y a plusieurs instances pour ce "
pas de majuscule (je corrige sur l'anglais)

2021-01-09 19:10 UTC, Nilvus commented
> Difficult to review as many diffs are due to change in order of messages!!! Many diffs are not actual changes...
> 
> I have spotted at least widget used in many places which could well be replaced by **contrôle** as we are speaking about a specific control in a module.

widget is used in french, that's why I don't change them. I'm for keeping them but I'm ok too for "contrôle" instead.

2021-01-09 20:54 UTC, Nilvus commented on po/fr.po
> +msgstr "Aller au module complet %s"
Je n'ai pas traduit ça mais je corrige.

2021-01-09 20:54 UTC, Nilvus commented on po/fr.po
> +"Ce widget de base est désactivé car il y a plusieurs instances pour ce "
Ok

2021-01-09 20:56 UTC, Nilvus commented
> Difficult to review as many diffs are due to change in order of messages!!! Many diffs are not actual changes...
> 
> I have spotted at least widget used in many places which could well be replaced by **contrôle** as we are speaking about a specific control in a module.

On that, I don't know how to do differently. I had just updated pot and then fr.po to make that translation.

2021-01-09 22:04 UTC, TurboGit commented
> On that, I don't know how to do differently.

You cannot do differently, not your fault that the way updating a po file is done.

2021-01-10 09:55 UTC, Nilvus commented
@TurboGit: new colorbalance rgb seems to not be integrated for translation. I've just see it in english in master and I don't see related text in po.fr, after updating it of course. Could you check what Is missing and ping me? I will update that PR after.

2021-01-10 13:34 UTC, TurboGit commented
> @TurboGit: new colorbalance rgb seems to not be integrated for translation. I've just see it in english in master and I don't see related text in po.fr, after updating it of course. Could you check what Is missing and ping me? I will update that PR after.

Indeed, it was missing. I have just added. Would it makes sense to merge this PR and work on colorbalancergb into another PR ? It will be easier to review. Anyway is fine by me, just let me know.

2021-01-10 13:58 UTC, Nilvus commented
Ok,  i will do another PR. You could merge that one.

2021-01-10 13:59 UTC, TurboGit commented
Good, merging then. Thanks.

2021-01-10 14:00 UTC, merged