Basic adjustments, new link to full module
darktable-org/darktable pull request #7753
Opened 2021-01-08 20:02 UTC by Mark-64

This will implement #7745 by removing the multiple gear wheels to link to the full module and replacing them with a single button per module, with a new icon

This is the aspect on Linux

![Screenshot from 2021-01-08 20-50-25](https://user-images.githubusercontent.com/43290988/104058758-8b8bd800-51f4-11eb-8dad-6d82c969c413.png)
 .. and on Windows

![immagine](https://user-images.githubusercontent.com/43290988/104058826-a1999880-51f4-11eb-82ea-a3fcc661f341.png)

2021-01-08 21:56 UTC, AlicVB requested changes
Thanks for this work !

I have 2 "small" remarks : 
- as said in the issue, if one set `plugins/darkroom/modulegroups_basics_sections_labels=false` (to save some vertical space) there's no more way to go to full module... So either we decide to remove this pref completely (why not) either we need to add the link at each widget end like before (just if we have this pref set to false, of course)...
- maybe it's just me, but I would prefer if the right side of your icon is aligned with the right side of widget (with pickers). I would also have put the line longer (so it's centered) See screenshot below... @Nilvus : if you have time, can take a look ?

![Capture d’écran_2021-01-08_22-41-09](https://user-images.githubusercontent.com/1818223/104067868-3a83e000-5204-11eb-8146-f0f413c5f9be.png)

2021-01-08 21:58 UTC, johnny-bit commented on src/dtgtk/paint.h
> +/** Paint a link icon for basic adjustments*/
In order to be picked up by `show_icons_in_paint_c.pl` tool the comment has to end with space before `*/`
```suggestion
/** Paint a link icon for basic adjustments */
```

2021-01-08 22:28 UTC, johnny-bit commented
> So either we decide to remove this pref completely

I love me some vertical space, PLZ not remove `plugins/darkroom/modulegroups_basics_sections_labels` (actually - I'd make it even a visible option in groups manager for basic group!) ... 

As for alignment of the button - imo it's fine.

anyway - for section labels I'd have some crazy ideas with custom serparators, but that's an overkill ;) however if `plugins/darkroom/modulegroups_basics_sections_labels` could be shown based on preset options... I'd love that! (but that's a comment not related to this pr)

2021-01-08 22:33 UTC, TurboGit commented
For the alignment I agree with @AlicVB, we can do better even if current proposal is already good.

2021-01-08 22:35 UTC, TurboGit commented
Code look ok to me also, just maybe squash all in one commit. If you don't know how to do that I'll do, no problem.

2021-01-09 07:48 UTC, Mark-64 commented
When coming to the "no section labels" option, do you want multiple link buttons next to each widget, like before ?

![immagine](https://user-images.githubusercontent.com/43290988/104086201-f0c3e580-5255-11eb-94f1-b62b6cba15ab.png)

or rather a single button per module to the right of everything, line included, in order to appear separate (this is a mockup) ?

![immagine](https://user-images.githubusercontent.com/43290988/104086336-3c2ac380-5257-11eb-9fb0-3c52016eba86.png)

2021-01-09 08:43 UTC, johnny-bit commented
At first I thought button next to all elements wouldn't be bad, but it's a bit messy. Id say - if it's not too big of a problem a single button per set of module controls would be preferable

2021-01-09 10:10 UTC, TurboGit commented
Agreed with @johnny-bit !

2021-01-09 10:17 UTC, AlicVB commented
yes, your last mockup would be better. It will need more work, thought... don't hesitate to ask for help if needed !

2021-01-09 21:07 UTC, Nilvus commented
> Thanks for this work !
> 
> I have 2 "small" remarks :
> 
>     * as said in the issue, if one set `plugins/darkroom/modulegroups_basics_sections_labels=false` (to save some vertical space) there's no more way to go to full module... So either we decide to remove this pref completely (why not) either we need to add the link at each widget end like before (just if we have this pref set to false, of course)...
> 
>     * maybe it's just me, but I would prefer if the right side of your icon is aligned with the right side of widget (with pickers). I would also have put the line longer (so it's centered) See screenshot below... @Nilvus : if you have time, can take a look ?
> 
> 
> ![Capture d’écran_2021-01-08_22-41-09](https://user-images.githubusercontent.com/1818223/104067868-3a83e000-5204-11eb-8146-f0f413c5f9be.png)

I will test. Just one thing: I see that you have a filmic widget on your screenshot. When I made a right-click on basics icon, I don't have all modules and no filmic. Is it normal and so how do you add filmic widget?

![image](https://user-images.githubusercontent.com/45535283/104108709-16d59e00-52c7-11eb-8abd-7d27eb3fbe85.png)

2021-01-09 21:21 UTC, Nilvus commented
>     * maybe it's just me, but I would prefer if the right side of your icon is aligned with the right side of widget (with pickers). I would also have put the line longer (so it's centered) See screenshot below... @Nilvus : if you have time, can take a look ?

I would not align new link to pickers or other things, because if we add only one for few widgets of same module, new link icon should be right after pickers or similar other things (like arrow of dropdown). What I see here, is that when the new link icon is on the name module line, we should have bottom border line (so line just below module name) use whole length and be under new link. Or to be simple, I would see the new link in the module title. But is it easily feasible? Not sure and not completely with CSS.

And, at least, the new link icon need to be aligned to module name title. Actually, the icon is a little too high.

See alignment I see below:

![2021-01-09_22-16](https://user-images.githubusercontent.com/45535283/104108920-fb6b9280-52c8-11eb-8799-eb1cb3778bdf.png)

2021-01-10 07:32 UTC, TurboGit commented
Need conflict resolution probably due to the now merged work for the new lightttable icons.

2021-01-10 08:19 UTC, Mark-64 commented
Yeah, no problem.
I think I will open a new PR anyway because as @AlicVB predicted, handling both `plugins/darkroom/modulegroups_basics_sections_labels` options required much more work, especially for my limited skills.
I am almost there, please be patient.

2021-01-10 14:25 UTC, Mark-64 commented
Continues in #7778. Closing here

2021-01-10 14:25 UTC, closed without merging