channelmixerrgb: fix color checker drawing and sampling
darktable-org/darktable pull request #7874
Opened 2021-01-15 22:34 UTC by flannelhead

I missed some details in https://github.com/darktable-org/darktable/pull/7700 about the coordinate transformations... It improved things but didn't completely fix the color checker extraction (or drawing) in positions other than close to the starting position and orientation. 

The `ideal_box` coordinates are now normalized to the interval [0, 1]. Dependence on preview area width and height is removed. This gives correct drawing and sampling of the color checker even in skewed or rotated positions, removing the necessity of performing rotating and perspective correction beforehand.

`apply_homography_scaling` is fixed to give the local scaling of areas based on the Jacobian determinant of the homography mapping. This gives correct scaling of the center circles in the checker grid. The previous implementation appeared to work at first glance but in some orientations shrinks the circles even if the sampling boxes are quite large.

Before this PR (master, ace7b26fc5f7186afbee8e920af972bacc35a780):
![colorchecker_bad](https://user-images.githubusercontent.com/5001906/104784985-1ee38100-5792-11eb-98b2-2d99dedf1a54.png)
In particular, the sampling boxes have bad aspect ratio and the symmetry lines are in the wrong place.

With this PR applied:
![colorchecker_good](https://user-images.githubusercontent.com/5001906/104785003-29057f80-5792-11eb-9e3f-4d42ce5e711b.png)

Please notice also the black sampling areas in the small preview image - these are drawn by the color checker extraction routine to indicate which pixels of the image are really sampled.

@aurelienpierre , out of curiosity: are the color checker patches extracted from the small preview image (top left in darkroom) or the large one in the center?

2021-01-15 22:39 UTC, aurelienpierre commented
> @aurelienpierre , out of curiosity: are the color checker patches extracted from the small preview image (top left in darkroom) or the large one in the center?

The small thumbnail or the top left.

2021-01-15 22:41 UTC, flannelhead commented
> > @aurelienpierre , out of curiosity: are the color checker patches extracted from the small preview image (top left in darkroom) or the large one in the center?
> 
> The small thumbnail or the top left.

Alright. Does this give sufficient accuracy? I trust you have verified it (and it works really well, I'm really impressed by the profiling feature so far). I was just wondering if there is additional accuracy to be gained from using the full image.

2021-01-15 22:57 UTC, aurelienpierre approved these changes
Not tested, but code looks good and perspective fit is indeed more accurate. Thanks !

2021-01-15 23:00 UTC, aurelienpierre commented
> Alright. Does this give sufficient accuracy? I trust you have verified it (and it works really well, I'm really impressed by the profiling feature so far). I was just wondering if there is additional accuracy to be gained from using the full image.

The thumbnail is a fixed-sized 1100×1100 px (or close) image, while the main preview is dynamically-sized to screen, so accuracy should be enough and anyway it's more predictable.

2021-01-16 08:00 UTC, TurboGit approved these changes
Works for me, Thanks!

2021-01-16 08:05 UTC, TurboGit requested changes
My only comment about the code would be to avoid using double and use float everywhere. We have made lot of clean-up recently in different part of the code to avoid mixed float.

2021-01-16 09:56 UTC, flannelhead commented
> My only comment about the code would be to avoid using double and use float everywhere. We have made lot of clean-up recently in different part of the code to avoid mixed float.

Fixed the commit to not introduce new `double`s in `channelmixerrgb`. The homography calculation routines still use `double` because that's the original typing there. Perhaps another PR could be made to convert all those to `float`.

2021-01-16 09:59 UTC, flannelhead commented
Regarding labels: `scope: UI` and `bugfix` would probably be more accurate here, I think.

2021-01-16 10:00 UTC, TurboGit commented
Yes, I meand UI and not CLI.

2021-01-16 10:01 UTC, TurboGit commented
> The homography calculation routines still use `double` because that's the original typing there. Perhaps another PR could be made to convert all those to `float`.

Would be nice, yes please.

2021-01-16 10:31 UTC, aurelienpierre commented
I would maybe let the homography intermediate computation as double. This kind of matrix solve can backfire if the matrix is poorly conditionned, so it's safer as double.

2021-01-16 10:33 UTC, merged

2021-01-16 10:35 UTC, TurboGit commented
> I would maybe let the homography intermediate computation as double. This kind of matrix solve can backfire if the matrix is poorly conditionned, so it's safer as double.

Ok, but the parameter `const double *` should be moved to float and the return value which is a float you be using internally an fabsf() to create the final values. An internally ok to let double.

2021-01-16 11:10 UTC, flannelhead commented
Yep, I agree with @aurelienpierre  - at least`get_homography()` should use `double` internally for the Gaussian elimination. The forward computations `apply_homography` and `apply_homography_scaling` would probably be fine using `float` also internally.