metadata: add double-click + reset button to reset prefs
darktable-org/darktable pull request #7905
Opened 2021-01-17 12:56 UTC by phweyland

- double-click on label to reset the metadata
- button reset to set default prefs (metadata visible and private)

Could be revised following conclusions of #7859.

2021-01-18 10:53 UTC, TurboGit requested changes
A memory leak to fix.

2021-01-18 10:53 UTC, TurboGit commented on src/common/metadata.c
> +    char *setting = dt_util_dstrcat(NULL, "plugins/lighttable/metadata/%s_flag", name);
need to be freed

2021-01-18 11:29 UTC, phweyland commented on src/common/metadata.c
> +    char *setting = dt_util_dstrcat(NULL, "plugins/lighttable/metadata/%s_flag", name);
Yes! I fix that.

2021-01-18 11:34 UTC, phweyland commented
Relative to discussion in #7859 ...

If I follow our both statements I should make the following changes to this module:
- remove clear button and replace it by reset button (=> metadata values)
- add a reset button in the module pref dialog (=> metadata visibility, ...).

How does that sound ?

2021-01-18 13:15 UTC, TurboGit commented
> How does that sound ?

Correct on both counts to me.

2021-01-18 14:05 UTC, phweyland commented
I've disabled the reset button, added a "default" button in prefs dialog.
For the user, the advantage is to be able to cancel the reset action if he doesn't feels secure.

If this is ok like this, I'll do the same for metadata_view for consistency.

2021-01-18 17:57 UTC, TurboGit commented
> I've disabled the reset button, added a "default" button in prefs dialog.

Hum... I still prefer having the reset button to clear the entries. We have a clear button [apply] that clearly shows that unit it is clicked the metadata won't be affecting the selected images.

2021-01-19 14:39 UTC, phweyland commented
> I still prefer having the reset button to clear the entries.

I had a preference for my last proposal, but this is good too. Back to first solution without memory leak.

2021-01-19 14:53 UTC, TurboGit reviewed
The reset button does nothing on my side with this last version.

2021-01-19 15:09 UTC, phweyland commented
Are you sure ? It works for me.
It set back visibility and private flags to default values.
But doesn't touch to metadata values of the selected images.

2021-01-19 15:37 UTC, TurboGit commented
> But doesn't touch to metadata values of the selected images.

Ok, so we have misunderstanding. I prefer a version I tested some time ago plus the proposal you had partly implemeneted IIRC:
- reset button : clear all metadata fields
- the [clear] button can then be removed
- on the metadata settings dialog a new button is added to reset to default values (I'm sure I had seen / tested that).

This seems more consistent.

2021-01-19 15:39 UTC, TurboGit commented
The point is that really reset button should clear what is visible or at least at the same level but not into sub-dialog.

2021-01-19 17:36 UTC, phweyland commented
Should be better now :wink:

2021-01-19 22:24 UTC, TurboGit commented
> However I've commented the acceleration for clear button. Is there an equivalent for reset button ?

Yes, all reset button can be assigned a key in the accels editor.

2021-01-19 22:25 UTC, TurboGit approved these changes
Thanks !

2021-01-19 22:25 UTC, merged