Show subfolders using Shift-Click like tags
darktable-org/darktable pull request #7983
Opened 2021-01-24 09:21 UTC by quovadit

suggestion to fix #4976

Using the same logic as tag/geotag, folders show only current level by default, only subfolders using ctrl-click and current+subfolders using shift-click

2021-01-28 18:17 UTC, TurboGit commented
This breaks the feature where shift-click was used to go from folder to filmroll.

2021-01-28 18:18 UTC, TurboGit requested changes
Need to find a way to keep the go-to filmroll feature.

2021-01-28 19:15 UTC, quovadit commented
In tagging module we have 'rightclick' > 'go to tag collection'

2021-01-29 14:22 UTC, phweyland commented
maybe ctrl-shift-click for folder<->filmroll come and go ?

2021-01-29 22:21 UTC, quovadit commented
I added ctrl-shift-click for the goto filmroll/folder function

2021-02-06 17:44 UTC, TurboGit requested changes
Another little glitch, when you go from filmroll ro folder the folder is selected/highlighted. When you go from folder to filmroll the filmroll is not selected/highlighted.

2021-02-06 17:45 UTC, TurboGit commented on src/libs/collect.c
> +      // go to corresponding folder collection
indentation looks incorrect here.

2021-02-07 10:12 UTC, quovadit commented
I fixed the indentation

@TurboGit : The selection problem when navigating to filmroll was already there in #7385 
@phweyland : do you have an idea how to fix that?

2021-02-07 14:21 UTC, phweyland commented
> do you have an idea how to fix that?

When you click on the corresponding line in recent collections that works properly ...

You could make a try with :

`  dt_collection_update_query(darktable.collection, DT_COLLECTION_CHANGE_NEW_QUERY, NULL);`

2021-02-08 17:31 UTC, TurboGit approved these changes
All good now to me. Thanks.

2021-02-08 17:31 UTC, merged