geotagging: improve timezone ui
darktable-org/darktable pull request #8007
Opened 2021-01-26 19:18 UTC by phweyland

Fixes #3887

- move timezone from file chooser dialog to plugin
- replace combobox by an entry with completion

However that doesn't work perfectly.
The routine _match_selected_func() is not necessary (does what is done per default) but shows what does not work.
It is called correctly when one clicks on an element of the list.
But if one selects this list element with arrow keys and enters return, this routine is not called.
I can see also that "entry" continues to capture the keys when one moves on the list.

Should be compared to ctrl-t behavior where both "mouse click" and "return" on the list element valid this element.

Any help is welcome.

2021-01-26 21:46 UTC, phweyland commented
Moving signal connect "key-press-event" after completion connection solves the issue.
Fixed also tagging entry completion.

2021-01-28 09:11 UTC, TurboGit requested changes
I would also record and restore the time zone in the entry across sessions.

2021-01-28 10:58 UTC, phweyland commented
> I would also record and restore the time zone in the entry across sessions.

Of course. But that works for me.
As for tags, selecting a value in the list, presets the entry with that value, but doesn't valid the entry. One needs to key once more "enter" to validate. Could that explain your finding ?

2021-01-28 15:20 UTC, TurboGit commented
>  Could that explain your finding ?

Good catch ! That's exactly the issue :)

2021-01-28 15:20 UTC, TurboGit approved these changes
All good to me, thanks!

2021-01-28 15:21 UTC, merged