guided_filter.c: consolidate and optimize box-mean filters
darktable-org/darktable pull request #8045
Opened 2021-01-31 07:55 UTC by ralfbrown

These were not previously merged with the other functions in box_filters.c because they use Kahan (compensated) summation instead of simple addition -- quite a bit slower, but eliminates roundoff.

```
0025-exposure-guided-filter
Thr     AVmstr  AVpr    (%ch)
  1      13.1526 11.7020 -11.0%
  2      6.9748   6.1888  -11.3%
  4      3.7882   3.4310  -9.4%
  8      2.1768   2.0352  -6.5%
 12     1.6590   1.6014  -3.5%
 16     1.4388   1.4218  -1.2%
 24     1.2420   1.2670  2.0%
 32     1.1976   1.2050  0.6%

0026-haze-removal
Thr     AVmstr  AVpr    (%ch)
  1      4.7982  4.0132  -16.4%
  2      2.6572  2.2402  -15.7%
  4      1.5042  1.2784  -15.0%
  8      0.9024  0.7956  -11.8%
 12     0.7052  0.6380  -9.5%
 16     0.6132  0.5642  -8.0%
 24     0.5366  0.5164  -3.8%
 32     0.5132  0.5050  -1.6%
```

2021-02-02 07:32 UTC, TurboGit requested changes
Needs some adjustment after merging another PR:

```
/home/obry/dev/builds/darktable/build/src/src/common/eaw.c: In function ‘eaw_dn_decompose’:
/home/obry/dev/builds/darktable/build/src/src/common/eaw.c:670:22: error: invalid operands to binary + (have ‘float’ and ‘void *’)
  670 |       sum_squared[c] += dt_get_bythread(squared_sums,scratch_size,i)[c];
      |                      ^~
compilation terminated due to -Wfatal-errors.
```

2021-02-02 14:00 UTC, ralfbrown commented
Fixed.  The underlying cause is that `__builtin_assume_aligned` doesn't preserve the pointer type, instead casting it to `void*`.  C will happily assign that to a `float*` without an explicit cast, but indexing obviously doesn't work.  C++ complains about the type mismatch.

2021-02-02 16:11 UTC, TurboGit commented
With this PR I have three tests with segmentation fault:

- 0020-denoise-nlmeans
- 0027-denoiseprofile-nlmeans
- 0035-multiple-modules

2021-02-02 22:23 UTC, ralfbrown commented
Fixed.  See commit message for details.

2021-02-03 20:30 UTC, TurboGit approved these changes
Nice fix ! All good now, thanks!

2021-02-03 20:31 UTC, merged