Prefere shallow git copies
darktable-org/darktable pull request #8146
Opened 2021-02-08 14:42 UTC by deric

With huge git changes it's usually not necessary to clone the whole
repository, only latest state. Also for submodules it's not necesary
to have the full history when the submodule is fixed to certain commit.
This might speedup CI builds and save some bandwidth and space on HDDs.

`git clone --depth 1` will be much faster, in fact it might save 1-2GBs on disk :)

2021-02-08 16:27 UTC, TurboGit requested changes
We don't want that in .gitmodules by default as this will hinder work for all developers.

2021-02-10 11:11 UTC, deric commented
@TurboGit I understand, though committing code directly into submodule is not an ideal workflow. I find it much safer to update submodule to a certain commit, but develop the submodule in another git copy

2021-02-11 16:39 UTC, TurboGit approved these changes
Thanks !

2021-02-11 16:39 UTC, merged

2021-02-11 16:41 UTC, TurboGit commented
>  I find it much safer to update submodule to a certain commit, but develop the submodule in another git copy

Well for the integration test I prefer changing the sub-module, running the test and then commit/push if all good. Having a separate clone won't be as handy even if one can pull from a local clone.