masks : make the samples aware of distortions
darktable-org/darktable pull request #8682
Opened 2021-04-15 09:55 UTC by AlicVB

This fix #8677 

The goal is to have a full "what we get is what we see" for drawn masks, as currently the "sample" form before creating it for real isn't distorted.

What need to be done : 
- circle sample (OK)
- ellipse sample (already done in current master)
- gradient sample (TODO)
- correct source drawing for cloning forms (not only samples) (TODO)

Once that in place and the bug in shift fixed (see #8676) drawn masks and cloning should be way easier to use and understand (more predictable)

That won't solve the "I want TRUE circle whatever the distortions" part (I have some other ideas to solve that, though)

2021-04-15 11:54 UTC, TurboGit commented
@AlicVB : Thanks for stating this project !

2021-04-15 16:04 UTC, AlicVB commented
Now circles, ellipses and gradients samples are distorted "on the fly" :)
So, you get the exact mask that is shown in the preview.

Still the source of cloning to implement...

2021-04-15 16:57 UTC, elstoc commented
@AlicVB works great for "creating" masks. Can you implement it for adjusting them too?

2021-04-15 17:06 UTC, AlicVB commented
@elstoc : added to the TODO :)

2021-04-15 23:58 UTC, aurelienpierre commented
I guess we want to parallelize the IOP `distort_transform()` and `distort_backtransform` with that too, don't we ? (I can work on that).

2021-04-16 10:21 UTC, AlicVB commented
@aurelienpierre : you're right, that would be great ! thanks for the proposal, as I've almost no experience in this area (not to speak about the amount of work still needed here and on #8676)

2021-04-16 10:47 UTC, AlicVB commented
I've just added some commit to get the source drawings with the right distortions. (only implemented for circle and ellipse atm)
For the record, here is what happen : 
- cloning algos (spots and retouch) works, obviously on the input image reference of the module.
- they get a raster masks of the target + the shift between source center and target center.
- each pixel of the target masks is replaced by the pixel at position - shift

That means that in order to have the right source mask in term of distortions, we need to do the following : 
1. get the points of the target masks at "input of module" reference (distorted by modules placed *before*)
2. shift all the points to get the points of the source masks (still in "input of module" reference)
3. distort this points by all the modules placed *after* to get the masks in final image reference (aka screen)

In term of computations, we add only the points shift in fact, and that cost about to nothing... (maybe we can even add some parallelizing here)

2021-04-16 18:18 UTC, AlicVB commented
This PR should now be ok for tests and review.
As said, all drawn masks should now correspond to you get at the end, whatever distortions there can be after or before, even during creation, dragging, editing...
And when using cloned form (spot or retouch) the source form also correspond to the real source.

Now the question : what do I broke ? :)

2021-04-16 18:40 UTC, elstoc commented
Looks ok with masks. With retouch there's some sort of misalignment when I have lens correction active - the source spot isn't coming from the right place though it seems to be the right shape. The following is retouch in "clone" mode.

![Screenshot_2021-04-16_19-37-38](https://user-images.githubusercontent.com/9555491/115069249-380fe100-9eeb-11eb-93a0-be1223854868.png)

If I turn off lens correction it's coming from the right place but obviously from a distorted image now:

![Screenshot_2021-04-16_19-38-50](https://user-images.githubusercontent.com/9555491/115069461-81f8c700-9eeb-11eb-856f-2b6a48d6baca.png)

2021-04-16 18:46 UTC, AlicVB commented
@elstoc : this is due to #8676 and was present in master too...
I've preferred to split the 2 things, as they are not related, and the 2 PR will be big enough to review ;) (we always need to be kind with the guys who pressed the merge button :-D)

2021-04-16 18:51 UTC, elstoc commented
Oh yeah so it is. Then this PR is fine!

2021-04-16 20:29 UTC, TurboGit commented
Just tested, this is great and indeed very pleasant to work with the forms being interactively deformed when placed or moved around. A really nice addition. Now I need to find some time to look at the code. We can certainly plan this for 3.6.

2021-04-16 20:34 UTC, TurboGit commented
@elstoc : I have added the documentation tag as I think we may add a little note somewhere on the documentation about those distortion to be a feature and why it is happening (a good and common example could be on the corner after lens correction). What do you think ?

2021-04-16 20:36 UTC, elstoc commented
I agree and I was thinking the same thing

2021-04-17 05:50 UTC, TurboGit requested changes
A first pass. I also think that we could add another // for in `_gradient_get_points()` which is slow.

2021-04-17 06:59 UTC, TurboGit commented
@AlicVB : if you don't fell comfortable with the // loop I can do them, just let me know.

2021-04-17 10:56 UTC, AlicVB commented on src/develop/masks/gradient.c
> +  float rot = atan2f(pts[3] - pts[1], pts[2] - pts[0]);
sadly, rot is adjusted after in line 243... We could eventually refactor the code, but I'm not sure it's worth the pain...

2021-04-17 10:58 UTC, AlicVB commented on src/develop/masks/circle.c
> +      // gui->creation_module = NULL;
good catch, in fact I should leave it as it was... the comment was just here for an aborted experiment...

2021-04-17 11:00 UTC, AlicVB commented
@TurboGit : thanks for the review. I've fix most of your comments, except the // loops : I think I will accept your offer here, as I've never done such things... but I will see how you do that, and try to learn :)

2021-04-17 20:11 UTC, TurboGit approved these changes
Thanks, tested again. All works ok. I'll commit the // for just after.

BTW this is a really nice work and it makes the feeling of using forms in distorted environment really great! Almost magic seeing the form distorted when flying over a liquify blob :)

2021-04-17 20:12 UTC, merged