iop:colorin: Correctly check return value
darktable-org/darktable pull request #8807
Opened 2021-04-28 12:35 UTC by cryptomilk

Correctly check return value of `dt_imageio_avif_read_color_profile()`

2021-04-28 12:38 UTC, cryptomilk commented
img->profile_size is set if `cp` is filled, the out parameter of dt_imageio_avif_read_color_profile.

Inspect with `git show -U20`

2021-04-29 09:31 UTC, TurboGit requested changes
Minor style fixes.

2021-04-29 09:31 UTC, TurboGit commented on src/iop/colorin.c
> +      dt_imageio_retval_t ret;
const dt_imageio_retval_t ret = dt_imageio_avif_read_color_profile(filename, &cp);

2021-04-29 09:31 UTC, TurboGit commented on src/iop/colorin.c
> +      if (ret != DT_IMAGEIO_OK) {
{ should be next line.

2021-04-29 09:33 UTC, cryptomilk commented on src/iop/colorin.c
> +      dt_imageio_retval_t ret;
Fixed.

2021-04-29 09:33 UTC, cryptomilk commented on src/iop/colorin.c
> +      if (ret != DT_IMAGEIO_OK) {
Fixed.

2021-04-29 10:50 UTC, LebedevRI commented
Presumably rawspeed changes weren't meant to be here.

2021-04-29 11:50 UTC, TurboGit commented
I'll merge manually removing the rawspeed update.

2021-04-29 11:52 UTC, closed without merging