Fix stupid mistakes for "very high CA" mode
darktable-org/darktable pull request #8864
Opened 2021-05-04 17:34 UTC by rawfiner

This mode actually worked pretty well considering the stupid mistakes I made...
The side effect was that the image was brighten, and was especially visible on blue sky.
Should be better now! :-)

2021-05-04 20:34 UTC, TurboGit requested changes
The vectorization should work fine as you are using aligned memory. But instead of using `dt_alloc_sse_ps()` please use `dt_alloc_align_float() `it is equivalent but better avoid using sse here as it is not an sse code path.

2021-05-04 20:34 UTC, TurboGit commented on src/iop/cacorrectrgb.c
> +        for(size_t c = 0; c < 4; c++)
you should be able to use: for_four_channels()

it is a macro that will vectorize this loop if possible.

2021-05-04 20:34 UTC, TurboGit commented on src/iop/cacorrectrgb.c
> +        for(size_t c = 0; c < 4; c++)
likewise

2021-05-05 05:29 UTC, TurboGit commented on src/iop/cacorrectrgb.c
> +        for(size_t c = 0; c < 4; c++)
EDIT: not possible as the loop is already inside a omp/simd section.

2021-05-05 05:29 UTC, TurboGit commented on src/iop/cacorrectrgb.c
> +        for(size_t c = 0; c < 4; c++)
EDIT: not possible as the loop is already inside a omp/simd section.

2021-05-05 05:30 UTC, TurboGit commented
@rawfiner : so the only needed changes is to `dt_alloc_sse_ps()`.

2021-05-05 06:11 UTC, rawfiner commented
I pushed the change, thank you for the review @TurboGit !

2021-05-05 09:18 UTC, TurboGit approved these changes
Looks good, thanks !

2021-05-05 09:18 UTC, merged