Improve grouped metadata
darktable-org/darktable pull request #8957
Opened 2021-05-13 20:15 UTC by vithom

Hello,

Here is a small improvement in the image information module to display the result of the metadata concatanation.
![Capture d’écran de 2021-05-13 22-10-22](https://user-images.githubusercontent.com/74423292/118181759-7213ca80-b438-11eb-8f4c-ccb629fc9836.png)
As the exemple above, it displays the value of the metadata if all selected images share it or it displays "<various values>" if they differ.

2021-05-16 09:25 UTC, vithom commented
@TurboGit : Be careful, there will be conflicts with #8979. I don't know which one is better to integrate before.

2021-05-16 19:46 UTC, AlicVB approved these changes
Works great on my side. No real perf issues, even with a 90K images selection !
Great work !

2021-05-16 19:46 UTC, AlicVB commented on src/libs/metadata_view.c
>        // Still -1 => no selection in progress
update comment ?

2021-05-16 22:32 UTC, vithom commented on src/libs/metadata_view.c
>        // Still -1 => no selection in progress
Yes, updated. Thanks.

2021-05-16 22:35 UTC, vithom commented
I would have liked to update the french translation but I haven't poedit installed on my machine.
Translation for french could be "<valeurs multiples>"

2021-05-17 19:47 UTC, TurboGit requested changes
First review, I'm going to test now.

2021-05-17 19:47 UTC, TurboGit commented on src/libs/metadata_view.c
> +  if (img->film_id == -1)
no space between if and (

2021-05-17 19:47 UTC, TurboGit commented on src/libs/metadata_view.c
> +  for (int32_t md = 0; md < md_size; md++)
likewise

2021-05-17 19:47 UTC, TurboGit commented on src/libs/metadata_view.c
> +    if (skip[md] == TRUE)
likewise ... please checks for all occurences

2021-05-17 19:47 UTC, TurboGit commented on src/libs/metadata_view.c
> +    switch (md)
likewise

2021-05-17 19:47 UTC, TurboGit commented on src/libs/metadata_view.c
> +          (void)g_snprintf(text, sizeof(text), "%.2f m", (double)img->exif_focus_distance);
As we are at it we probably want "%.2f m" to be translatable _("%.2f m") as in Russian IINM m is M.

2021-05-17 19:52 UTC, TurboGit reviewed
BTW, also we can remove the SHOW_FLAGS #define as we can now select the columns to display on the metadata view module. So this is superfluous.

2021-05-18 20:17 UTC, vithom commented
I've corrected the remarks.

2021-05-19 06:40 UTC, TurboGit approved these changes
Looks good to me now. Thanks!

2021-05-19 06:41 UTC, merged