Safer gphoto2 device handling
darktable-org/darktable pull request #9011
Opened 2021-05-20 16:02 UTC by jenshannoschwalm

Recently there have been two issues each showing a different bug in dt’s gphoto code.

#8967 describes a situation where dt tries to initialize a device and if not successful does so again and again
This “fighting” for the device leads to other apps de- and reconnecting.

#8974 shows a fundamental flaw of the current implementation. When doing a hot unplugging the device handler is left in a broken state.

This pr re-implements the device handling. In more detail:
1. every device that has been detected by gphoto (except disks) is “remembered” in one of two lists.
   List A holds all devices that have been successfully initialised
   List B holds all devices that are currently not used by darktable, whatever the reason is.

2. Reasons for being in list B are:
   a) could not be initialized
   b) device has been found uninteresting (no import or tethering)
   c) device has been unmounted (more on this later)

3. The background thread (BT) looks for available - physically connected - devices every 4 seconds while
   in lighttable mode and deletes all devices from both lists that are not connected any more.
   This can be either a hot unplugging (this should be avoided by the user) - so a removal from list A -
   or a device currently not used - so from List B

4. The BT looks for all connected devices, takes care a device in not already in List B and if it’s really
   a new device it tries to initialize the device and adds it either to List A or to List B

How do we avoid hot-unplugging?
We could give every device an unmount button, this might be overseen or forgotten by the user.
Also it would result in more buttons for each camera, something I really dislike.
So I chose to implement an automatic device unmounting after ~15 seconds.

If a device is un-mounted it is moved from List A to List B and gets a remount button instead of the
tethering / import buttons. This is per-device.

What about loading files from a camera or tethering?
In both cases we must not unmount!
  - For tethering we are safe because of not-in-lighttable-mode
  - While the import selection box is open we bypass the updater in the BT
  - For each device the importing job gets a don’t unmount ticker which is cleared in the job cleanup code.

Probably Fixes #8967
Fixes #8974

I tested as good as I could, unfortunately I have no tethering capable camera available.
So further testing by others with such cameras is strongly required (although i am pretty sure), @TurboGit and @johnny-bit had tested tethering before.

There is one thing i would like to get confirmed / discussed. We have key_accels for tethering/import_from_camera and now also for remounting. This is a bit tricky insofar as the key is connected to the last camera connected (this has been this way before). Are we sure we want this? Personally i think we shouldn't have key_accels for these per-device-buttons at all.

Some minor bugs while working on the code have been fixed, also some renaming of structs/elements for a better readability of the code.

Please use the –d camctl option, it’s output has been made less verbose (removing redundant information)

2021-05-20 21:00 UTC, TurboGit commented
I tried testing this tonight but because of #9013 it is not possible at the moment.

Note thought that I'm pretty sure that there is no detection of camera with this patch. The bug in #9013 comes after that. So I suppose that what I saw is correct. When I plug the camera there is no message on screen about new camera. There is no message on the console either.

2021-05-20 21:05 UTC, TurboGit commented
Ok, indeed there is an issue:

- connect the camera
- it gets mounted by the os, and we get on the console:
`27,719978 [camera_control] failed to initialize Nikon DSC D850 on port usb:002,006, likely causes are: locked by another application, no access to udev etc.`
- then I unmount from OS
- and nothing happens.... no more line on the console

2021-05-20 21:05 UTC, TurboGit requested changes
issue with camera detection first time.

2021-05-21 04:12 UTC, jenshannoschwalm commented
I don't fully understand this
```
it gets mounted by the os, and we get on the console:
27,719978 [camera_control] failed to initialize Nikon DSC D850 on port usb:002,006, likely causes are: locked by another application, no access to udev etc.
then I unmount from OS
and nothing happens.... no more line on the console
```

For me this is so far exactly what it should be like because we want to avoid any device fighting. What you should see is something like this
![Bildschirmfoto von 2021-05-21 06-02-03](https://user-images.githubusercontent.com/50982232/119080547-8fc5ce80-b9fa-11eb-8744-cfca7468ac05.png)

This connect button should be there whenever a device is physically connected but not used by dt. If you do **not** see this button, that would be wrong. Otherwise - click on it to connect dt to the device and within a few sec you should see

![Bildschirmfoto von 2021-05-21 06-10-11](https://user-images.githubusercontent.com/50982232/119080915-4164ff80-b9fb-11eb-8328-a15a44121417.png)

2021-05-21 16:43 UTC, jenshannoschwalm commented
Pinging @phweyland as from my understanding you did much of the imported work. While working on this i got into a few peculiarities with importing from gphoto devices. I didn't fully test or understand but in some situations we can't get all files in a directory - there is no message about filling the list. This **might** be related to a) the device not being able to handle directories or b) no preview support and no proper error testing in the file selection part for the import. I added some capabilities checks for cameras you might want to use or think about.

2021-05-21 18:50 UTC, phweyland commented
Hi Hannon, I've mostly reshuffled the cards especially on the ui side, trying not to change/disturb the camera handling.
gphoto2 seems to be limited (no date/time info for example) but I have not gone very far to master its features. 
But sure, I'll try to understand what you try to achieve and see if I can help.

2021-05-22 06:56 UTC, phweyland commented
I get the same scenario as Pascal.

```
0,882194 [camera_control] creating new context 0x55f782c3e170
0,889078 [camera_control] loaded 2498 camera drivers.
5,299221 [camera_control] loaded 12 port drivers.
5,303821 [camera_control] 0 cameras connected
13,533345 [camera_control] loaded 13 port drivers.
13,540679 [camera_control] 1 cameras connected
13,542703 [camera_control] failed to initialize Nikon DSC D300s (PTP mode) on port usb:001,010
13,542710 [camera_control] failed to initialize Nikon DSC D300s (PTP mode) on port usb:001,010, likely causes are: locked by another application, no access to udev etc.
34,121585 [camera_control] loaded 12 port drivers.
34,125568 [camera_control] 0 cameras connected
34,125578 [camera_control] remove Nikon DSC D300s (PTP mode) on port usb:001,010 from ununsed camera list
```

2021-05-22 07:22 UTC, johnny-bit commented
I generally love the idea and approach :+1: but...

> How do we avoid hot-unplugging?
We could give every device an unmount button, this might be overseen or forgotten by the user.
Also it would result in more buttons for each camera, something I really dislike.
So I chose to implement an automatic device unmounting after ~15 seconds.

15 seconds feel both loooong when you want to safely unplug and awfully short when trying to use camera for either import or tether... And also I'm one of those weirdos that does safely unplug devices ;) so for me button would be great ;) If no button then maaaybe some form of visual indication about when the device will be unmounted due to inactivity?



As for CI: LLVM CI yells about mutex not being held...

```
src/common/camera_control.c:934:41: fatal error: expecting mutex 'camctl->lock' to be held at start of each loop [-Wthread-safety-analysis]
      dt_camera_t *cam = (dt_camera_t *)citem->data;
                                        ^
src/common/camera_control.c:808:3: note: mutex acquired here
  dt_pthread_mutex_lock(&camctl->lock);
  ^
src/common/dtpthread.h:108:34: note: expanded from macro 'dt_pthread_mutex_lock'
#define dt_pthread_mutex_lock(A) dt_pthread_mutex_lock_with_caller(A, __FILE__, __LINE__, __FUNCTION__)
                                 ^
```

2021-05-22 17:58 UTC, jenshannoschwalm commented
Ok, i think i know whats wrong.

Just to get a feedback for the UI, what solution would be better
1. Have the automatic mounting if a new device is found and get it unmounted after some time and allow remounting as proposed initially in this pr
2. Look for devices in the backthread and allow **active mounting** of found devices. Mounted device have buttons for import and tethering **plus** a button to unmount, automatic unmounting would not be "necessary" as the user is in control of mount / unmount

Let me know, both solutions would be fine for me.

2021-05-22 20:46 UTC, johnny-bit commented
I'd vote for option 2 - it's a bit more explicit. I have ideas, but I don't want to do feature creep or other garbage ;)

> EDIT: btw, there is also some harware managing involved :-)

methinks labels needs slight redefinings. the `scope:hardware` label says it's abot gpus & printers ;)

2021-05-22 21:55 UTC, phweyland commented
I vote for option 2 too. Only the user knows what will be his next step.

2021-05-23 09:19 UTC, jenshannoschwalm commented
New feedback desired :-)

2021-05-23 15:50 UTC, phweyland commented
All good for me !

2021-05-23 16:13 UTC, jenshannoschwalm commented
> All good for me !

User interface, mounting & unmounting, tethering and importing? Cool! 

If Pascal and Hubert can confirm i would like to get this merged ...

Although, there **is** an outstanding issue probably related to access rights for PTP device. The initialize code works right but gphoto2 functions might not be allowed to read from the device resulting in

1. an error condition probably not checked correctly in the import code and
2. removing the camera from the active list in an uncontrolled manner.

See `_error_func_dispatch25` in `camera_control.c`

This is old code and i am yet not sure how to handle that fully correct. I will further investigate before doing another pr - maybe it will also require mods on the import code.

2021-05-23 16:24 UTC, phweyland commented
> User interface, mounting & unmounting, tethering and importing?

Yes, even camera switch off. The only thing is that the response time of mount / unmount buttons can seem a bit long (2 sec ?).

> Although, there is an outstanding issue probably related to access rights for PTP device. 

With my D300s (PTP) I haven't experienced any issue.

2021-05-23 16:25 UTC, jenshannoschwalm commented
> With my D300s (PTP) I haven't experienced any issue.

I have this if using a cellphone where i have to confirm access to the device on the phone and i do that late. Phone gets mounted but when reading the files there is an error.

2021-05-23 16:28 UTC, jenshannoschwalm commented
> of mount / unmount buttons can seem a bit long (2 sec ?)

ok. i think this could also be done in another pr, maybe checks on computer performance (>4= cores & >=16GB of memory could allow faster polling?)

2021-05-23 16:33 UTC, phweyland commented
Maybe a small glitch.
1. launch dt
2. switch on camera => OS browser sees the device and dt shows the button [mount].

But [mount] does not do anything as long as I haven't unmounted the device on OS browser side. Isn't the button shown too early ? Or a tooltip to suggest to unmount first in OS browser if the the button doesn²t work. Or/and keep it deactivated as long as it's not done.

2021-05-23 16:37 UTC, johnny-bit commented
THIS IS AWESOME NOW!

It's "all good from me" with 2 liiiittle annoyances. you might want to ignore it as a feature creep or whatever:

1. When clicking <kbd>mount camera</kbd> when camera is grabbed by something outside of darktable, nothing happens in UI but there's this in log: `failed to initialize Canon EOS 77D on port usb:002,004, likely causes are: locked by another application, no access to udev etc.`. So If user clicks <kbd>mount camera</kbd> it'd be cool if same message appeared as a simple dialog box. eg message: "Cannot mount Canon EOS 77D, most likely it's locked by another application or there are some permission issues. Unmount camera from other applications and try again" and let it have <kbd>OK</kbd> button :)
2. mount/unmount seems to lag a bit, probably via pooling mechanism. My "solution" in terms of UI would be - if user clicks on "mount" make button disabled till everything's mounted (or there's an error) and if clicking "unmount" do the same for import/tether/unmount buttons. This'll be probably best way to indicate to user "YEAH, registered request, processing" :)

IMO this MUST land in 3.6 because UX is awesome :)

2021-05-23 17:09 UTC, jenshannoschwalm commented
Ok, you both point into the same direction, i will fix all mentioned glitches either here or in another pr depending on time of this getting merged. No time coding today, likely tomorrow.

2021-05-23 18:23 UTC, johnny-bit commented
> Ok, you both point into the same direction

Just FYI - point 1 (message to user that camera i mounted elsewhere) is more importanter for me than point 2 :)

> No time coding today, likely tomorrow.

Chill - I love this change, so for me it could land as-is or with tweaks.

2021-05-24 06:13 UTC, jenshannoschwalm commented
Ok. This should do it now,
1. ui responsiveness is much better without increasing cpu load
2. Messages about failing initialize or boring cameras as popups.

2021-05-24 08:30 UTC, phweyland commented
Great. All works for me. :+1:

2021-05-24 08:32 UTC, johnny-bit commented
Methinks it's perfect now :)

(just a note after merging: plz add documentation:pending tag :) )

2021-05-24 19:18 UTC, TurboGit approved these changes
All good, works good on my side. Mounting/Unmountting and even disconnecting the cable and mounting it again after that.

2021-05-24 19:18 UTC, merged

2021-05-24 22:00 UTC, elstoc commented
@jenshannoschwalm: I've added some documentation for this in https://github.com/darktable-org/dtdocs/commit/7147683695b66fb8f65d083908c3f626ddd897bc, https://github.com/darktable-org/dtdocs/commit/1b162d37c0d0c6adea5dac082e408534edcc30b6 and https://github.com/darktable-org/dtdocs/commit/ed03751cb905e6a78c04cc18d5b12e93a2958322 (in retrospect I probably should have done a PR!). Please can you give my changes a quick check to make sure I haven't missed anything.