collections: speed up display of tags for tag filter
darktable-org/darktable pull request #9017
Opened 2021-05-21 04:13 UTC by ralfbrown

I was doing some tag maintenance on my personal image library and noticed some dramatic slowdowns now that it's gotten large....

Found and removed an extraneous widget refresh, and sped up the underlying SQL query.  I know enough about SQL to be dangerous, so somebody should check it to ensure I haven't introduced any corner case breakage.  It does work properly on my library, including combining multiple filter rules, though there is a pre-existing display bug where the count of untagged images is the count in the entire library even when a previous rule has narrowed the pool under consideration.

**Results**
On a library with 219k images and 668 distinct tags (667 case-folded), the previous code took 0.86 seconds to execute the SQL query for
populating the Collections module's tree view of tags in case-sensitive mode and 3.6 seconds in the default case-folded mode.

Flipping around the subquery for the UNION clause to perform the string comparison on data.tags.name to generate a list of tag IDs which can then be tested with an integer (set) comparison instead of a string comparison for every instance of a tag attached to an image saves 0.14 seconds in both case-sensitive and case-folded modes.

Performing an equivalent flip to perform the JOIN with tag names only after de-duplicating the tag IDs reduces the execution time further to 0.66 seconds in case-sensitive mode and 0.67 seconds in case-folded mode.

**Additional notes**
There are further occurences of the pattern of JOINing data.tags and then comparing the name which could be flipped to generating a list of tag IDs from data.tags for use in a WHERE clause.  I'll take a look at them after verification that I haven't broken anything here.

When the Collections module is collapsed, it would make sense to simply ignore the update call resulting from a COLLECTION_NEW_QUERY or COLLECTION_UPDATED signal to avoid adding unnecessary lag to other user actions.  We'd need to ensure that the update call is then issued when the module is expanded.

2021-05-21 09:11 UTC, TurboGit commented
Nice! Let's try to have this in 3.6. I'll review and asked @phweyland to review also as pretty good in SQL.

2021-05-21 10:29 UTC, phweyland commented
Nice indeed, making the string comparison only on already filtered/reduced list should speed up things.
I've compared the queries and haven't found any discrepancy.
If you let me some time, I'll make some tests later today.

2021-05-21 14:15 UTC, phweyland requested changes
I've made some comparisons with the previous versions and I have not found any difference.
I haven't made any speed measurement.
Apart the suggestion above all good for me.

2021-05-21 14:15 UTC, phweyland commented on src/libs/collect.c
> +                                       "    (SELECT id FROM data.tags WHERE"
I would suggest to replace this SELECT by the darktable tags table:
`"   WHERE ti.tagid NOT IN memory.darktable_tags)"`

2021-05-21 22:36 UTC, ralfbrown commented
I hadn't been aware of `memory.darktable_tags`.  Using it does indeed save a bit of time (now down to 0.63-0.64 seconds).  When I looked at the code manipulating it, I was worried that the lazy init/update would cause an issue, but apparently there's always an invocation of a function that calls the init before the treeview is built.  OTOH, replacing the other occurrence of the substring check that I found with `memory.darktable_tags` resulted in an incorrect thumbtable for the "tag: untagged" filter until I switched to darkroom and back out to lighttable, so I'm leaving that one unchanged.

2021-05-22 05:45 UTC, phweyland commented
yes, I was starting with dt when I implemented this. The initialization should be made at the start of darktable.  I'll try to fix it.

2021-05-22 05:46 UTC, phweyland approved these changes

2021-05-22 07:25 UTC, TurboGit approved these changes
Thanks !

2021-05-22 07:25 UTC, merged