Fix brush point access with wraparound
darktable-org/darktable pull request #9145
Opened 2021-06-03 16:12 UTC by johnny-bit

Fixes #9142 

The list access could have problems when accessing points after last element. use `g_list_next_wraparound` helper to get around the problem :)

thanks to @ralfbrown for essentially handing the solution (i had bit of time to test)

2021-06-03 20:41 UTC, MStraeten commented
the segfault is gone but instead of inserting a new node in the segment where ctrl+click is done a new endpoint is appended at this place.

2021-06-04 03:57 UTC, johnny-bit commented
Hmmm... Does the section you want to add node "highlights"? If not then it's a problem with node part detection...

2021-06-04 06:20 UTC, MStraeten commented
i don't need highlights - thats just because inkscape highlightes these.
the old behaviour inserting a node was the in the first sketch the red node - in the line segment between the blue nodes  a node is inserted by ctrl-click at the place the mouse pointer points on
this was broken by the commit introducing the segfault.

2021-06-04 06:24 UTC, MStraeten commented
ohh there is a further issue - i cant move the stroke around. 
i can select the whole stroke (not the segments)
selecting and moving nodes is fine indeed

2021-06-04 06:31 UTC, TurboGit requested changes
Indeed, no more crash but the node is not properly created.

2021-06-04 06:40 UTC, TurboGit commented
And there is another issue with the brush tool, we cannot move a single segment anymore. We can only move nodes.

2021-06-04 06:40 UTC, MStraeten commented
and also i cant move the whole stroke

2021-06-04 06:50 UTC, johnny-bit commented
Yeah, I now think this is wrong fix. The issue is rather at the brush stroke detection level, because it now doesn't detect paths or node points :/ i need to check if that's the case with all the masks or just brushes... Either way I'm most likely out of my depth here :/

2021-06-04 16:30 UTC, johnny-bit commented
Yeah, this approach is incorrect and actually gotta figure out how to properly highligh segment/node in brush path because it is currently NOT detected.

Closing

2021-06-04 16:30 UTC, closed without merging