report separate memory requirements for CPU vs GPU to reduce CPU tiling
darktable-org/darktable pull request #9272
Opened 2021-06-18 16:50 UTC by ralfbrown

Mitigates #5428.  Now that we have a mechanism for reporting memory requirements separately for the CPU and GPU code paths, take advantage of it.  Reporting the lower actual requrements for the CPU code path reduces tiling in low-memory situations and thus reduces the slowdown.

Additional memory savings are possible, but require more extensive changes that should wait until after 3.6.

2021-06-18 18:07 UTC, johnny-bit commented
Should this be for 3.6 milestone then?

2021-06-18 18:52 UTC, ralfbrown commented
If you want, but I'm not going to push for it.

2021-06-18 20:45 UTC, johnny-bit commented
Tested - I'd consider it a performance bugfix - when opencl is enabled but not used for the run due to different issues, the cpu path would then be faced with greater than required tilling which does pose problems with performance... I'll set for 3.6 since it seems 100% safe and correct.

2021-06-19 06:44 UTC, TurboGit commented on src/common/gaussian.c
> +size_t dt_gaussian_memory_use_CPU(const int width,    // width of input image
I think about in the CPU case you want to call this routine instead of duplicating the computation. This would make it clear that both are related.

2021-06-19 06:45 UTC, TurboGit commented on src/common/gaussian.c
> +size_t dt_gaussian_memory_use_CPU(const int width,    // width of input image
And for consistency with other parts of dt, I would use a _cl suffix for the OpenCL version and nothing for the CPU.

2021-06-19 06:46 UTC, TurboGit requested changes
Some minor changes.

2021-06-19 08:08 UTC, TurboGit approved these changes
Lot cleaner this way! Thanks.

2021-06-19 08:08 UTC, merged