preferences: only text should be translatable
darktable-org/darktable pull request #9330
Opened 2021-06-24 10:10 UTC by elstoc

resolves #7467

2021-06-24 10:11 UTC, elstoc commented
@TurboGit I think this is probably a good candidate for a 3.6.1 release - it's an issue I've seen reported a few times.

2021-06-24 10:28 UTC, parafin commented
Translation must not include */ after this change - won't "fuzzy" translations of old strings make it quite probable?

2021-06-24 10:48 UTC, elstoc commented
obviously the alternative is to fix the translations themselves but we can't guarantee this error won't creep back in again

2021-06-24 11:56 UTC, johnny-bit requested changes
`g_strconcat` results need freeing ;)

also - it'd be great to fix the translation files that have this error, just so that "fuzzy" translations won't catch that.

2021-06-24 11:56 UTC, johnny-bit commented on src/gui/preferences.c
> +      gtk_text_buffer_set_text(buffer, g_strconcat("/* ", _("ERROR Loading user.css"), " */", NULL), -1);
```suggestion
      gchar* css_error_msg = g_strconcat("/* ", _("ERROR Loading user.css"), " */", NULL);
      gtk_text_buffer_set_text(buffer, css_error_msg, -1);
      g_free(css_error_msg);
```

2021-06-24 11:56 UTC, johnny-bit commented on src/gui/preferences.c
> +    gtk_text_buffer_set_text(buffer, g_strconcat("/* ", _("Enter CSS theme tweaks here"), " */\n\n", NULL), -1);
```suggestion
    gchar* css_prompt = g_strconcat("/* ", _("Enter CSS theme tweaks here"), " */\n\n", NULL);
    gtk_text_buffer_set_text(buffer, css_prompt, -1);
    g_free(css_prompt);
```

2021-06-24 12:50 UTC, elstoc commented
It's possible that the broken translation itself has been fixed because I can't find an error in the po files. Still (I think) better to translate just the words if we can.

2021-07-03 09:42 UTC, TurboGit approved these changes
All good, thanks !

2021-07-03 09:43 UTC, merged