use gtk check menus to indicate choosen preset/blendmode
darktable-org/darktable pull request #9557
Opened 2021-07-17 11:24 UTC by johnny-bit

Fixes #3843

This PR makes use of gtk's native check menu functionality.

This makes choosen preset or blending mode stand out more in case the bold doesn't do it's job properly ;)

The way to get of squares in non-choosen menu items would be to use normal menu item for not choosen thingie, but i guess it's fine as is.

2021-07-18 20:37 UTC, Nilvus requested changes
I just like that. It remains only some CSS to improve that. I've made some tests and test on all themes to have some CSS code ok for all check point (actually in treeviews like copy/paste dialog window and so on presets with that PR). Should be good with this CSS:

```
diff --git a/data/themes/darktable.css b/data/themes/darktable.css
index 26b769bcf..f3feded5a 100644
--- a/data/themes/darktable.css
+++ b/data/themes/darktable.css
@@ -1831,7 +1831,7 @@ messagedialog .default  /* this show that a button in confirmation action pop-up
 button:hover,
 #add-color-button:hover,
 menuitem:hover,
-menuitem:hover > *,
+menuitem:hover > *:not(check),
 combobox window *:hover,
 radiobutton:hover label,
 #control-button:hover,
@@ -1930,9 +1930,11 @@ button:disabled,
 }
 
 /* Treeviews and filechoosers states */
-treeview check /* set specific background color about check buttons in treeviews like copy/paste dialog window */
+treeview check, /* set specific background color about check buttons like in copy/paste dialog window */
+menuitem check
 {
   background-color: @field_selected_bg;
+  border-color: @field_selected_bg;
 }
 
 treeview:not(#lutname) *:hover:not(check),
@@ -1960,17 +1962,17 @@ filechooser *:selected
   color: @field_selected_fg;
 }
 
-treeview check:selected
+treeview check:selected,
+menuitem check:selected
 {
   background-color: @button_bg;
   border-color: @plugin_bg_color;
 }
 
-treeview check:hover
+treeview check:hover,
+menuitem check:hover
 {
-  background-color: @bauhaus_bg_hover;
   color: @field_hover_fg;
-  border-color: @selected_bg_color;
 }
 
 filechooser checkbutton:checked
@@ -2638,7 +2640,7 @@ Details :
 }
 
 /* Set active menu items: needed for some Pango issues not rendering synthetic bold for all OS */
-.active-menu-item *
+.active-menu-item label
 {
-    font-weight: bold;
+  font-weight: bold;
 }
```
@johnny-bit: if this code is ok for you, just include it in your PR (that will avoid another PR to be tested and merged).

2021-07-18 20:39 UTC, Nilvus commented
And complete darktable.css file if needed with my CSS update proposal:
[darktable.css.txt](https://github.com/darktable-org/darktable/files/6836913/darktable.css.txt)

2021-07-18 21:01 UTC, johnny-bit commented
Thanks! added your css :)

2021-07-19 18:06 UTC, TurboGit approved these changes
Works for me ! Thanks for the team work.

2021-07-19 18:06 UTC, merged

2021-07-19 20:42 UTC, Nilvus commented
I just notice something here. I find all check buttons not correctly aligned vertically regarding label text beside. I find it better with:

```
menuitem check
{
  margin-bottom: 1px;
}
```

What I don't understand is that I find nothing in CSS that could explain that difference. It's a little one but visible. I don't really know Gtk code but on what I see on source code of this PR, I don't see anything that could add that difference. CSS code above is simple but I see it more as a workaround and so not the cleaner way. By default, with CSS we have (so top and bottom padding and margin on menuitem, check and label ones to 0), this should be correctly aligned by default. So, is there something in Gtk code (or something in CSS I miss) that could explain that difference? Or, we have no other ways than adding workaround above in this comment?

2021-07-19 20:45 UTC, Nilvus commented
To see the difference:

this PR:
![without](https://user-images.githubusercontent.com/45535283/126224957-13e42b01-0864-4c76-9c41-5d73a43dcc74.png)

with the workaround above:
![with](https://user-images.githubusercontent.com/45535283/126224997-fb46a59b-f024-40cc-9f04-94b24ffb8d65.png)

2021-07-20 05:09 UTC, johnny-bit commented
I have no idea... It's funny to note that i only see it with comparison, the 1px difference wouldn't bother me otherwise ;) So i think it deserves PR for css changes :)

2021-07-20 15:39 UTC, Nilvus commented
Ok. I even didn't notice it when testing your PR.
So, I will soon propose a PR.