vectorscope: add RYB option
darktable-org/darktable pull request #9904
Opened 2021-08-29 20:29 UTC by phweyland

fixes #9847. See this FR for more details.

This is inspired by "[Paint Inspired Color Mixing and Compositing for Visualization](http://vis.computer.org/vis2004/DVD/infovis/papers/gossett.pdf)" - Gossett.
As the Gossett model is not reversible, we keep his cube hues and use them to transpose the rgb <-> ryb data by spline interpolation.
This model compensates the orange expansion by compressing from green to red unlike the model proposed by Junichi SUGITA & Tokiichiro TAKAHASHI, in "[Computational RYB Color Model and its Applications](https://danielhaim.com/research/downloads/Computational%20RYB%20Color%20Model%20and%20its%20Applications.pdf)", which compresses mainly the cyan colors. This latest is also reversible and is used in the G'MIC functions.

As we talk of colors harmony I'm embarrassed by the color wash of the presented graph. Example:
![image](https://user-images.githubusercontent.com/23012047/131264431-a54cf32c-b6c6-4dab-982c-b2ece8f74abf.png)
compared to:
![image](https://user-images.githubusercontent.com/23012047/131264439-4d0d7225-db8f-4e77-8e78-b28b21c06246.png)
In the first image, it's impossible to identify the blue... The second image is far more aligned on the real colors of the image.
Thoughts ?

2021-08-29 20:41 UTC, Mark-64 commented
Can't build on Windows

```

../../src/libs/histogram.c: In function '_lib_histogram_process_vectorscope._omp_fn.0':
../../src/libs/histogram.c:321:19: error: '*((void *)&chromaticity+8)' may be used uninitialized in this function [-Werror=maybe-uninitialized]
  321 |   const float h = dt_fast_hypotf(*x,*y);
      |                   ^~~~~~~~~~~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.
```

2021-08-29 23:29 UTC, phweyland commented
> Can't build on Windows

Sorry, an oversight. Probably the same cause as for Travis error. Let's see if it is happier now.

2021-08-30 20:37 UTC, phweyland commented
rebased after 8441948

2021-08-30 21:49 UTC, Nilvus commented
On your screenshots, I agree that first screenshot is quite washed. But the second is probably a little too oversaturated. Maybe something between them would be the best. That was discussed a lot for vectorscope as you probably now in PR #9209 by @dtorop. So maybe some improvement remaining here.

2021-08-30 23:46 UTC, phweyland commented
> On your screenshots, I agree that first screenshot is quite washed. But the second is probably a little too oversaturated. Maybe something between them would be the best. That was discussed a lot for vectorscope as you probably now in PR #9209 by @dtorop. So maybe some improvement remaining here.

I'm afraid that everyone will have his own preferences. Histograms and waveform do not suffer being dimmed. From my point of view vectorscopes talk colors and I would prefer them as real as possible.

2021-08-31 12:50 UTC, MStraeten commented
the appearance is dependent to the selected theme: the background using a ...gray theme or even the ...dark theme reduces the contrast to the colors (it's quite contrasty in the ...darker theme)
But just darkening the background will result in an eye catching vercorscope because it's quite darker then approriate for the theme. In my option it's better to have the background color consistent to the theme - so nothing distracts from the image

2021-08-31 13:04 UTC, phweyland commented
> But just darkening the background will result in an eye catching vercorscope because it's quite darker then approriate for the theme

I can agree about this.

But I disagree about washing the colors of the wheel (colored background of the vectorscope).

2021-08-31 15:30 UTC, TurboGit commented
> But I disagree about washing the colors of the wheel (colored background of the vectorscope).

I agree with @phweyland, it makes the vectorscope mostly unusable.

2021-09-01 14:35 UTC, Mark-64 commented
I am afraid the rebase doesn't consider the changes introduced with #9866 and #9906. It actually reverts some of those changes.
Position of samples is not calculated correctly in RYB.
@TurboGit How can we fix this before merging this one? Or shall we do it after ?

2021-09-01 15:05 UTC, TurboGit commented
> @TurboGit How can we fix this before merging this one? Or shall we do it after ?

Strange that the rebase broke something ! How did you handle this, if you go to this branch and do a "git rebase master" (making sure master is updated to current commit) what happens? Do you have conflicts? If not the rebase should be fine, no?

2021-09-01 15:08 UTC, TurboGit commented
And anyway, there is no conflicts on this PR... So if I merge all should be fine. Was the washout colors fixed in this PR? (not tested yet, so asking...)

2021-09-01 16:17 UTC, phweyland commented
> Was the washout colors fixed in this PR? (not tested yet, so asking...)

No, I've let the current treatment of background vectorscope.
I've risen the topic to get opinion before touchng anything which was made just before.
I'm not sure we get a consensus on this. Maybe the solution would be to let the user saturate the vectorscope the way he likes.
Could be done in another PR. ?

2021-09-01 18:50 UTC, Mark-64 commented
Well I merged locally this PR with master and the changes in #9866 and #9906 are there, but this is not enough.
We have to add some code to find coordinates of primary sample an live samples in RYB, but it should not be difficult

2021-09-02 06:23 UTC, Mark-64 commented
We have to apply the same transformation from RGB to RYB to primary sample and live samples.

If I understood correctly the transformation, this part of _lib_histogram_process_vectorscope()
```

  // find position of the primary sample
  for(int k = 0; k < 3; k++)
  {
    switch(statistic)
    {
      case DT_LIB_COLORPICKER_STATISTIC_MEAN:
        RGB[k] = sample->picked_color_rgb_mean[k];
        break;

      case DT_LIB_COLORPICKER_STATISTIC_MIN:
        RGB[k] = sample->picked_color_rgb_min[k];
        break;

      case DT_LIB_COLORPICKER_STATISTIC_MAX:
        RGB[k] = sample->picked_color_rgb_max[k];
        break;
      default:
        fprintf(stderr, "[histogram] unsupported color picker statistics %i\n", statistic);
        break;
    }
  }

  dt_ioppr_rgb_matrix_to_xyz(RGB, XYZ_D50, vs_prof->matrix_in_transposed, vs_prof->lut_in,
                             vs_prof->unbounded_coeffs_in, vs_prof->lutsize, vs_prof->nonlinearlut);
  if(vs_type == DT_LIB_HISTOGRAM_VECTORSCOPE_CIELUV)
  {
    dt_aligned_pixel_t xyY_D50;
    dt_XYZ_to_xyY(XYZ_D50, xyY_D50);
    dt_xyY_to_Luv(xyY_D50, chromaticity);
  }
  else
  {
    dt_aligned_pixel_t XYZ_D65;
    dt_XYZ_D50_2_XYZ_D65(XYZ_D50, XYZ_D65);
    dt_XYZ_2_JzAzBz(XYZ_D65, chromaticity);
  }
  if(vs_scale == DT_LIB_HISTOGRAM_SCALE_LOGARITHMIC)
    log_scale(&chromaticity[1], &chromaticity[2], max_radius);

  d->vectorscope_pt[0] = chromaticity[1];
  d->vectorscope_pt[1] = chromaticity[2];

  // if live simple visualized, find their position
  if(d->vectorscope_samples && darktable.lib->proxy.colorpicker.display_samples)
  {
    g_slist_free_full((GSList *)d->vectorscope_samples, free);
    d->vectorscope_samples = NULL;
    d->selected_sample = -1;
  }
  GSList *samples = darktable.lib->proxy.colorpicker.live_samples;
  if(samples)
  {
    const dt_colorpicker_sample_t *selected = darktable.lib->proxy.colorpicker.selected_sample;

    int pos = 0;
    for(; samples; samples = g_slist_next(samples))
    {
      sample = samples->data;
      if(sample == selected) d->selected_sample = pos;
      pos++;

      //find coordinates
      for(int k = 0; k < 3; k++)
      {
        switch(statistic)
        {
          case DT_LIB_COLORPICKER_STATISTIC_MEAN:
            RGB[k] = sample->picked_color_rgb_mean[k];
            break;

          case DT_LIB_COLORPICKER_STATISTIC_MIN:
            RGB[k] = sample->picked_color_rgb_min[k];
            break;

          case DT_LIB_COLORPICKER_STATISTIC_MAX:
            RGB[k] = sample->picked_color_rgb_max[k];
            break;
          default:
            fprintf(stderr, "[histogram] unsupported color picker statistics %i\n", statistic);
            break;
        }
      }

      dt_ioppr_rgb_matrix_to_xyz(RGB, XYZ_D50, vs_prof->matrix_in_transposed, vs_prof->lut_in,
                                 vs_prof->unbounded_coeffs_in, vs_prof->lutsize, vs_prof->nonlinearlut);
      if(vs_type == DT_LIB_HISTOGRAM_VECTORSCOPE_CIELUV)
      {
        dt_aligned_pixel_t xyY_D50;
        dt_XYZ_to_xyY(XYZ_D50, xyY_D50);
        dt_xyY_to_Luv(xyY_D50, chromaticity);
      }
      else
      {
        dt_aligned_pixel_t XYZ_D65;
        dt_XYZ_D50_2_XYZ_D65(XYZ_D50, XYZ_D65);
        dt_XYZ_2_JzAzBz(XYZ_D65, chromaticity);
      }
      if(vs_scale == DT_LIB_HISTOGRAM_SCALE_LOGARITHMIC)
        log_scale(&chromaticity[1], &chromaticity[2], max_radius);

      float *sample_xy = (float *)calloc(2, sizeof(float));

      sample_xy[0] = chromaticity[1];
      sample_xy[1] = chromaticity[2];

      d->vectorscope_samples = g_slist_append(d->vectorscope_samples, sample_xy);
    }
  }
```
becomes

```
  // find position of the primary sample
  sample = darktable.lib->proxy.colorpicker.primary_sample;
  for(int k = 0; k < 3; k++)
  {
    switch(statistic)
    {
      case DT_LIB_COLORPICKER_STATISTIC_MEAN:
        RGB[k] = sample->picked_color_rgb_mean[k];
        break;

      case DT_LIB_COLORPICKER_STATISTIC_MIN:
        RGB[k] = sample->picked_color_rgb_min[k];
        break;

      case DT_LIB_COLORPICKER_STATISTIC_MAX:
        RGB[k] = sample->picked_color_rgb_max[k];
        break;
      default:
        fprintf(stderr, "[histogram] unsupported color picker statistics %i\n", statistic);
        break;
    }
  }

  if(vs_type != DT_LIB_HISTOGRAM_VECTORSCOPE_RYB)
  {

    dt_ioppr_rgb_matrix_to_xyz(RGB, XYZ_D50, vs_prof->matrix_in_transposed, vs_prof->lut_in,
                               vs_prof->unbounded_coeffs_in, vs_prof->lutsize, vs_prof->nonlinearlut);
    if(vs_type == DT_LIB_HISTOGRAM_VECTORSCOPE_CIELUV)
    {
      dt_aligned_pixel_t xyY_D50;
      dt_XYZ_to_xyY(XYZ_D50, xyY_D50);
      dt_xyY_to_Luv(xyY_D50, chromaticity);
    }
    else
    {
      dt_aligned_pixel_t XYZ_D65;
      dt_XYZ_D50_2_XYZ_D65(XYZ_D50, XYZ_D65);
      dt_XYZ_2_JzAzBz(XYZ_D65, chromaticity);
    }
  }
  else
  {
    dt_aligned_pixel_t RYB, rgb, HCV;
    for_each_channel(ch, aligned(rgb, RGB:16))
      rgb[ch] = RGB[ch] <= 0.04045f ? RGB[ch] / 12.92f : powf((RGB[ch] + 0.055f) / (1.0f + 0.055f), 2.4f);
    _rgb2ryb(rgb, RYB, d);
    dt_RGB_2_HCV(RYB, HCV);
    const float alpha = 2.0 * M_PI * HCV[0];
    chromaticity[1] = cosf(alpha) * HCV[1] * 0.01;
    chromaticity[2] = sinf(alpha) * HCV[1] * 0.01;
  }

  if(vs_scale == DT_LIB_HISTOGRAM_SCALE_LOGARITHMIC)
    log_scale(&chromaticity[1], &chromaticity[2], max_radius);

  d->vectorscope_pt[0] = chromaticity[1];
  d->vectorscope_pt[1] = chromaticity[2];

  // if live simple visualized, find their position
  if(d->vectorscope_samples && darktable.lib->proxy.colorpicker.display_samples)
  {
    g_slist_free_full((GSList *)d->vectorscope_samples, free);
    d->vectorscope_samples = NULL;
    d->selected_sample = -1;
  }
  GSList *samples = darktable.lib->proxy.colorpicker.live_samples;
  if(samples)
  {
    const dt_colorpicker_sample_t *selected = darktable.lib->proxy.colorpicker.selected_sample;

    int pos = 0;
    for(; samples; samples = g_slist_next(samples))
    {
      sample = samples->data;
      if(sample == selected) d->selected_sample = pos;
      pos++;

      //find coordinates
      for(int k = 0; k < 3; k++)
      {
        switch(statistic)
        {
          case DT_LIB_COLORPICKER_STATISTIC_MEAN:
            RGB[k] = sample->picked_color_rgb_mean[k];
            break;

          case DT_LIB_COLORPICKER_STATISTIC_MIN:
            RGB[k] = sample->picked_color_rgb_min[k];
            break;

          case DT_LIB_COLORPICKER_STATISTIC_MAX:
            RGB[k] = sample->picked_color_rgb_max[k];
            break;
          default:
            fprintf(stderr, "[histogram] unsupported color picker statistics %i\n", statistic);
            break;
        }
      }

      if(vs_type != DT_LIB_HISTOGRAM_VECTORSCOPE_RYB)
      {

        dt_ioppr_rgb_matrix_to_xyz(RGB, XYZ_D50, vs_prof->matrix_in_transposed, vs_prof->lut_in,
                                   vs_prof->unbounded_coeffs_in, vs_prof->lutsize, vs_prof->nonlinearlut);
        if(vs_type == DT_LIB_HISTOGRAM_VECTORSCOPE_CIELUV)
        {
          dt_aligned_pixel_t xyY_D50;
          dt_XYZ_to_xyY(XYZ_D50, xyY_D50);
          dt_xyY_to_Luv(xyY_D50, chromaticity);
        }
        else
        {
          dt_aligned_pixel_t XYZ_D65;
          dt_XYZ_D50_2_XYZ_D65(XYZ_D50, XYZ_D65);
          dt_XYZ_2_JzAzBz(XYZ_D65, chromaticity);
        }
      }
      else
      {
        dt_aligned_pixel_t RYB, rgb, HCV;
        for_each_channel(ch, aligned(rgb, RGB:16))
          rgb[ch] = RGB[ch] <= 0.04045f ? RGB[ch] / 12.92f : powf((RGB[ch] + 0.055f) / (1.0f + 0.055f), 2.4f);
        _rgb2ryb(rgb, RYB, d);
        dt_RGB_2_HCV(RYB, HCV);
        const float alpha = 2.0 * M_PI * HCV[0];
        chromaticity[1] = cosf(alpha) * HCV[1] * 0.01;
        chromaticity[2] = sinf(alpha) * HCV[1] * 0.01;
      }

      if(vs_scale == DT_LIB_HISTOGRAM_SCALE_LOGARITHMIC)
        log_scale(&chromaticity[1], &chromaticity[2], max_radius);

      float *sample_xy = (float *)calloc(2, sizeof [...]

2021-09-03 12:06 UTC, phweyland commented
@Mark-64 Great. Thanks for preparing the fix.
I've just rebased, I've integrated your code and created a routine as you suggested.
However I see the main sample on the scope, but not the live ones, whatever the vectorscope chosen.
I'll try to debug that.

2021-09-03 13:54 UTC, Mark-64 commented
I tested this code on my local merge with master and it works.
If you rebased, you should have taken all the changes in master as well, so I don't understand.
I can have a look, but only in few hours

2021-09-03 14:05 UTC, phweyland commented
> so I don't understand.

Sorry, I'm back and I see I have tested the wrong executable. Yes everything works fine. Sorry again for inconvenience!

2021-09-03 16:24 UTC, Mark-64 commented
Yes :-)

![immagine](https://user-images.githubusercontent.com/43290988/132038008-2c0fccca-0442-4fe7-8c36-1217b5caef2a.png)

2021-09-03 16:52 UTC, phweyland commented
small change on ryb routine parameters.
However in the omp loop (histogram.c line 600) I don't know what to do about the parameter d->rgb2ryb_ypp. 
Is there something to do ?

2021-09-03 19:04 UTC, phweyland commented
rebased to resolve conflicts

2021-09-03 21:20 UTC, phweyland commented
About colors, different parameters influence the colorfulness of the graph.
- the fading of the graph colors. There is a parameter which could be used to get more or less vivid colors.
- the blending with the theme's background. The clearer the theme is the more the background colors are washed. The only action I can see is to play with the darkness of the vectorscope background.
- the graph color saturation is also proportional to the density of points for a given chroma. So the color of the graph is not directly representative of the corresponding color in the image by design, even if we give the user some way to tweak the saturation. 

So I'm afraid the user cannot expect to rely on the graph's colors to get an immediate feeling of the harmony.
He has to learn how to read the vectorscope with these 3 dimensions:
- hue: the angle (that''s not graph color which defines the color)
- chroma: the distance from center
- density of image's points with that color: the colorfulness. In any case this last one is not very readable with the grey themes.
- the lightness/brightness being not represented

Any thoughts ?
Any idea to try to improve the color feeling, at least for the RYB vectorscope ?
Pinging also @dtorop

2021-09-03 22:39 UTC, dtorop commented
>  However in the omp loop (histogram.c line 600) I don't know what to do about the parameter d->rgb2ryb_ypp.

I think you just put `d` in the `dt_omp_firstprivate()` clause (should already be there) and then that pointer is passed to each thread. If that is the question?

> About colors, different parameters influence the colorfulness of the graph.

This all seems a good rundown. I'd add one more, which is the Cairo compositing operation with which the graph is drawn. So long as it is `CAIRO_OPERATOR_ADD`, the graph will desaturate as the background lightens up.

Here's with current code (not this PR), `CAIRO_OPERATOR_ADD` and the grey theme:

![image](https://user-images.githubusercontent.com/2311860/132071219-249f0eaa-d9be-4b10-99d7-75509b0eb7d3.png)

With `CAIRO_OPERATOR_OVER`:

![image](https://user-images.githubusercontent.com/2311860/132070980-4303f0c5-7b07-4710-a5d4-25287ebcb1e8.png)

With `CAIRO_OPERATOR_HARD_LIGHT`:

![image](https://user-images.githubusercontent.com/2311860/132071083-9654bd0e-4cb3-4885-a883-6bcedd608cd5.png)

The graph will still appear more vivid with a dark theme, due to more color contrast with the background color. Here's with `CAIRO_OPERATOR_OVER` and the "darker" theme:

![image](https://user-images.githubusercontent.com/2311860/132071562-46cfba08-616f-4b91-ab25-09c300f0dcb8.png)

Perhaps shifting around the drawing mode (and tuning some other parameters) could produce something nice?

Here's a diff using `_OVER`:

```diff
modified   src/libs/histogram.c
@@ -1004,8 +1004,7 @@ static void _lib_histogram_draw_vectorscope(dt_lib_histogram_t *d, cairo_t *cr,
   const gboolean display_live_samples = d->vectorscope_samples &&
       darktable.lib->proxy.colorpicker.display_samples;
 
-  if(display_primary_sample || display_live_samples)
-    cairo_push_group(cr);
+  cairo_push_group(cr);
   cairo_set_source(cr, bkgd_pat);
   cairo_mask(cr, graph_pat);
   cairo_set_operator(cr, CAIRO_OPERATOR_HARD_LIGHT);
@@ -1017,13 +1016,9 @@ static void _lib_histogram_draw_vectorscope(dt_lib_histogram_t *d, cairo_t *cr,
   cairo_pattern_destroy(graph_pat);
   cairo_surface_destroy(graph_surface);
 
-  if(display_primary_sample || display_live_samples)
-  {
-    cairo_pop_group_to_source(cr);
-    cairo_paint_with_alpha(cr, 0.5);
-  }
-
+  cairo_pop_group_to_source(cr);
   cairo_set_operator(cr, CAIRO_OPERATOR_OVER);
+  cairo_paint_with_alpha(cr, (display_primary_sample || display_live_samples) ? 0.5 : 1.0);
 
   // overlay central circle
   set_color(cr, darktable.bauhaus->graph_grid);
```

2021-09-03 23:19 UTC, phweyland commented
Thanks @dtorop, I'll take the time to digest this.

2021-09-04 15:41 UTC, phweyland commented
> I think you just put `d` in the `dt_omp_firstprivate()` clause (should already be there) and then that pointer is passed to each thread. If that is the question?

Yes it was the question, thanks.
As `d->rgb2ryb_ypp` is also a pointer, and `d` not used otherwise, I've replaced `d` by a local copy of `rgb2ryb_ypp`.

2021-09-04 18:12 UTC, dtorop commented
Also! I can't guarantee that #9925 hasn't messed up this PR... If so, apologies, but it shouldn't be too difficult to fix.

2021-09-04 21:28 UTC, phweyland commented
> I can't guarantee that #9925 hasn't messed up this PR... If so, apologies, but it shouldn't be too difficult to fix.

No problem, I've rebased and haven't found any issue!

2021-09-05 01:39 UTC, phweyland commented
@TurboGit I think the PR is ok for review.
I'll try to improve a little bit the vectorscope colors but in another PR (which may take advantage of #9640 - local preferences).

2021-09-05 19:40 UTC, TurboGit requested changes
TIA.

2021-09-05 19:40 UTC, TurboGit commented on src/libs/histogram.c
> +      gtk_widget_set_tooltip_text(d->colorspace_button, _("set view to RYB"));
This is wrong here, it should be on previous text. The message here describe which mode will be displayed after clicking on it. So the message here should be `"set view to u*v*"` and the message for the previous switch entry must be `"set view to RYB"`.

2021-09-05 19:40 UTC, TurboGit commented on src/libs/histogram.c
> +  if(vs_type != DT_LIB_HISTOGRAM_VECTORSCOPE_RYB)
let's simplify the code here with a swicth:

```
switch(vs_type)
{
   case DT_LIB_HISTOGRAM_VECTORSCOPE_RYB:
   ...
```
And yes I'll duplicate the call dt_ioppr_rgb_matrix_to_xyz() in each alternatives maybe even the declaration of XYZ_D50 which is not used for the RYB case.

2021-09-05 19:40 UTC, TurboGit commented on src/libs/histogram.c
> +      if(vs_type != DT_LIB_HISTOGRAM_VECTORSCOPE_RYB)
see comment below where I think a swicth() should be easier to read and have a clear separate entries for the 3 supported cases.

2021-09-06 14:31 UTC, phweyland commented
All done. Thanks !

2021-09-06 19:03 UTC, johnny-bit commented
CI got "problematiced" in GCC 11 nofeatures + nosse with :
```
/home/runner/work/darktable/darktable/src/src/libs/histogram.c: In function ‘dt_lib_histogram_process’:
/home/runner/work/darktable/darktable/src/src/libs/histogram.c:391:46: error: ‘chromaticity[1]’ is used uninitialized [-Werror=uninitialized]
  391 |       dt_aligned_pixel_t rgb_scope, XYZ_D50, chromaticity;
      |                                              ^~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.
```

2021-09-06 19:10 UTC, phweyland commented
Travelling, I'll check this asap.

2021-09-07 08:02 UTC, TurboGit commented
> Travelling, I'll check this asap.

The fix looks trivial, we need to initialize chromaticity as indeed chromaticity[0] is not used afterward and in the RYB case we only set the index 1 and 2. Will merge and add necessary init for GCC 11.

2021-09-07 08:02 UTC, merged