denoiseprofile: fix wavelet preset
darktable-org/darktable pull request #9951
Opened 2021-09-07 06:05 UTC by rawfiner

Preset was made for param version 10, but in the code the version was not appearing. Thus, the strength of the preset was too high with the changes of #9832 .
This PR puts the version number for the preset, so that it is automatically updated for next params versions.

2021-09-08 15:58 UTC, TurboGit commented
But this will trigger the migration path at every run, and so we get on the console:

```
[imageop_init_presets] updating 'denoiseprofile' preset 'ondelettes: seulement chroma' from version 10 to version 11
to:'gz06eJxjYGiwZ2B44DBr5kwgjQBnz5yxZQDLNexnwAIYofTqVVp2q1etsgMy7YFs+9DQUHuIvkElR2+MD+DUxwgNVxgGAMZTQOU='
```
It would be best to migrate the preset once for all and keep `self->version()`.

2021-09-08 15:59 UTC, TurboGit requested changes
Do migration of preset once for all.

2021-09-10 19:01 UTC, rawfiner commented
I agree
I pushed the updated version

2021-09-11 07:33 UTC, TurboGit approved these changes
Looks good now. Thanks!

2021-09-11 07:33 UTC, merged